/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTransactionExportRequest,
  ErrorResponse,
  TransactionExportJob,
} from '../models/index';
import {
    CreateTransactionExportRequestFromJSON,
    CreateTransactionExportRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TransactionExportJobFromJSON,
    TransactionExportJobToJSON,
} from '../models/index';

export interface CreateTransactionExportOperationRequest {
    createTransactionExportRequest: CreateTransactionExportRequest;
}

export interface DownloadTransactionExportRequest {
    exportID: string;
}

export interface GetTransactionExportByIDRequest {
    exportID: string;
}

/**
 * 
 */
export class ExportsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTransactionExport without sending the request
     */
    async createTransactionExportRequestOpts(requestParameters: CreateTransactionExportOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createTransactionExportRequest'] == null) {
            throw new runtime.RequiredError(
                'createTransactionExportRequest',
                'Required parameter "createTransactionExportRequest" was null or undefined when calling createTransactionExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/exports/transactions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTransactionExportRequestToJSON(requestParameters['createTransactionExportRequest']),
        };
    }

    /**
     * Create a transactions export job
     */
    async createTransactionExportRaw(requestParameters: CreateTransactionExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionExportJob>> {
        const requestOptions = await this.createTransactionExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionExportJobFromJSON(jsonValue));
    }

    /**
     * Create a transactions export job
     */
    async createTransactionExport(requestParameters: CreateTransactionExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionExportJob> {
        const response = await this.createTransactionExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadTransactionExport without sending the request
     */
    async downloadTransactionExportRequestOpts(requestParameters: DownloadTransactionExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['exportID'] == null) {
            throw new runtime.RequiredError(
                'exportID',
                'Required parameter "exportID" was null or undefined when calling downloadTransactionExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/exports/transactions/{exportID}/download`;
        urlPath = urlPath.replace(`{${"exportID"}}`, encodeURIComponent(String(requestParameters['exportID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download a completed transaction export
     */
    async downloadTransactionExportRaw(requestParameters: DownloadTransactionExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadTransactionExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download a completed transaction export
     */
    async downloadTransactionExport(requestParameters: DownloadTransactionExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadTransactionExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransactionExportByID without sending the request
     */
    async getTransactionExportByIDRequestOpts(requestParameters: GetTransactionExportByIDRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['exportID'] == null) {
            throw new runtime.RequiredError(
                'exportID',
                'Required parameter "exportID" was null or undefined when calling getTransactionExportByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/exports/transactions/{exportID}`;
        urlPath = urlPath.replace(`{${"exportID"}}`, encodeURIComponent(String(requestParameters['exportID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get transaction export job status
     */
    async getTransactionExportByIDRaw(requestParameters: GetTransactionExportByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionExportJob>> {
        const requestOptions = await this.getTransactionExportByIDRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionExportJobFromJSON(jsonValue));
    }

    /**
     * Get transaction export job status
     */
    async getTransactionExportByID(requestParameters: GetTransactionExportByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionExportJob> {
        const response = await this.getTransactionExportByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
