/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Tag,
  TagCreateRequest,
  TagListResponse,
  TagPatchRequest,
  Transaction,
  TransactionTagsReplaceRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TagFromJSON,
    TagToJSON,
    TagCreateRequestFromJSON,
    TagCreateRequestToJSON,
    TagListResponseFromJSON,
    TagListResponseToJSON,
    TagPatchRequestFromJSON,
    TagPatchRequestToJSON,
    TransactionFromJSON,
    TransactionToJSON,
    TransactionTagsReplaceRequestFromJSON,
    TransactionTagsReplaceRequestToJSON,
} from '../models/index';

export interface AttachTagToTransactionRequest {
    accountID: string;
    transactionID: string;
    tagID: string;
}

export interface CreateTagRequest {
    tagCreateRequest: TagCreateRequest;
}

export interface DeleteTagRequest {
    tagID: string;
}

export interface DetachTagFromTransactionRequest {
    accountID: string;
    transactionID: string;
    tagID: string;
}

export interface GetTagByIDRequest {
    tagID: string;
}

export interface PatchTagRequest {
    tagID: string;
    tagPatchRequest: TagPatchRequest;
}

export interface ReplaceTransactionTagsRequest {
    accountID: string;
    transactionID: string;
    transactionTagsReplaceRequest: TransactionTagsReplaceRequest;
}

/**
 * 
 */
export class TagsApi extends runtime.BaseAPI {

    /**
     * Creates request options for attachTagToTransaction without sending the request
     */
    async attachTagToTransactionRequestOpts(requestParameters: AttachTagToTransactionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountID'] == null) {
            throw new runtime.RequiredError(
                'accountID',
                'Required parameter "accountID" was null or undefined when calling attachTagToTransaction().'
            );
        }

        if (requestParameters['transactionID'] == null) {
            throw new runtime.RequiredError(
                'transactionID',
                'Required parameter "transactionID" was null or undefined when calling attachTagToTransaction().'
            );
        }

        if (requestParameters['tagID'] == null) {
            throw new runtime.RequiredError(
                'tagID',
                'Required parameter "tagID" was null or undefined when calling attachTagToTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/accounts/{accountID}/transactions/{transactionID}/tags/{tagID}`;
        urlPath = urlPath.replace(`{${"accountID"}}`, encodeURIComponent(String(requestParameters['accountID'])));
        urlPath = urlPath.replace(`{${"transactionID"}}`, encodeURIComponent(String(requestParameters['transactionID'])));
        urlPath = urlPath.replace(`{${"tagID"}}`, encodeURIComponent(String(requestParameters['tagID'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Attach a tag to a transaction owned by the current authenticated user
     */
    async attachTagToTransactionRaw(requestParameters: AttachTagToTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Transaction>> {
        const requestOptions = await this.attachTagToTransactionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
    }

    /**
     * Attach a tag to a transaction owned by the current authenticated user
     */
    async attachTagToTransaction(requestParameters: AttachTagToTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
        const response = await this.attachTagToTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTag without sending the request
     */
    async createTagRequestOpts(requestParameters: CreateTagRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tagCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'tagCreateRequest',
                'Required parameter "tagCreateRequest" was null or undefined when calling createTag().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tags`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TagCreateRequestToJSON(requestParameters['tagCreateRequest']),
        };
    }

    /**
     * Create a tag for current authenticated user
     */
    async createTagRaw(requestParameters: CreateTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tag>> {
        const requestOptions = await this.createTagRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
    }

    /**
     * Create a tag for current authenticated user
     */
    async createTag(requestParameters: CreateTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tag> {
        const response = await this.createTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTag without sending the request
     */
    async deleteTagRequestOpts(requestParameters: DeleteTagRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tagID'] == null) {
            throw new runtime.RequiredError(
                'tagID',
                'Required parameter "tagID" was null or undefined when calling deleteTag().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/tags/{tagID}`;
        urlPath = urlPath.replace(`{${"tagID"}}`, encodeURIComponent(String(requestParameters['tagID'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete tag by ID for current authenticated user
     */
    async deleteTagRaw(requestParameters: DeleteTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTagRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete tag by ID for current authenticated user
     */
    async deleteTag(requestParameters: DeleteTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTagRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detachTagFromTransaction without sending the request
     */
    async detachTagFromTransactionRequestOpts(requestParameters: DetachTagFromTransactionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountID'] == null) {
            throw new runtime.RequiredError(
                'accountID',
                'Required parameter "accountID" was null or undefined when calling detachTagFromTransaction().'
            );
        }

        if (requestParameters['transactionID'] == null) {
            throw new runtime.RequiredError(
                'transactionID',
                'Required parameter "transactionID" was null or undefined when calling detachTagFromTransaction().'
            );
        }

        if (requestParameters['tagID'] == null) {
            throw new runtime.RequiredError(
                'tagID',
                'Required parameter "tagID" was null or undefined when calling detachTagFromTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/accounts/{accountID}/transactions/{transactionID}/tags/{tagID}`;
        urlPath = urlPath.replace(`{${"accountID"}}`, encodeURIComponent(String(requestParameters['accountID'])));
        urlPath = urlPath.replace(`{${"transactionID"}}`, encodeURIComponent(String(requestParameters['transactionID'])));
        urlPath = urlPath.replace(`{${"tagID"}}`, encodeURIComponent(String(requestParameters['tagID'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detach a tag from a transaction owned by the current authenticated user
     */
    async detachTagFromTransactionRaw(requestParameters: DetachTagFromTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Transaction>> {
        const requestOptions = await this.detachTagFromTransactionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
    }

    /**
     * Detach a tag from a transaction owned by the current authenticated user
     */
    async detachTagFromTransaction(requestParameters: DetachTagFromTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
        const response = await this.detachTagFromTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTagByID without sending the request
     */
    async getTagByIDRequestOpts(requestParameters: GetTagByIDRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tagID'] == null) {
            throw new runtime.RequiredError(
                'tagID',
                'Required parameter "tagID" was null or undefined when calling getTagByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/tags/{tagID}`;
        urlPath = urlPath.replace(`{${"tagID"}}`, encodeURIComponent(String(requestParameters['tagID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get tag by ID for current authenticated user
     */
    async getTagByIDRaw(requestParameters: GetTagByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tag>> {
        const requestOptions = await this.getTagByIDRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
    }

    /**
     * Get tag by ID for current authenticated user
     */
    async getTagByID(requestParameters: GetTagByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tag> {
        const response = await this.getTagByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTags without sending the request
     */
    async listTagsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/tags`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List tags for current authenticated user
     */
    async listTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TagListResponse>> {
        const requestOptions = await this.listTagsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TagListResponseFromJSON(jsonValue));
    }

    /**
     * List tags for current authenticated user
     */
    async listTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TagListResponse> {
        const response = await this.listTagsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchTag without sending the request
     */
    async patchTagRequestOpts(requestParameters: PatchTagRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tagID'] == null) {
            throw new runtime.RequiredError(
                'tagID',
                'Required parameter "tagID" was null or undefined when calling patchTag().'
            );
        }

        if (requestParameters['tagPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'tagPatchRequest',
                'Required parameter "tagPatchRequest" was null or undefined when calling patchTag().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tags/{tagID}`;
        urlPath = urlPath.replace(`{${"tagID"}}`, encodeURIComponent(String(requestParameters['tagID'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TagPatchRequestToJSON(requestParameters['tagPatchRequest']),
        };
    }

    /**
     * Patch tag fields for current authenticated user
     */
    async patchTagRaw(requestParameters: PatchTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tag>> {
        const requestOptions = await this.patchTagRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
    }

    /**
     * Patch tag fields for current authenticated user
     */
    async patchTag(requestParameters: PatchTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tag> {
        const response = await this.patchTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for replaceTransactionTags without sending the request
     */
    async replaceTransactionTagsRequestOpts(requestParameters: ReplaceTransactionTagsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountID'] == null) {
            throw new runtime.RequiredError(
                'accountID',
                'Required parameter "accountID" was null or undefined when calling replaceTransactionTags().'
            );
        }

        if (requestParameters['transactionID'] == null) {
            throw new runtime.RequiredError(
                'transactionID',
                'Required parameter "transactionID" was null or undefined when calling replaceTransactionTags().'
            );
        }

        if (requestParameters['transactionTagsReplaceRequest'] == null) {
            throw new runtime.RequiredError(
                'transactionTagsReplaceRequest',
                'Required parameter "transactionTagsReplaceRequest" was null or undefined when calling replaceTransactionTags().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/{accountID}/transactions/{transactionID}/tags`;
        urlPath = urlPath.replace(`{${"accountID"}}`, encodeURIComponent(String(requestParameters['accountID'])));
        urlPath = urlPath.replace(`{${"transactionID"}}`, encodeURIComponent(String(requestParameters['transactionID'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionTagsReplaceRequestToJSON(requestParameters['transactionTagsReplaceRequest']),
        };
    }

    /**
     * Replace all tags for a transaction owned by the current authenticated user
     */
    async replaceTransactionTagsRaw(requestParameters: ReplaceTransactionTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Transaction>> {
        const requestOptions = await this.replaceTransactionTagsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
    }

    /**
     * Replace all tags for a transaction owned by the current authenticated user
     */
    async replaceTransactionTags(requestParameters: ReplaceTransactionTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
        const response = await this.replaceTransactionTagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
