/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  TransactionRule,
  TransactionRuleCreateRequest,
  TransactionRuleListResponse,
  TransactionRulePatchRequest,
  TransactionRuleSourceScope,
  TransactionRuleStatus,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TransactionRuleFromJSON,
    TransactionRuleToJSON,
    TransactionRuleCreateRequestFromJSON,
    TransactionRuleCreateRequestToJSON,
    TransactionRuleListResponseFromJSON,
    TransactionRuleListResponseToJSON,
    TransactionRulePatchRequestFromJSON,
    TransactionRulePatchRequestToJSON,
    TransactionRuleSourceScopeFromJSON,
    TransactionRuleSourceScopeToJSON,
    TransactionRuleStatusFromJSON,
    TransactionRuleStatusToJSON,
} from '../models/index';

export interface CreateTransactionRuleRequest {
    transactionRuleCreateRequest: TransactionRuleCreateRequest;
}

export interface DeleteTransactionRuleRequest {
    ruleID: string;
}

export interface GetTransactionRuleByIDRequest {
    ruleID: string;
}

export interface ListTransactionRulesRequest {
    status?: Array<TransactionRuleStatus>;
    sourceScope?: Array<TransactionRuleSourceScope>;
}

export interface PatchTransactionRuleRequest {
    ruleID: string;
    transactionRulePatchRequest: TransactionRulePatchRequest;
}

/**
 * 
 */
export class TransactionRulesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTransactionRule without sending the request
     */
    async createTransactionRuleRequestOpts(requestParameters: CreateTransactionRuleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transactionRuleCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'transactionRuleCreateRequest',
                'Required parameter "transactionRuleCreateRequest" was null or undefined when calling createTransactionRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/transactions/rules`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionRuleCreateRequestToJSON(requestParameters['transactionRuleCreateRequest']),
        };
    }

    /**
     * Create a transaction rule for current authenticated user
     */
    async createTransactionRuleRaw(requestParameters: CreateTransactionRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionRule>> {
        const requestOptions = await this.createTransactionRuleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionRuleFromJSON(jsonValue));
    }

    /**
     * Create a transaction rule for current authenticated user
     */
    async createTransactionRule(requestParameters: CreateTransactionRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionRule> {
        const response = await this.createTransactionRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTransactionRule without sending the request
     */
    async deleteTransactionRuleRequestOpts(requestParameters: DeleteTransactionRuleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleID'] == null) {
            throw new runtime.RequiredError(
                'ruleID',
                'Required parameter "ruleID" was null or undefined when calling deleteTransactionRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/transactions/rules/{ruleID}`;
        urlPath = urlPath.replace(`{${"ruleID"}}`, encodeURIComponent(String(requestParameters['ruleID'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete transaction rule by ID for current authenticated user
     */
    async deleteTransactionRuleRaw(requestParameters: DeleteTransactionRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTransactionRuleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete transaction rule by ID for current authenticated user
     */
    async deleteTransactionRule(requestParameters: DeleteTransactionRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTransactionRuleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTransactionRuleByID without sending the request
     */
    async getTransactionRuleByIDRequestOpts(requestParameters: GetTransactionRuleByIDRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleID'] == null) {
            throw new runtime.RequiredError(
                'ruleID',
                'Required parameter "ruleID" was null or undefined when calling getTransactionRuleByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/transactions/rules/{ruleID}`;
        urlPath = urlPath.replace(`{${"ruleID"}}`, encodeURIComponent(String(requestParameters['ruleID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get transaction rule by ID for current authenticated user
     */
    async getTransactionRuleByIDRaw(requestParameters: GetTransactionRuleByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionRule>> {
        const requestOptions = await this.getTransactionRuleByIDRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionRuleFromJSON(jsonValue));
    }

    /**
     * Get transaction rule by ID for current authenticated user
     */
    async getTransactionRuleByID(requestParameters: GetTransactionRuleByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionRule> {
        const response = await this.getTransactionRuleByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTransactionRules without sending the request
     */
    async listTransactionRulesRequestOpts(requestParameters: ListTransactionRulesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['sourceScope'] != null) {
            queryParameters['source_scope'] = requestParameters['sourceScope']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/transactions/rules`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List transaction rules for current authenticated user
     */
    async listTransactionRulesRaw(requestParameters: ListTransactionRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionRuleListResponse>> {
        const requestOptions = await this.listTransactionRulesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionRuleListResponseFromJSON(jsonValue));
    }

    /**
     * List transaction rules for current authenticated user
     */
    async listTransactionRules(requestParameters: ListTransactionRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionRuleListResponse> {
        const response = await this.listTransactionRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchTransactionRule without sending the request
     */
    async patchTransactionRuleRequestOpts(requestParameters: PatchTransactionRuleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleID'] == null) {
            throw new runtime.RequiredError(
                'ruleID',
                'Required parameter "ruleID" was null or undefined when calling patchTransactionRule().'
            );
        }

        if (requestParameters['transactionRulePatchRequest'] == null) {
            throw new runtime.RequiredError(
                'transactionRulePatchRequest',
                'Required parameter "transactionRulePatchRequest" was null or undefined when calling patchTransactionRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/transactions/rules/{ruleID}`;
        urlPath = urlPath.replace(`{${"ruleID"}}`, encodeURIComponent(String(requestParameters['ruleID'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionRulePatchRequestToJSON(requestParameters['transactionRulePatchRequest']),
        };
    }

    /**
     * Patch transaction rule fields for current authenticated user
     */
    async patchTransactionRuleRaw(requestParameters: PatchTransactionRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionRule>> {
        const requestOptions = await this.patchTransactionRuleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionRuleFromJSON(jsonValue));
    }

    /**
     * Patch transaction rule fields for current authenticated user
     */
    async patchTransactionRule(requestParameters: PatchTransactionRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionRule> {
        const response = await this.patchTransactionRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
