/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingMonthlyLine
 */
export interface BillingMonthlyLine {
    /**
     * 
     * @type {string}
     * @memberof BillingMonthlyLine
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof BillingMonthlyLine
     */
    billingMonth: Date;
    /**
     * 
     * @type {string}
     * @memberof BillingMonthlyLine
     */
    licenseId: string;
    /**
     * 
     * @type {string}
     * @memberof BillingMonthlyLine
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof BillingMonthlyLine
     */
    meterType: string;
    /**
     * 
     * @type {number}
     * @memberof BillingMonthlyLine
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof BillingMonthlyLine
     */
    unitPriceUsd: string;
    /**
     * 
     * @type {string}
     * @memberof BillingMonthlyLine
     */
    amountUsd: string;
    /**
     * 
     * @type {string}
     * @memberof BillingMonthlyLine
     */
    currency: string;
}

/**
 * Check if a given object implements the BillingMonthlyLine interface.
 */
export function instanceOfBillingMonthlyLine(value: object): value is BillingMonthlyLine {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('billingMonth' in value) || value['billingMonth'] === undefined) return false;
    if (!('licenseId' in value) || value['licenseId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('meterType' in value) || value['meterType'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unitPriceUsd' in value) || value['unitPriceUsd'] === undefined) return false;
    if (!('amountUsd' in value) || value['amountUsd'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function BillingMonthlyLineFromJSON(json: any): BillingMonthlyLine {
    return BillingMonthlyLineFromJSONTyped(json, false);
}

export function BillingMonthlyLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingMonthlyLine {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'billingMonth': (new Date(json['billing_month'])),
        'licenseId': json['license_id'],
        'productId': json['product_id'],
        'meterType': json['meter_type'],
        'quantity': json['quantity'],
        'unitPriceUsd': json['unit_price_usd'],
        'amountUsd': json['amount_usd'],
        'currency': json['currency'],
    };
}

export function BillingMonthlyLineToJSON(json: any): BillingMonthlyLine {
    return BillingMonthlyLineToJSONTyped(json, false);
}

export function BillingMonthlyLineToJSONTyped(value?: BillingMonthlyLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'billing_month': value['billingMonth'].toISOString().substring(0,10),
        'license_id': value['licenseId'],
        'product_id': value['productId'],
        'meter_type': value['meterType'],
        'quantity': value['quantity'],
        'unit_price_usd': value['unitPriceUsd'],
        'amount_usd': value['amountUsd'],
        'currency': value['currency'],
    };
}

