/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BillingMonthlyLine } from './BillingMonthlyLine';
import {
    BillingMonthlyLineFromJSON,
    BillingMonthlyLineFromJSONTyped,
    BillingMonthlyLineToJSON,
    BillingMonthlyLineToJSONTyped,
} from './BillingMonthlyLine';

/**
 * 
 * @export
 * @interface BillingMonthlyListResponse
 */
export interface BillingMonthlyListResponse {
    /**
     * 
     * @type {Array<BillingMonthlyLine>}
     * @memberof BillingMonthlyListResponse
     */
    items: Array<BillingMonthlyLine>;
}

/**
 * Check if a given object implements the BillingMonthlyListResponse interface.
 */
export function instanceOfBillingMonthlyListResponse(value: object): value is BillingMonthlyListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BillingMonthlyListResponseFromJSON(json: any): BillingMonthlyListResponse {
    return BillingMonthlyListResponseFromJSONTyped(json, false);
}

export function BillingMonthlyListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingMonthlyListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BillingMonthlyLineFromJSON)),
    };
}

export function BillingMonthlyListResponseToJSON(json: any): BillingMonthlyListResponse {
    return BillingMonthlyListResponseToJSONTyped(json, false);
}

export function BillingMonthlyListResponseToJSONTyped(value?: BillingMonthlyListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(BillingMonthlyLineToJSON)),
    };
}

