/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkAccount } from './LinkAccount';
import {
    LinkAccountFromJSON,
    LinkAccountFromJSONTyped,
    LinkAccountToJSON,
    LinkAccountToJSONTyped,
} from './LinkAccount';
import type { LinkInstitution } from './LinkInstitution';
import {
    LinkInstitutionFromJSON,
    LinkInstitutionFromJSONTyped,
    LinkInstitutionToJSON,
    LinkInstitutionToJSONTyped,
} from './LinkInstitution';

/**
 * 
 * @export
 * @interface ConnectLinkMetadata
 */
export interface ConnectLinkMetadata {
    /**
     * 
     * @type {LinkInstitution}
     * @memberof ConnectLinkMetadata
     */
    institution: LinkInstitution;
    /**
     * 
     * @type {Array<LinkAccount>}
     * @memberof ConnectLinkMetadata
     */
    accounts: Array<LinkAccount>;
}

/**
 * Check if a given object implements the ConnectLinkMetadata interface.
 */
export function instanceOfConnectLinkMetadata(value: object): value is ConnectLinkMetadata {
    if (!('institution' in value) || value['institution'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function ConnectLinkMetadataFromJSON(json: any): ConnectLinkMetadata {
    return ConnectLinkMetadataFromJSONTyped(json, false);
}

export function ConnectLinkMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectLinkMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'institution': LinkInstitutionFromJSON(json['institution']),
        'accounts': ((json['accounts'] as Array<any>).map(LinkAccountFromJSON)),
    };
}

export function ConnectLinkMetadataToJSON(json: any): ConnectLinkMetadata {
    return ConnectLinkMetadataToJSONTyped(json, false);
}

export function ConnectLinkMetadataToJSONTyped(value?: ConnectLinkMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'institution': LinkInstitutionToJSON(value['institution']),
        'accounts': ((value['accounts'] as Array<any>).map(LinkAccountToJSON)),
    };
}

