/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectLinkMetadata } from './ConnectLinkMetadata';
import {
    ConnectLinkMetadataFromJSON,
    ConnectLinkMetadataFromJSONTyped,
    ConnectLinkMetadataToJSON,
    ConnectLinkMetadataToJSONTyped,
} from './ConnectLinkMetadata';

/**
 * 
 * @export
 * @interface ConnectLinkTokenRequest
 */
export interface ConnectLinkTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof ConnectLinkTokenRequest
     */
    publicToken: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectLinkTokenRequest
     */
    linkToken: string;
    /**
     * 
     * @type {ConnectLinkMetadata}
     * @memberof ConnectLinkTokenRequest
     */
    metadata: ConnectLinkMetadata;
}

/**
 * Check if a given object implements the ConnectLinkTokenRequest interface.
 */
export function instanceOfConnectLinkTokenRequest(value: object): value is ConnectLinkTokenRequest {
    if (!('publicToken' in value) || value['publicToken'] === undefined) return false;
    if (!('linkToken' in value) || value['linkToken'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ConnectLinkTokenRequestFromJSON(json: any): ConnectLinkTokenRequest {
    return ConnectLinkTokenRequestFromJSONTyped(json, false);
}

export function ConnectLinkTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectLinkTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'publicToken': json['public_token'],
        'linkToken': json['link_token'],
        'metadata': ConnectLinkMetadataFromJSON(json['metadata']),
    };
}

export function ConnectLinkTokenRequestToJSON(json: any): ConnectLinkTokenRequest {
    return ConnectLinkTokenRequestToJSONTyped(json, false);
}

export function ConnectLinkTokenRequestToJSONTyped(value?: ConnectLinkTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_token': value['publicToken'],
        'link_token': value['linkToken'],
        'metadata': ConnectLinkMetadataToJSON(value['metadata']),
    };
}

