/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectLinkTokenResponse
 */
export interface ConnectLinkTokenResponse {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof ConnectLinkTokenResponse
     */
    accounts: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {string}
     * @memberof ConnectLinkTokenResponse
     */
    connectionId: string;
}

/**
 * Check if a given object implements the ConnectLinkTokenResponse interface.
 */
export function instanceOfConnectLinkTokenResponse(value: object): value is ConnectLinkTokenResponse {
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    return true;
}

export function ConnectLinkTokenResponseFromJSON(json: any): ConnectLinkTokenResponse {
    return ConnectLinkTokenResponseFromJSONTyped(json, false);
}

export function ConnectLinkTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectLinkTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': json['accounts'],
        'connectionId': json['connection_id'],
    };
}

export function ConnectLinkTokenResponseToJSON(json: any): ConnectLinkTokenResponse {
    return ConnectLinkTokenResponseToJSONTyped(json, false);
}

export function ConnectLinkTokenResponseToJSONTyped(value?: ConnectLinkTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': value['accounts'],
        'connection_id': value['connectionId'],
    };
}

