/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsoleConnection } from './ConsoleConnection';
import {
    ConsoleConnectionFromJSON,
    ConsoleConnectionFromJSONTyped,
    ConsoleConnectionToJSON,
    ConsoleConnectionToJSONTyped,
} from './ConsoleConnection';

/**
 *
 * @export
 * @interface ConsoleConnectionPage
 */
export interface ConsoleConnectionPage {
    /**
     *
     * @type {Array<ConsoleConnection>}
     * @memberof ConsoleConnectionPage
     */
    items: Array<ConsoleConnection>;
    /**
     *
     * @type {number}
     * @memberof ConsoleConnectionPage
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof ConsoleConnectionPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the ConsoleConnectionPage interface.
 */
export function instanceOfConsoleConnectionPage(value: object): value is ConsoleConnectionPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function ConsoleConnectionPageFromJSON(json: any): ConsoleConnectionPage {
    return ConsoleConnectionPageFromJSONTyped(json, false);
}

export function ConsoleConnectionPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleConnectionPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(ConsoleConnectionFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'],
    };
}

export function ConsoleConnectionPageToJSON(json: any): ConsoleConnectionPage {
    return ConsoleConnectionPageToJSONTyped(json, false);
}

export function ConsoleConnectionPageToJSONTyped(value?: ConsoleConnectionPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(ConsoleConnectionToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

