/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConsoleSubscription
 */
export interface ConsoleSubscription {
    /**
     *
     * @type {string}
     * @memberof ConsoleSubscription
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleSubscription
     */
    licenseId: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleSubscription
     */
    stripeCustomerId: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleSubscription
     */
    email: string | null;
    /**
     *
     * @type {string}
     * @memberof ConsoleSubscription
     */
    plan: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleSubscription
     */
    status: string;
    /**
     *
     * @type {Date}
     * @memberof ConsoleSubscription
     */
    currentPeriodEnd: Date | null;
    /**
     *
     * @type {boolean}
     * @memberof ConsoleSubscription
     */
    cancelAtPeriodEnd: boolean;
    /**
     *
     * @type {Date}
     * @memberof ConsoleSubscription
     */
    dateAdded: Date | null;
    /**
     *
     * @type {Date}
     * @memberof ConsoleSubscription
     */
    dateModified: Date | null;
}

/**
 * Check if a given object implements the ConsoleSubscription interface.
 */
export function instanceOfConsoleSubscription(value: object): value is ConsoleSubscription {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('licenseId' in value) || value['licenseId'] === undefined) return false;
    if (!('stripeCustomerId' in value) || value['stripeCustomerId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('plan' in value) || value['plan'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('currentPeriodEnd' in value) || value['currentPeriodEnd'] === undefined) return false;
    if (!('cancelAtPeriodEnd' in value) || value['cancelAtPeriodEnd'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    if (!('dateModified' in value) || value['dateModified'] === undefined) return false;
    return true;
}

export function ConsoleSubscriptionFromJSON(json: any): ConsoleSubscription {
    return ConsoleSubscriptionFromJSONTyped(json, false);
}

export function ConsoleSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleSubscription {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'licenseId': json['license_id'],
        'stripeCustomerId': json['stripe_customer_id'],
        'email': json['email'],
        'plan': json['plan'],
        'status': json['status'],
        'currentPeriodEnd': (json['current_period_end'] == null ? null : new Date(json['current_period_end'])),
        'cancelAtPeriodEnd': json['cancel_at_period_end'],
        'dateAdded': (json['date_added'] == null ? null : new Date(json['date_added'])),
        'dateModified': (json['date_modified'] == null ? null : new Date(json['date_modified'])),
    };
}

export function ConsoleSubscriptionToJSON(json: any): ConsoleSubscription {
    return ConsoleSubscriptionToJSONTyped(json, false);
}

export function ConsoleSubscriptionToJSONTyped(value?: ConsoleSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'license_id': value['licenseId'],
        'stripe_customer_id': value['stripeCustomerId'],
        'email': value['email'],
        'plan': value['plan'],
        'status': value['status'],
        'current_period_end': value['currentPeriodEnd'] == null ? value['currentPeriodEnd'] : value['currentPeriodEnd'].toISOString(),
        'cancel_at_period_end': value['cancelAtPeriodEnd'],
        'date_added': value['dateAdded'] == null ? value['dateAdded'] : value['dateAdded'].toISOString(),
        'date_modified': value['dateModified'] == null ? value['dateModified'] : value['dateModified'].toISOString(),
    };
}

