/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConsoleUsageTotal
 */
export interface ConsoleUsageTotal {
    /**
     *
     * @type {string}
     * @memberof ConsoleUsageTotal
     */
    productId: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleUsageTotal
     */
    meterType: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleUsageTotal
     */
    quantity: string;
}

/**
 * Check if a given object implements the ConsoleUsageTotal interface.
 */
export function instanceOfConsoleUsageTotal(value: object): value is ConsoleUsageTotal {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('meterType' in value) || value['meterType'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function ConsoleUsageTotalFromJSON(json: any): ConsoleUsageTotal {
    return ConsoleUsageTotalFromJSONTyped(json, false);
}

export function ConsoleUsageTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleUsageTotal {
    if (json == null) {
        return json;
    }
    return {

        'productId': json['product_id'],
        'meterType': json['meter_type'],
        'quantity': json['quantity'],
    };
}

export function ConsoleUsageTotalToJSON(json: any): ConsoleUsageTotal {
    return ConsoleUsageTotalToJSONTyped(json, false);
}

export function ConsoleUsageTotalToJSONTyped(value?: ConsoleUsageTotal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'product_id': value['productId'],
        'meter_type': value['meterType'],
        'quantity': value['quantity'],
    };
}

