/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsoleSubscription } from './ConsoleSubscription';
import {
    ConsoleSubscriptionFromJSON,
    ConsoleSubscriptionFromJSONTyped,
    ConsoleSubscriptionToJSON,
    ConsoleSubscriptionToJSONTyped,
} from './ConsoleSubscription';

/**
 *
 * @export
 * @interface ConsoleSubscriptionPage
 */
export interface ConsoleSubscriptionPage {
    /**
     *
     * @type {Array<ConsoleSubscription>}
     * @memberof ConsoleSubscriptionPage
     */
    items: Array<ConsoleSubscription>;
    /**
     *
     * @type {number}
     * @memberof ConsoleSubscriptionPage
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof ConsoleSubscriptionPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the ConsoleSubscriptionPage interface.
 */
export function instanceOfConsoleSubscriptionPage(value: object): value is ConsoleSubscriptionPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function ConsoleSubscriptionPageFromJSON(json: any): ConsoleSubscriptionPage {
    return ConsoleSubscriptionPageFromJSONTyped(json, false);
}

export function ConsoleSubscriptionPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleSubscriptionPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(ConsoleSubscriptionFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'],
    };
}

export function ConsoleSubscriptionPageToJSON(json: any): ConsoleSubscriptionPage {
    return ConsoleSubscriptionPageToJSONTyped(json, false);
}

export function ConsoleSubscriptionPageToJSONTyped(value?: ConsoleSubscriptionPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(ConsoleSubscriptionToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

