/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConsoleSearchResult
 */
export interface ConsoleSearchResult {
    /**
     *
     * @type {string}
     * @memberof ConsoleSearchResult
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleSearchResult
     */
    label: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleSearchResult
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleSearchResult
     */
    href: string;
}

/**
 * Check if a given object implements the ConsoleSearchResult interface.
 */
export function instanceOfConsoleSearchResult(value: object): value is ConsoleSearchResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('href' in value) || value['href'] === undefined) return false;
    return true;
}

export function ConsoleSearchResultFromJSON(json: any): ConsoleSearchResult {
    return ConsoleSearchResultFromJSONTyped(json, false);
}

export function ConsoleSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleSearchResult {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'label': json['label'],
        'status': json['status'] == null ? undefined : json['status'],
        'href': json['href'],
    };
}

export function ConsoleSearchResultToJSON(json: any): ConsoleSearchResult {
    return ConsoleSearchResultToJSONTyped(json, false);
}

export function ConsoleSearchResultToJSONTyped(value?: ConsoleSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'label': value['label'],
        'status': value['status'],
        'href': value['href'],
    };
}

