/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConsoleBillingTotal
 */
export interface ConsoleBillingTotal {
    /**
     *
     * @type {string}
     * @memberof ConsoleBillingTotal
     */
    productId: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleBillingTotal
     */
    currency: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleBillingTotal
     */
    amount: string;
}

/**
 * Check if a given object implements the ConsoleBillingTotal interface.
 */
export function instanceOfConsoleBillingTotal(value: object): value is ConsoleBillingTotal {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function ConsoleBillingTotalFromJSON(json: any): ConsoleBillingTotal {
    return ConsoleBillingTotalFromJSONTyped(json, false);
}

export function ConsoleBillingTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleBillingTotal {
    if (json == null) {
        return json;
    }
    return {

        'productId': json['product_id'],
        'currency': json['currency'],
        'amount': json['amount'],
    };
}

export function ConsoleBillingTotalToJSON(json: any): ConsoleBillingTotal {
    return ConsoleBillingTotalToJSONTyped(json, false);
}

export function ConsoleBillingTotalToJSONTyped(value?: ConsoleBillingTotal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'product_id': value['productId'],
        'currency': value['currency'],
        'amount': value['amount'],
    };
}

