/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsoleStripeEvent } from './ConsoleStripeEvent';
import {
    ConsoleStripeEventFromJSON,
    ConsoleStripeEventFromJSONTyped,
    ConsoleStripeEventToJSON,
    ConsoleStripeEventToJSONTyped,
} from './ConsoleStripeEvent';

/**
 *
 * @export
 * @interface ConsoleStripeEventPage
 */
export interface ConsoleStripeEventPage {
    /**
     *
     * @type {Array<ConsoleStripeEvent>}
     * @memberof ConsoleStripeEventPage
     */
    items: Array<ConsoleStripeEvent>;
    /**
     *
     * @type {number}
     * @memberof ConsoleStripeEventPage
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof ConsoleStripeEventPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the ConsoleStripeEventPage interface.
 */
export function instanceOfConsoleStripeEventPage(value: object): value is ConsoleStripeEventPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function ConsoleStripeEventPageFromJSON(json: any): ConsoleStripeEventPage {
    return ConsoleStripeEventPageFromJSONTyped(json, false);
}

export function ConsoleStripeEventPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleStripeEventPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(ConsoleStripeEventFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'],
    };
}

export function ConsoleStripeEventPageToJSON(json: any): ConsoleStripeEventPage {
    return ConsoleStripeEventPageToJSONTyped(json, false);
}

export function ConsoleStripeEventPageToJSONTyped(value?: ConsoleStripeEventPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(ConsoleStripeEventToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

