/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsoleSearchResult } from './ConsoleSearchResult';
import {
    ConsoleSearchResultFromJSON,
    ConsoleSearchResultFromJSONTyped,
    ConsoleSearchResultToJSON,
    ConsoleSearchResultToJSONTyped,
} from './ConsoleSearchResult';

/**
 *
 * @export
 * @interface ConsoleSearchGroup
 */
export interface ConsoleSearchGroup {
    /**
     *
     * @type {string}
     * @memberof ConsoleSearchGroup
     */
    kind: string;
    /**
     *
     * @type {boolean}
     * @memberof ConsoleSearchGroup
     */
    available: boolean;
    /**
     *
     * @type {number}
     * @memberof ConsoleSearchGroup
     */
    total: number;
    /**
     *
     * @type {Array<ConsoleSearchResult>}
     * @memberof ConsoleSearchGroup
     */
    items: Array<ConsoleSearchResult>;
}

/**
 * Check if a given object implements the ConsoleSearchGroup interface.
 */
export function instanceOfConsoleSearchGroup(value: object): value is ConsoleSearchGroup {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ConsoleSearchGroupFromJSON(json: any): ConsoleSearchGroup {
    return ConsoleSearchGroupFromJSONTyped(json, false);
}

export function ConsoleSearchGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleSearchGroup {
    if (json == null) {
        return json;
    }
    return {

        'kind': json['kind'],
        'available': json['available'],
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(ConsoleSearchResultFromJSON)),
    };
}

export function ConsoleSearchGroupToJSON(json: any): ConsoleSearchGroup {
    return ConsoleSearchGroupToJSONTyped(json, false);
}

export function ConsoleSearchGroupToJSONTyped(value?: ConsoleSearchGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'kind': value['kind'],
        'available': value['available'],
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(ConsoleSearchResultToJSON)),
    };
}

