/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LicenseStatus } from './LicenseStatus';
import {
    LicenseStatusFromJSON,
    LicenseStatusFromJSONTyped,
    LicenseStatusToJSON,
    LicenseStatusToJSONTyped,
} from './LicenseStatus';

/**
 *
 * @export
 * @interface ConsoleLicense
 */
export interface ConsoleLicense {
    /**
     *
     * @type {string}
     * @memberof ConsoleLicense
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleLicense
     */
    keySuffix: string;
    /**
     *
     * @type {Date}
     * @memberof ConsoleLicense
     */
    dateAdded: Date;
    /**
     *
     * @type {Date}
     * @memberof ConsoleLicense
     */
    dateModified?: Date;
    /**
     *
     * @type {Date}
     * @memberof ConsoleLicense
     */
    dateExpires?: Date;
    /**
     *
     * @type {LicenseStatus}
     * @memberof ConsoleLicense
     */
    status: LicenseStatus;
    /**
     *
     * @type {string}
     * @memberof ConsoleLicense
     */
    holderName?: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleLicense
     */
    holderEmail?: string;
    /**
     *
     * @type {string}
     * @memberof ConsoleLicense
     */
    holderCompany?: string;
    /**
     *
     * @type {number}
     * @memberof ConsoleLicense
     */
    entitlementsTotal: number;
    /**
     *
     * @type {number}
     * @memberof ConsoleLicense
     */
    installsTotal: number;
    /**
     *
     * @type {number}
     * @memberof ConsoleLicense
     */
    transfersTotal: number;
}



/**
 * Check if a given object implements the ConsoleLicense interface.
 */
export function instanceOfConsoleLicense(value: object): value is ConsoleLicense {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('keySuffix' in value) || value['keySuffix'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('entitlementsTotal' in value) || value['entitlementsTotal'] === undefined) return false;
    if (!('installsTotal' in value) || value['installsTotal'] === undefined) return false;
    if (!('transfersTotal' in value) || value['transfersTotal'] === undefined) return false;
    return true;
}

export function ConsoleLicenseFromJSON(json: any): ConsoleLicense {
    return ConsoleLicenseFromJSONTyped(json, false);
}

export function ConsoleLicenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsoleLicense {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'keySuffix': json['key_suffix'],
        'dateAdded': (new Date(json['date_added'])),
        'dateModified': json['date_modified'] == null ? undefined : (new Date(json['date_modified'])),
        'dateExpires': json['date_expires'] == null ? undefined : (new Date(json['date_expires'])),
        'status': LicenseStatusFromJSON(json['status']),
        'holderName': json['holder_name'] == null ? undefined : json['holder_name'],
        'holderEmail': json['holder_email'] == null ? undefined : json['holder_email'],
        'holderCompany': json['holder_company'] == null ? undefined : json['holder_company'],
        'entitlementsTotal': json['entitlements_total'],
        'installsTotal': json['installs_total'],
        'transfersTotal': json['transfers_total'],
    };
}

export function ConsoleLicenseToJSON(json: any): ConsoleLicense {
    return ConsoleLicenseToJSONTyped(json, false);
}

export function ConsoleLicenseToJSONTyped(value?: ConsoleLicense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'key_suffix': value['keySuffix'],
        'date_added': value['dateAdded'].toISOString(),
        'date_modified': value['dateModified'] == null ? value['dateModified'] : value['dateModified'].toISOString(),
        'date_expires': value['dateExpires'] == null ? value['dateExpires'] : value['dateExpires'].toISOString(),
        'status': LicenseStatusToJSON(value['status']),
        'holder_name': value['holderName'],
        'holder_email': value['holderEmail'],
        'holder_company': value['holderCompany'],
        'entitlements_total': value['entitlementsTotal'],
        'installs_total': value['installsTotal'],
        'transfers_total': value['transfersTotal'],
    };
}

