/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateLinkTokenResponse
 */
export interface CreateLinkTokenResponse {
    /**
     *
     * @type {string}
     * @memberof CreateLinkTokenResponse
     */
    linkToken: string;
    /**
     *
     * @type {string}
     * @memberof CreateLinkTokenResponse
     */
    connectionId?: string;
    /**
     *
     * @type {Date}
     * @memberof CreateLinkTokenResponse
     */
    expiration: Date;
    /**
     *
     * @type {CreateLinkTokenResponseModeEnum}
     * @memberof CreateLinkTokenResponse
     */
    mode: CreateLinkTokenResponseModeEnum;
}


/**
 * @export
 */
export const CreateLinkTokenResponseModeEnum = {
    Create: 'create',
    Update: 'update'
} as const;
export type CreateLinkTokenResponseModeEnum = typeof CreateLinkTokenResponseModeEnum[keyof typeof CreateLinkTokenResponseModeEnum];


/**
 * Check if a given object implements the CreateLinkTokenResponse interface.
 */
export function instanceOfCreateLinkTokenResponse(value: object): value is CreateLinkTokenResponse {
    if (!('linkToken' in value) || value['linkToken'] === undefined) return false;
    if (!('expiration' in value) || value['expiration'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function CreateLinkTokenResponseFromJSON(json: any): CreateLinkTokenResponse {
    return CreateLinkTokenResponseFromJSONTyped(json, false);
}

export function CreateLinkTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLinkTokenResponse {
    if (json == null) {
        return json;
    }
    return {

        'linkToken': json['link_token'],
        'connectionId': json['connection_id'] == null ? undefined : json['connection_id'],
        'expiration': (new Date(json['expiration'])),
        'mode': json['mode'],
    };
}

export function CreateLinkTokenResponseToJSON(json: any): CreateLinkTokenResponse {
    return CreateLinkTokenResponseToJSONTyped(json, false);
}

export function CreateLinkTokenResponseToJSONTyped(value?: CreateLinkTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'link_token': value['linkToken'],
        'connection_id': value['connectionId'],
        'expiration': value['expiration'].toISOString(),
        'mode': value['mode'],
    };
}
