/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateWebhookDestinationRequest
 */
export interface CreateWebhookDestinationRequest {
    /**
     *
     * @type {string}
     * @memberof CreateWebhookDestinationRequest
     */
    url: string;
    /**
     *
     * @type {number}
     * @memberof CreateWebhookDestinationRequest
     */
    maxAttempts?: number;
}

/**
 * Check if a given object implements the CreateWebhookDestinationRequest interface.
 */
export function instanceOfCreateWebhookDestinationRequest(value: object): value is CreateWebhookDestinationRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreateWebhookDestinationRequestFromJSON(json: any): CreateWebhookDestinationRequest {
    return CreateWebhookDestinationRequestFromJSONTyped(json, false);
}

export function CreateWebhookDestinationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookDestinationRequest {
    if (json == null) {
        return json;
    }
    return {

        'url': json['url'],
        'maxAttempts': json['max_attempts'] == null ? undefined : json['max_attempts'],
    };
}

export function CreateWebhookDestinationRequestToJSON(json: any): CreateWebhookDestinationRequest {
    return CreateWebhookDestinationRequestToJSONTyped(json, false);
}

export function CreateWebhookDestinationRequestToJSONTyped(value?: CreateWebhookDestinationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'url': value['url'],
        'max_attempts': value['maxAttempts'],
    };
}

