/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Institution
 */
export interface Institution {
    /**
     * 
     * @type {string}
     * @memberof Institution
     */
    iD: string;
    /**
     * 
     * @type {string}
     * @memberof Institution
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Institution
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof Institution
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Institution
     */
    websiteUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Institution
     */
    websiteLoginUrl?: string | null;
}

/**
 * Check if a given object implements the Institution interface.
 */
export function instanceOfInstitution(value: object): value is Institution {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    return true;
}

export function InstitutionFromJSON(json: any): Institution {
    return InstitutionFromJSONTyped(json, false);
}

export function InstitutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Institution {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'name': json['name'],
        'countryCode': json['country_code'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'websiteUrl': json['website_url'] == null ? undefined : json['website_url'],
        'websiteLoginUrl': json['website_login_url'] == null ? undefined : json['website_login_url'],
    };
}

export function InstitutionToJSON(json: any): Institution {
    return InstitutionToJSONTyped(json, false);
}

export function InstitutionToJSONTyped(value?: Institution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
        'name': value['name'],
        'country_code': value['countryCode'],
        'logo_url': value['logoUrl'],
        'website_url': value['websiteUrl'],
        'website_login_url': value['websiteLoginUrl'],
    };
}

