/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LicenseStatus = {
    Active: 'active',
    Pending: 'pending',
    Revoked: 'revoked',
    Suspended: 'suspended',
    Expired: 'expired'
} as const;
export type LicenseStatus = typeof LicenseStatus[keyof typeof LicenseStatus];


export function instanceOfLicenseStatus(value: any): boolean {
    for (const key in LicenseStatus) {
        if (Object.prototype.hasOwnProperty.call(LicenseStatus, key)) {
            if (LicenseStatus[key as keyof typeof LicenseStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LicenseStatusFromJSON(json: any): LicenseStatus {
    return LicenseStatusFromJSONTyped(json, false);
}

export function LicenseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LicenseStatus {
    return json as LicenseStatus;
}

export function LicenseStatusToJSON(value?: LicenseStatus | null): any {
    return value as any;
}

export function LicenseStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): LicenseStatus {
    return value as LicenseStatus;
}

