/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkAccount
 */
export interface LinkAccount {
    /**
     * 
     * @type {string}
     * @memberof LinkAccount
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LinkAccount
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkAccount
     */
    mask?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkAccount
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkAccount
     */
    subtype?: string;
}

/**
 * Check if a given object implements the LinkAccount interface.
 */
export function instanceOfLinkAccount(value: object): value is LinkAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function LinkAccountFromJSON(json: any): LinkAccount {
    return LinkAccountFromJSONTyped(json, false);
}

export function LinkAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'mask': json['mask'] == null ? undefined : json['mask'],
        'type': json['type'] == null ? undefined : json['type'],
        'subtype': json['subtype'] == null ? undefined : json['subtype'],
    };
}

export function LinkAccountToJSON(json: any): LinkAccount {
    return LinkAccountToJSONTyped(json, false);
}

export function LinkAccountToJSONTyped(value?: LinkAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'mask': value['mask'],
        'type': value['type'],
        'subtype': value['subtype'],
    };
}

