/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ManagedBalanceSyncResponse
 */
export interface ManagedBalanceSyncResponse {
    /**
     *
     * @type {string}
     * @memberof ManagedBalanceSyncResponse
     */
    itemId: string;
    /**
     *
     * @type {number}
     * @memberof ManagedBalanceSyncResponse
     */
    updatedCount: number;
    /**
     *
     * @type {string}
     * @memberof ManagedBalanceSyncResponse
     */
    requestId: string;
}

/**
 * Check if a given object implements the ManagedBalanceSyncResponse interface.
 */
export function instanceOfManagedBalanceSyncResponse(value: object): value is ManagedBalanceSyncResponse {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('updatedCount' in value) || value['updatedCount'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function ManagedBalanceSyncResponseFromJSON(json: any): ManagedBalanceSyncResponse {
    return ManagedBalanceSyncResponseFromJSONTyped(json, false);
}

export function ManagedBalanceSyncResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedBalanceSyncResponse {
    if (json == null) {
        return json;
    }
    return {

        'itemId': json['item_id'],
        'updatedCount': json['updated_count'],
        'requestId': json['request_id'],
    };
}

export function ManagedBalanceSyncResponseToJSON(json: any): ManagedBalanceSyncResponse {
    return ManagedBalanceSyncResponseToJSONTyped(json, false);
}

export function ManagedBalanceSyncResponseToJSONTyped(value?: ManagedBalanceSyncResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'item_id': value['itemId'],
        'updated_count': value['updatedCount'],
        'request_id': value['requestId'],
    };
}
