/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ManagedAccountBalanceSyncResponse
 */
export interface ManagedAccountBalanceSyncResponse {
    /**
     *
     * @type {string}
     * @memberof ManagedAccountBalanceSyncResponse
     */
    itemId: string;
    /**
     *
     * @type {number}
     * @memberof ManagedAccountBalanceSyncResponse
     */
    updatedCount: number;
    /**
     *
     * @type {string}
     * @memberof ManagedAccountBalanceSyncResponse
     */
    requestId?: string;
}

/**
 * Check if a given object implements the ManagedAccountBalanceSyncResponse interface.
 */
export function instanceOfManagedAccountBalanceSyncResponse(value: object): value is ManagedAccountBalanceSyncResponse {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('updatedCount' in value) || value['updatedCount'] === undefined) return false;
    return true;
}

export function ManagedAccountBalanceSyncResponseFromJSON(json: any): ManagedAccountBalanceSyncResponse {
    return ManagedAccountBalanceSyncResponseFromJSONTyped(json, false);
}

export function ManagedAccountBalanceSyncResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedAccountBalanceSyncResponse {
    if (json == null) {
        return json;
    }
    return {

        'itemId': json['item_id'],
        'updatedCount': json['updated_count'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function ManagedAccountBalanceSyncResponseToJSON(json: any): ManagedAccountBalanceSyncResponse {
    return ManagedAccountBalanceSyncResponseToJSONTyped(json, false);
}

export function ManagedAccountBalanceSyncResponseToJSONTyped(value?: ManagedAccountBalanceSyncResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'item_id': value['itemId'],
        'updated_count': value['updatedCount'],
        'request_id': value['requestId'],
    };
}

