/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ManagedTransaction
 */
export interface ManagedTransaction {
    /**
     *
     * @type {string}
     * @memberof ManagedTransaction
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ManagedTransaction
     */
    itemId: string;
    /**
     *
     * @type {string}
     * @memberof ManagedTransaction
     */
    provider: string;
    /**
     *
     * @type {string}
     * @memberof ManagedTransaction
     */
    providerTransactionId: string;
    /**
     *
     * @type {string}
     * @memberof ManagedTransaction
     */
    providerAccountId: string;
    /**
     *
     * @type {Date}
     * @memberof ManagedTransaction
     */
    transactionDate: Date;
    /**
     *
     * @type {Date}
     * @memberof ManagedTransaction
     */
    authorizedDate?: Date | null;
    /**
     *
     * @type {string}
     * @memberof ManagedTransaction
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ManagedTransaction
     */
    merchantName?: string | null;
    /**
     *
     * @type {number}
     * @memberof ManagedTransaction
     */
    amount: number;
    /**
     *
     * @type {string}
     * @memberof ManagedTransaction
     */
    isoCurrencyCode?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof ManagedTransaction
     */
    pending: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ManagedTransaction
     */
    removed: boolean;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof ManagedTransaction
     */
    raw: { [key: string]: any; };
    /**
     *
     * @type {Date}
     * @memberof ManagedTransaction
     */
    dateAdded: Date;
    /**
     *
     * @type {Date}
     * @memberof ManagedTransaction
     */
    dateModified?: Date | null;
}

/**
 * Check if a given object implements the ManagedTransaction interface.
 */
export function instanceOfManagedTransaction(value: object): value is ManagedTransaction {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('providerTransactionId' in value) || value['providerTransactionId'] === undefined) return false;
    if (!('providerAccountId' in value) || value['providerAccountId'] === undefined) return false;
    if (!('transactionDate' in value) || value['transactionDate'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('removed' in value) || value['removed'] === undefined) return false;
    if (!('raw' in value) || value['raw'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    return true;
}

export function ManagedTransactionFromJSON(json: any): ManagedTransaction {
    return ManagedTransactionFromJSONTyped(json, false);
}

export function ManagedTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedTransaction {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'itemId': json['item_id'],
        'provider': json['provider'],
        'providerTransactionId': json['provider_transaction_id'],
        'providerAccountId': json['provider_account_id'],
        'transactionDate': (new Date(json['transaction_date'])),
        'authorizedDate': json['authorized_date'] == null ? undefined : (new Date(json['authorized_date'])),
        'name': json['name'],
        'merchantName': json['merchant_name'] == null ? undefined : json['merchant_name'],
        'amount': json['amount'],
        'isoCurrencyCode': json['iso_currency_code'] == null ? undefined : json['iso_currency_code'],
        'pending': json['pending'],
        'removed': json['removed'],
        'raw': json['raw'],
        'dateAdded': (new Date(json['date_added'])),
        'dateModified': json['date_modified'] == null ? undefined : (new Date(json['date_modified'])),
    };
}

export function ManagedTransactionToJSON(json: any): ManagedTransaction {
    return ManagedTransactionToJSONTyped(json, false);
}

export function ManagedTransactionToJSONTyped(value?: ManagedTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'item_id': value['itemId'],
        'provider': value['provider'],
        'provider_transaction_id': value['providerTransactionId'],
        'provider_account_id': value['providerAccountId'],
        'transaction_date': value['transactionDate'].toISOString().substring(0,10),
        'authorized_date': value['authorizedDate'] == null ? value['authorizedDate'] : value['authorizedDate'].toISOString().substring(0,10),
        'name': value['name'],
        'merchant_name': value['merchantName'],
        'amount': value['amount'],
        'iso_currency_code': value['isoCurrencyCode'],
        'pending': value['pending'],
        'removed': value['removed'],
        'raw': value['raw'],
        'date_added': value['dateAdded'].toISOString(),
        'date_modified': value['dateModified'] == null ? value['dateModified'] : value['dateModified'].toISOString(),
    };
}

