/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ManagedConnectionStatusResponse
 */
export interface ManagedConnectionStatusResponse {
    /**
     *
     * @type {string}
     * @memberof ManagedConnectionStatusResponse
     */
    connectionId: string;
    /**
     *
     * @type {ManagedConnectionStatusResponseStatusEnum}
     * @memberof ManagedConnectionStatusResponse
     */
    status: ManagedConnectionStatusResponseStatusEnum;
}


/**
 * @export
 */
export const ManagedConnectionStatusResponseStatusEnum = {
    Active: 'active',
    Error: 'error',
    ReauthRequired: 'reauth_required',
    LimitReached: 'limit_reached',
    Revoked: 'revoked'
} as const;
export type ManagedConnectionStatusResponseStatusEnum = typeof ManagedConnectionStatusResponseStatusEnum[keyof typeof ManagedConnectionStatusResponseStatusEnum];


/**
 * Check if a given object implements the ManagedConnectionStatusResponse interface.
 */
export function instanceOfManagedConnectionStatusResponse(value: object): value is ManagedConnectionStatusResponse {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ManagedConnectionStatusResponseFromJSON(json: any): ManagedConnectionStatusResponse {
    return ManagedConnectionStatusResponseFromJSONTyped(json, false);
}

export function ManagedConnectionStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedConnectionStatusResponse {
    if (json == null) {
        return json;
    }
    return {

        'connectionId': json['connection_id'],
        'status': json['status'],
    };
}

export function ManagedConnectionStatusResponseToJSON(json: any): ManagedConnectionStatusResponse {
    return ManagedConnectionStatusResponseToJSONTyped(json, false);
}

export function ManagedConnectionStatusResponseToJSONTyped(value?: ManagedConnectionStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'connection_id': value['connectionId'],
        'status': value['status'],
    };
}
