/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewsletterDeliveryMetadata } from './NewsletterDeliveryMetadata';
import {
    NewsletterDeliveryMetadataFromJSON,
    NewsletterDeliveryMetadataFromJSONTyped,
    NewsletterDeliveryMetadataToJSON,
    NewsletterDeliveryMetadataToJSONTyped,
} from './NewsletterDeliveryMetadata';

/**
 *
 * @export
 * @interface NewsletterDeliveryMetadataPage
 */
export interface NewsletterDeliveryMetadataPage {
    /**
     *
     * @type {Array<NewsletterDeliveryMetadata>}
     * @memberof NewsletterDeliveryMetadataPage
     */
    items: Array<NewsletterDeliveryMetadata>;
    /**
     *
     * @type {number}
     * @memberof NewsletterDeliveryMetadataPage
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof NewsletterDeliveryMetadataPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the NewsletterDeliveryMetadataPage interface.
 */
export function instanceOfNewsletterDeliveryMetadataPage(value: object): value is NewsletterDeliveryMetadataPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function NewsletterDeliveryMetadataPageFromJSON(json: any): NewsletterDeliveryMetadataPage {
    return NewsletterDeliveryMetadataPageFromJSONTyped(json, false);
}

export function NewsletterDeliveryMetadataPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsletterDeliveryMetadataPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(NewsletterDeliveryMetadataFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'],
    };
}

export function NewsletterDeliveryMetadataPageToJSON(json: any): NewsletterDeliveryMetadataPage {
    return NewsletterDeliveryMetadataPageToJSONTyped(json, false);
}

export function NewsletterDeliveryMetadataPageToJSONTyped(value?: NewsletterDeliveryMetadataPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(NewsletterDeliveryMetadataToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

