/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NewsletterSendRequest
 */
export interface NewsletterSendRequest {
    /**
     *
     * @type {string}
     * @memberof NewsletterSendRequest
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof NewsletterSendRequest
     */
    content: string;
    /**
     *
     * @type {string}
     * @memberof NewsletterSendRequest
     */
    mailingListId: string;
}

/**
 * Check if a given object implements the NewsletterSendRequest interface.
 */
export function instanceOfNewsletterSendRequest(value: object): value is NewsletterSendRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('mailingListId' in value) || value['mailingListId'] === undefined) return false;
    return true;
}

export function NewsletterSendRequestFromJSON(json: any): NewsletterSendRequest {
    return NewsletterSendRequestFromJSONTyped(json, false);
}

export function NewsletterSendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsletterSendRequest {
    if (json == null) {
        return json;
    }
    return {

        'title': json['title'],
        'content': json['content'],
        'mailingListId': json['mailing_list_id'],
    };
}

export function NewsletterSendRequestToJSON(json: any): NewsletterSendRequest {
    return NewsletterSendRequestToJSONTyped(json, false);
}

export function NewsletterSendRequestToJSONTyped(value?: NewsletterSendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'title': value['title'],
        'content': value['content'],
        'mailing_list_id': value['mailingListId'],
    };
}

