/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewsletterStatus } from './NewsletterStatus';
import {
    NewsletterStatusFromJSON,
    NewsletterStatusFromJSONTyped,
    NewsletterStatusToJSON,
    NewsletterStatusToJSONTyped,
} from './NewsletterStatus';

/**
 *
 * @export
 * @interface NewsletterSummary
 */
export interface NewsletterSummary {
    /**
     *
     * @type {string}
     * @memberof NewsletterSummary
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof NewsletterSummary
     */
    mailingListId: string;
    /**
     *
     * @type {string}
     * @memberof NewsletterSummary
     */
    mailingList: string;
    /**
     *
     * @type {Date}
     * @memberof NewsletterSummary
     */
    dateAdded: Date;
    /**
     *
     * @type {Date}
     * @memberof NewsletterSummary
     */
    datePublished: Date;
    /**
     *
     * @type {Date}
     * @memberof NewsletterSummary
     */
    dateCompleted?: Date | null;
    /**
     *
     * @type {NewsletterStatus}
     * @memberof NewsletterSummary
     */
    status: NewsletterStatus;
    /**
     *
     * @type {string}
     * @memberof NewsletterSummary
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof NewsletterSummary
     */
    content: string;
    /**
     *
     * @type {number}
     * @memberof NewsletterSummary
     */
    recipientCount: number;
    /**
     *
     * @type {number}
     * @memberof NewsletterSummary
     */
    sentCount: number;
    /**
     *
     * @type {number}
     * @memberof NewsletterSummary
     */
    failedCount: number;
    /**
     *
     * @type {number}
     * @memberof NewsletterSummary
     */
    pendingCount: number;
}



/**
 * Check if a given object implements the NewsletterSummary interface.
 */
export function instanceOfNewsletterSummary(value: object): value is NewsletterSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mailingListId' in value) || value['mailingListId'] === undefined) return false;
    if (!('mailingList' in value) || value['mailingList'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    if (!('datePublished' in value) || value['datePublished'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('recipientCount' in value) || value['recipientCount'] === undefined) return false;
    if (!('sentCount' in value) || value['sentCount'] === undefined) return false;
    if (!('failedCount' in value) || value['failedCount'] === undefined) return false;
    if (!('pendingCount' in value) || value['pendingCount'] === undefined) return false;
    return true;
}

export function NewsletterSummaryFromJSON(json: any): NewsletterSummary {
    return NewsletterSummaryFromJSONTyped(json, false);
}

export function NewsletterSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsletterSummary {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'mailingListId': json['mailing_list_id'],
        'mailingList': json['mailing_list'],
        'dateAdded': (new Date(json['date_added'])),
        'datePublished': (new Date(json['date_published'])),
        'dateCompleted': json['date_completed'] == null ? undefined : (new Date(json['date_completed'])),
        'status': NewsletterStatusFromJSON(json['status']),
        'title': json['title'],
        'content': json['content'],
        'recipientCount': json['recipient_count'],
        'sentCount': json['sent_count'],
        'failedCount': json['failed_count'],
        'pendingCount': json['pending_count'],
    };
}

export function NewsletterSummaryToJSON(json: any): NewsletterSummary {
    return NewsletterSummaryToJSONTyped(json, false);
}

export function NewsletterSummaryToJSONTyped(value?: NewsletterSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'mailing_list_id': value['mailingListId'],
        'mailing_list': value['mailingList'],
        'date_added': value['dateAdded'].toISOString(),
        'date_published': value['datePublished'].toISOString(),
        'date_completed': value['dateCompleted'] == null ? value['dateCompleted'] : value['dateCompleted'].toISOString(),
        'status': NewsletterStatusToJSON(value['status']),
        'title': value['title'],
        'content': value['content'],
        'recipient_count': value['recipientCount'],
        'sent_count': value['sentCount'],
        'failed_count': value['failedCount'],
        'pending_count': value['pendingCount'],
    };
}

