/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PatchWebhookEndpointRequest
 */
export interface PatchWebhookEndpointRequest {
    /**
     *
     * @type {string}
     * @memberof PatchWebhookEndpointRequest
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof PatchWebhookEndpointRequest
     */
    secret?: string;
    /**
     *
     * @type {boolean}
     * @memberof PatchWebhookEndpointRequest
     */
    allowUnsigned?: boolean;
    /**
     *
     * @type {PatchWebhookEndpointRequestStatusEnum}
     * @memberof PatchWebhookEndpointRequest
     */
    status?: PatchWebhookEndpointRequestStatusEnum;
}


/**
 * @export
 */
export const PatchWebhookEndpointRequestStatusEnum = {
    Active: 'active',
    Disabled: 'disabled'
} as const;
export type PatchWebhookEndpointRequestStatusEnum = typeof PatchWebhookEndpointRequestStatusEnum[keyof typeof PatchWebhookEndpointRequestStatusEnum];


/**
 * Check if a given object implements the PatchWebhookEndpointRequest interface.
 */
export function instanceOfPatchWebhookEndpointRequest(value: object): value is PatchWebhookEndpointRequest {
    return true;
}

export function PatchWebhookEndpointRequestFromJSON(json: any): PatchWebhookEndpointRequest {
    return PatchWebhookEndpointRequestFromJSONTyped(json, false);
}

export function PatchWebhookEndpointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchWebhookEndpointRequest {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'] == null ? undefined : json['name'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'allowUnsigned': json['allow_unsigned'] == null ? undefined : json['allow_unsigned'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PatchWebhookEndpointRequestToJSON(json: any): PatchWebhookEndpointRequest {
    return PatchWebhookEndpointRequestToJSONTyped(json, false);
}

export function PatchWebhookEndpointRequestToJSONTyped(value?: PatchWebhookEndpointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
        'secret': value['secret'],
        'allow_unsigned': value['allowUnsigned'],
        'status': value['status'],
    };
}

