/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PlaidWebhookRequest
 */
export interface PlaidWebhookRequest {
    [key: string]: any | any;
    /**
     *
     * @type {string}
     * @memberof PlaidWebhookRequest
     */
    webhookType: string;
    /**
     *
     * @type {string}
     * @memberof PlaidWebhookRequest
     */
    webhookCode: string;
    /**
     *
     * @type {string}
     * @memberof PlaidWebhookRequest
     */
    itemId?: string;
}

/**
 * Check if a given object implements the PlaidWebhookRequest interface.
 */
export function instanceOfPlaidWebhookRequest(value: object): value is PlaidWebhookRequest {
    if (!('webhookType' in value) || value['webhookType'] === undefined) return false;
    if (!('webhookCode' in value) || value['webhookCode'] === undefined) return false;
    return true;
}

export function PlaidWebhookRequestFromJSON(json: any): PlaidWebhookRequest {
    return PlaidWebhookRequestFromJSONTyped(json, false);
}

export function PlaidWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidWebhookRequest {
    if (json == null) {
        return json;
    }
    return {

            ...json,
        'webhookType': json['webhook_type'],
        'webhookCode': json['webhook_code'],
        'itemId': json['item_id'] == null ? undefined : json['item_id'],
    };
}

export function PlaidWebhookRequestToJSON(json: any): PlaidWebhookRequest {
    return PlaidWebhookRequestToJSONTyped(json, false);
}

export function PlaidWebhookRequestToJSONTyped(value?: PlaidWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

            ...value,
        'webhook_type': value['webhookType'],
        'webhook_code': value['webhookCode'],
        'item_id': value['itemId'],
    };
}
