/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuntimeCommandStatus } from './RuntimeCommandStatus';
import {
    RuntimeCommandStatusFromJSON,
    RuntimeCommandStatusFromJSONTyped,
    RuntimeCommandStatusToJSON,
    RuntimeCommandStatusToJSONTyped,
} from './RuntimeCommandStatus';
import type { RuntimeCommandType } from './RuntimeCommandType';
import {
    RuntimeCommandTypeFromJSON,
    RuntimeCommandTypeFromJSONTyped,
    RuntimeCommandTypeToJSON,
    RuntimeCommandTypeToJSONTyped,
} from './RuntimeCommandType';
import type { RuntimeCommandTargetScope } from './RuntimeCommandTargetScope';
import {
    RuntimeCommandTargetScopeFromJSON,
    RuntimeCommandTargetScopeFromJSONTyped,
    RuntimeCommandTargetScopeToJSON,
    RuntimeCommandTargetScopeToJSONTyped,
} from './RuntimeCommandTargetScope';
import type { ProductID } from './ProductID';
import {
    ProductIDFromJSON,
    ProductIDFromJSONTyped,
    ProductIDToJSON,
    ProductIDToJSONTyped,
} from './ProductID';

/**
 *
 * @export
 * @interface RuntimeCommandSummary
 */
export interface RuntimeCommandSummary {
    /**
     *
     * @type {string}
     * @memberof RuntimeCommandSummary
     */
    id: string;
    /**
     *
     * @type {RuntimeCommandType}
     * @memberof RuntimeCommandSummary
     */
    commandType: RuntimeCommandType;
    /**
     *
     * @type {RuntimeCommandTargetScope}
     * @memberof RuntimeCommandSummary
     */
    targetScope: RuntimeCommandTargetScope;
    /**
     *
     * @type {ProductID}
     * @memberof RuntimeCommandSummary
     */
    productId: ProductID;
    /**
     *
     * @type {string}
     * @memberof RuntimeCommandSummary
     */
    licenseId?: string | null;
    /**
     *
     * @type {string}
     * @memberof RuntimeCommandSummary
     */
    installId?: string | null;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof RuntimeCommandSummary
     */
    payload: { [key: string]: any; };
    /**
     *
     * @type {RuntimeCommandStatus}
     * @memberof RuntimeCommandSummary
     */
    status: RuntimeCommandStatus;
    /**
     *
     * @type {Date}
     * @memberof RuntimeCommandSummary
     */
    issuedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof RuntimeCommandSummary
     */
    expiresAt: Date;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandSummary
     */
    retryIntervalSeconds: number;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandSummary
     */
    maxAttempts: number;
    /**
     *
     * @type {Date}
     * @memberof RuntimeCommandSummary
     */
    dateAdded: Date;
    /**
     *
     * @type {Date}
     * @memberof RuntimeCommandSummary
     */
    dateModified: Date;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandSummary
     */
    totalTargets: number;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandSummary
     */
    ackedCount: number;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandSummary
     */
    sentCount: number;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandSummary
     */
    queuedCount: number;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandSummary
     */
    failedCount: number;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandSummary
     */
    expiredCount: number;
}



/**
 * Check if a given object implements the RuntimeCommandSummary interface.
 */
export function instanceOfRuntimeCommandSummary(value: object): value is RuntimeCommandSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('commandType' in value) || value['commandType'] === undefined) return false;
    if (!('targetScope' in value) || value['targetScope'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('issuedAt' in value) || value['issuedAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('retryIntervalSeconds' in value) || value['retryIntervalSeconds'] === undefined) return false;
    if (!('maxAttempts' in value) || value['maxAttempts'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    if (!('dateModified' in value) || value['dateModified'] === undefined) return false;
    if (!('totalTargets' in value) || value['totalTargets'] === undefined) return false;
    if (!('ackedCount' in value) || value['ackedCount'] === undefined) return false;
    if (!('sentCount' in value) || value['sentCount'] === undefined) return false;
    if (!('queuedCount' in value) || value['queuedCount'] === undefined) return false;
    if (!('failedCount' in value) || value['failedCount'] === undefined) return false;
    if (!('expiredCount' in value) || value['expiredCount'] === undefined) return false;
    return true;
}

export function RuntimeCommandSummaryFromJSON(json: any): RuntimeCommandSummary {
    return RuntimeCommandSummaryFromJSONTyped(json, false);
}

export function RuntimeCommandSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeCommandSummary {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'commandType': RuntimeCommandTypeFromJSON(json['command_type']),
        'targetScope': RuntimeCommandTargetScopeFromJSON(json['target_scope']),
        'productId': ProductIDFromJSON(json['product_id']),
        'licenseId': json['license_id'] == null ? undefined : json['license_id'],
        'installId': json['install_id'] == null ? undefined : json['install_id'],
        'payload': json['payload'],
        'status': RuntimeCommandStatusFromJSON(json['status']),
        'issuedAt': (new Date(json['issued_at'])),
        'expiresAt': (new Date(json['expires_at'])),
        'retryIntervalSeconds': json['retry_interval_seconds'],
        'maxAttempts': json['max_attempts'],
        'dateAdded': (new Date(json['date_added'])),
        'dateModified': (new Date(json['date_modified'])),
        'totalTargets': json['total_targets'],
        'ackedCount': json['acked_count'],
        'sentCount': json['sent_count'],
        'queuedCount': json['queued_count'],
        'failedCount': json['failed_count'],
        'expiredCount': json['expired_count'],
    };
}

export function RuntimeCommandSummaryToJSON(json: any): RuntimeCommandSummary {
    return RuntimeCommandSummaryToJSONTyped(json, false);
}

export function RuntimeCommandSummaryToJSONTyped(value?: RuntimeCommandSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'command_type': RuntimeCommandTypeToJSON(value['commandType']),
        'target_scope': RuntimeCommandTargetScopeToJSON(value['targetScope']),
        'product_id': ProductIDToJSON(value['productId']),
        'license_id': value['licenseId'],
        'install_id': value['installId'],
        'payload': value['payload'],
        'status': RuntimeCommandStatusToJSON(value['status']),
        'issued_at': value['issuedAt'].toISOString(),
        'expires_at': value['expiresAt'].toISOString(),
        'retry_interval_seconds': value['retryIntervalSeconds'],
        'max_attempts': value['maxAttempts'],
        'date_added': value['dateAdded'].toISOString(),
        'date_modified': value['dateModified'].toISOString(),
        'total_targets': value['totalTargets'],
        'acked_count': value['ackedCount'],
        'sent_count': value['sentCount'],
        'queued_count': value['queuedCount'],
        'failed_count': value['failedCount'],
        'expired_count': value['expiredCount'],
    };
}

