/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RuntimeEntitlementSnapshotResponseCaps
 */
export interface RuntimeEntitlementSnapshotResponseCaps {
    /**
     *
     * @type {number}
     * @memberof RuntimeEntitlementSnapshotResponseCaps
     */
    transactionsConnectedAccounts?: number;
    /**
     *
     * @type {number}
     * @memberof RuntimeEntitlementSnapshotResponseCaps
     */
    recurringConnectedAccounts?: number;
    /**
     *
     * @type {number}
     * @memberof RuntimeEntitlementSnapshotResponseCaps
     */
    transactionsRefreshCalls?: number;
}

/**
 * Check if a given object implements the RuntimeEntitlementSnapshotResponseCaps interface.
 */
export function instanceOfRuntimeEntitlementSnapshotResponseCaps(value: object): value is RuntimeEntitlementSnapshotResponseCaps {
    return true;
}

export function RuntimeEntitlementSnapshotResponseCapsFromJSON(json: any): RuntimeEntitlementSnapshotResponseCaps {
    return RuntimeEntitlementSnapshotResponseCapsFromJSONTyped(json, false);
}

export function RuntimeEntitlementSnapshotResponseCapsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeEntitlementSnapshotResponseCaps {
    if (json == null) {
        return json;
    }
    return {

        'transactionsConnectedAccounts': json['transactions_connected_accounts'] == null ? undefined : json['transactions_connected_accounts'],
        'recurringConnectedAccounts': json['recurring_connected_accounts'] == null ? undefined : json['recurring_connected_accounts'],
        'transactionsRefreshCalls': json['transactions_refresh_calls'] == null ? undefined : json['transactions_refresh_calls'],
    };
}

export function RuntimeEntitlementSnapshotResponseCapsToJSON(json: any): RuntimeEntitlementSnapshotResponseCaps {
    return RuntimeEntitlementSnapshotResponseCapsToJSONTyped(json, false);
}

export function RuntimeEntitlementSnapshotResponseCapsToJSONTyped(value?: RuntimeEntitlementSnapshotResponseCaps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'transactions_connected_accounts': value['transactionsConnectedAccounts'],
        'recurring_connected_accounts': value['recurringConnectedAccounts'],
        'transactions_refresh_calls': value['transactionsRefreshCalls'],
    };
}

