/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuntimeUsageBatchResponse
 */
export interface RuntimeUsageBatchResponse {
    /**
     * 
     * @type {number}
     * @memberof RuntimeUsageBatchResponse
     */
    accepted: number;
    /**
     * 
     * @type {number}
     * @memberof RuntimeUsageBatchResponse
     */
    ignored: number;
}

/**
 * Check if a given object implements the RuntimeUsageBatchResponse interface.
 */
export function instanceOfRuntimeUsageBatchResponse(value: object): value is RuntimeUsageBatchResponse {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    if (!('ignored' in value) || value['ignored'] === undefined) return false;
    return true;
}

export function RuntimeUsageBatchResponseFromJSON(json: any): RuntimeUsageBatchResponse {
    return RuntimeUsageBatchResponseFromJSONTyped(json, false);
}

export function RuntimeUsageBatchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeUsageBatchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
        'ignored': json['ignored'],
    };
}

export function RuntimeUsageBatchResponseToJSON(json: any): RuntimeUsageBatchResponse {
    return RuntimeUsageBatchResponseToJSONTyped(json, false);
}

export function RuntimeUsageBatchResponseToJSONTyped(value?: RuntimeUsageBatchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
        'ignored': value['ignored'],
    };
}

