/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuntimeActivateResponse
 */
export interface RuntimeActivateResponse {
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateResponse
     */
    licenseId: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateResponse
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateResponse
     */
    installId: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateResponse
     */
    leaseToken: string;
    /**
     * 
     * @type {Date}
     * @memberof RuntimeActivateResponse
     */
    leaseExpiresAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof RuntimeActivateResponse
     */
    scopes: Array<string>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof RuntimeActivateResponse
     */
    caps: { [key: string]: number; };
    /**
     * 
     * @type {boolean}
     * @memberof RuntimeActivateResponse
     */
    transferred: boolean;
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateResponse
     */
    warning?: string;
}

/**
 * Check if a given object implements the RuntimeActivateResponse interface.
 */
export function instanceOfRuntimeActivateResponse(value: object): value is RuntimeActivateResponse {
    if (!('licenseId' in value) || value['licenseId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('installId' in value) || value['installId'] === undefined) return false;
    if (!('leaseToken' in value) || value['leaseToken'] === undefined) return false;
    if (!('leaseExpiresAt' in value) || value['leaseExpiresAt'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    if (!('caps' in value) || value['caps'] === undefined) return false;
    if (!('transferred' in value) || value['transferred'] === undefined) return false;
    return true;
}

export function RuntimeActivateResponseFromJSON(json: any): RuntimeActivateResponse {
    return RuntimeActivateResponseFromJSONTyped(json, false);
}

export function RuntimeActivateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeActivateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'licenseId': json['license_id'],
        'productId': json['product_id'],
        'installId': json['install_id'],
        'leaseToken': json['lease_token'],
        'leaseExpiresAt': (new Date(json['lease_expires_at'])),
        'scopes': json['scopes'],
        'caps': json['caps'],
        'transferred': json['transferred'],
        'warning': json['warning'] == null ? undefined : json['warning'],
    };
}

export function RuntimeActivateResponseToJSON(json: any): RuntimeActivateResponse {
    return RuntimeActivateResponseToJSONTyped(json, false);
}

export function RuntimeActivateResponseToJSONTyped(value?: RuntimeActivateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'license_id': value['licenseId'],
        'product_id': value['productId'],
        'install_id': value['installId'],
        'lease_token': value['leaseToken'],
        'lease_expires_at': value['leaseExpiresAt'].toISOString(),
        'scopes': value['scopes'],
        'caps': value['caps'],
        'transferred': value['transferred'],
        'warning': value['warning'],
    };
}

