/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RuntimeActivationDaily
 */
export interface RuntimeActivationDaily {
    /**
     *
     * @type {Date}
     * @memberof RuntimeActivationDaily
     */
    eventDate: Date;
    /**
     *
     * @type {number}
     * @memberof RuntimeActivationDaily
     */
    activations: number;
}

/**
 * Check if a given object implements the RuntimeActivationDaily interface.
 */
export function instanceOfRuntimeActivationDaily(value: object): value is RuntimeActivationDaily {
    if (!('eventDate' in value) || value['eventDate'] === undefined) return false;
    if (!('activations' in value) || value['activations'] === undefined) return false;
    return true;
}

export function RuntimeActivationDailyFromJSON(json: any): RuntimeActivationDaily {
    return RuntimeActivationDailyFromJSONTyped(json, false);
}

export function RuntimeActivationDailyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeActivationDaily {
    if (json == null) {
        return json;
    }
    return {

        'eventDate': (new Date(json['event_date'])),
        'activations': json['activations'],
    };
}

export function RuntimeActivationDailyToJSON(json: any): RuntimeActivationDaily {
    return RuntimeActivationDailyToJSONTyped(json, false);
}

export function RuntimeActivationDailyToJSONTyped(value?: RuntimeActivationDaily | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'event_date': value['eventDate'].toISOString().substring(0,10),
        'activations': value['activations'],
    };
}

