/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const RuntimeCommandTargetScope = {
    Install: 'install',
    LicenseProduct: 'license_product',
    Product: 'product'
} as const;
export type RuntimeCommandTargetScope = typeof RuntimeCommandTargetScope[keyof typeof RuntimeCommandTargetScope];


export function instanceOfRuntimeCommandTargetScope(value: any): boolean {
    for (const key in RuntimeCommandTargetScope) {
        if (Object.prototype.hasOwnProperty.call(RuntimeCommandTargetScope, key)) {
            if (RuntimeCommandTargetScope[key as keyof typeof RuntimeCommandTargetScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RuntimeCommandTargetScopeFromJSON(json: any): RuntimeCommandTargetScope {
    return RuntimeCommandTargetScopeFromJSONTyped(json, false);
}

export function RuntimeCommandTargetScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeCommandTargetScope {
    return json as RuntimeCommandTargetScope;
}

export function RuntimeCommandTargetScopeToJSON(value?: RuntimeCommandTargetScope | null): any {
    return value as any;
}

export function RuntimeCommandTargetScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): RuntimeCommandTargetScope {
    return value as RuntimeCommandTargetScope;
}

