/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuntimeActivationDaily } from './RuntimeActivationDaily';
import {
    RuntimeActivationDailyFromJSON,
    RuntimeActivationDailyFromJSONTyped,
    RuntimeActivationDailyToJSON,
    RuntimeActivationDailyToJSONTyped,
} from './RuntimeActivationDaily';

/**
 *
 * @export
 * @interface RuntimeActivationHistoryListResponse
 */
export interface RuntimeActivationHistoryListResponse {
    /**
     *
     * @type {Array<RuntimeActivationDaily>}
     * @memberof RuntimeActivationHistoryListResponse
     */
    items: Array<RuntimeActivationDaily>;
    /**
     *
     * @type {number}
     * @memberof RuntimeActivationHistoryListResponse
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof RuntimeActivationHistoryListResponse
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the RuntimeActivationHistoryListResponse interface.
 */
export function instanceOfRuntimeActivationHistoryListResponse(value: object): value is RuntimeActivationHistoryListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function RuntimeActivationHistoryListResponseFromJSON(json: any): RuntimeActivationHistoryListResponse {
    return RuntimeActivationHistoryListResponseFromJSONTyped(json, false);
}

export function RuntimeActivationHistoryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeActivationHistoryListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(RuntimeActivationDailyFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function RuntimeActivationHistoryListResponseToJSON(json: any): RuntimeActivationHistoryListResponse {
    return RuntimeActivationHistoryListResponseToJSONTyped(json, false);
}

export function RuntimeActivationHistoryListResponseToJSONTyped(value?: RuntimeActivationHistoryListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(RuntimeActivationDailyToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

