/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuntimeCommandSummary } from './RuntimeCommandSummary';
import {
    RuntimeCommandSummaryFromJSON,
    RuntimeCommandSummaryFromJSONTyped,
    RuntimeCommandSummaryToJSON,
    RuntimeCommandSummaryToJSONTyped,
} from './RuntimeCommandSummary';

/**
 *
 * @export
 * @interface RuntimeCommandListResponse
 */
export interface RuntimeCommandListResponse {
    /**
     *
     * @type {Array<RuntimeCommandSummary>}
     * @memberof RuntimeCommandListResponse
     */
    items: Array<RuntimeCommandSummary>;
    /**
     *
     * @type {number}
     * @memberof RuntimeCommandListResponse
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof RuntimeCommandListResponse
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the RuntimeCommandListResponse interface.
 */
export function instanceOfRuntimeCommandListResponse(value: object): value is RuntimeCommandListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function RuntimeCommandListResponseFromJSON(json: any): RuntimeCommandListResponse {
    return RuntimeCommandListResponseFromJSONTyped(json, false);
}

export function RuntimeCommandListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeCommandListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(RuntimeCommandSummaryFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function RuntimeCommandListResponseToJSON(json: any): RuntimeCommandListResponse {
    return RuntimeCommandListResponseToJSONTyped(json, false);
}

export function RuntimeCommandListResponseToJSONTyped(value?: RuntimeCommandListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(RuntimeCommandSummaryToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

