/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuntimeActivateRequest
 */
export interface RuntimeActivateRequest {
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateRequest
     */
    licenseKey: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateRequest
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateRequest
     */
    installId: string;
    /**
     * Base64-encoded Ed25519 public key
     * @type {string}
     * @memberof RuntimeActivateRequest
     */
    installPublicKey: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeActivateRequest
     */
    challenge: string;
    /**
     * Base64-encoded signature of challenge
     * @type {string}
     * @memberof RuntimeActivateRequest
     */
    challengeSignature: string;
    /**
     * 
     * @type {boolean}
     * @memberof RuntimeActivateRequest
     */
    confirmTransfer?: boolean;
}

/**
 * Check if a given object implements the RuntimeActivateRequest interface.
 */
export function instanceOfRuntimeActivateRequest(value: object): value is RuntimeActivateRequest {
    if (!('licenseKey' in value) || value['licenseKey'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('installId' in value) || value['installId'] === undefined) return false;
    if (!('installPublicKey' in value) || value['installPublicKey'] === undefined) return false;
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('challengeSignature' in value) || value['challengeSignature'] === undefined) return false;
    return true;
}

export function RuntimeActivateRequestFromJSON(json: any): RuntimeActivateRequest {
    return RuntimeActivateRequestFromJSONTyped(json, false);
}

export function RuntimeActivateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeActivateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'licenseKey': json['license_key'],
        'productId': json['product_id'],
        'installId': json['install_id'],
        'installPublicKey': json['install_public_key'],
        'challenge': json['challenge'],
        'challengeSignature': json['challenge_signature'],
        'confirmTransfer': json['confirm_transfer'] == null ? undefined : json['confirm_transfer'],
    };
}

export function RuntimeActivateRequestToJSON(json: any): RuntimeActivateRequest {
    return RuntimeActivateRequestToJSONTyped(json, false);
}

export function RuntimeActivateRequestToJSONTyped(value?: RuntimeActivateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'license_key': value['licenseKey'],
        'product_id': value['productId'],
        'install_id': value['installId'],
        'install_public_key': value['installPublicKey'],
        'challenge': value['challenge'],
        'challenge_signature': value['challengeSignature'],
        'confirm_transfer': value['confirmTransfer'],
    };
}

