/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const RuntimeCommandStatus = {
    Queued: 'queued',
    Sent: 'sent',
    Acked: 'acked',
    Expired: 'expired',
    Failed: 'failed'
} as const;
export type RuntimeCommandStatus = typeof RuntimeCommandStatus[keyof typeof RuntimeCommandStatus];


export function instanceOfRuntimeCommandStatus(value: any): boolean {
    for (const key in RuntimeCommandStatus) {
        if (Object.prototype.hasOwnProperty.call(RuntimeCommandStatus, key)) {
            if (RuntimeCommandStatus[key as keyof typeof RuntimeCommandStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RuntimeCommandStatusFromJSON(json: any): RuntimeCommandStatus {
    return RuntimeCommandStatusFromJSONTyped(json, false);
}

export function RuntimeCommandStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeCommandStatus {
    return json as RuntimeCommandStatus;
}

export function RuntimeCommandStatusToJSON(value?: RuntimeCommandStatus | null): any {
    return value as any;
}

export function RuntimeCommandStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RuntimeCommandStatus {
    return value as RuntimeCommandStatus;
}

