/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriberMailingListMembership } from './SubscriberMailingListMembership';
import {
    SubscriberMailingListMembershipFromJSON,
    SubscriberMailingListMembershipFromJSONTyped,
    SubscriberMailingListMembershipToJSON,
    SubscriberMailingListMembershipToJSONTyped,
} from './SubscriberMailingListMembership';

/**
 *
 * @export
 * @interface SubscriberSummary
 */
export interface SubscriberSummary {
    /**
     *
     * @type {string}
     * @memberof SubscriberSummary
     */
    id: string;
    /**
     *
     * @type {Date}
     * @memberof SubscriberSummary
     */
    dateAdded: Date;
    /**
     *
     * @type {string}
     * @memberof SubscriberSummary
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof SubscriberSummary
     */
    name: string;
    /**
     *
     * @type {Array<SubscriberMailingListMembership>}
     * @memberof SubscriberSummary
     */
    mailingLists: Array<SubscriberMailingListMembership>;
}

/**
 * Check if a given object implements the SubscriberSummary interface.
 */
export function instanceOfSubscriberSummary(value: object): value is SubscriberSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('mailingLists' in value) || value['mailingLists'] === undefined) return false;
    return true;
}

export function SubscriberSummaryFromJSON(json: any): SubscriberSummary {
    return SubscriberSummaryFromJSONTyped(json, false);
}

export function SubscriberSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriberSummary {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'dateAdded': (new Date(json['date_added'])),
        'email': json['email'],
        'name': json['name'],
        'mailingLists': ((json['mailing_lists'] as Array<any>).map(SubscriberMailingListMembershipFromJSON)),
    };
}

export function SubscriberSummaryToJSON(json: any): SubscriberSummary {
    return SubscriberSummaryToJSONTyped(json, false);
}

export function SubscriberSummaryToJSONTyped(value?: SubscriberSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'date_added': value['dateAdded'].toISOString(),
        'email': value['email'],
        'name': value['name'],
        'mailing_lists': ((value['mailingLists'] as Array<any>).map(SubscriberMailingListMembershipToJSON)),
    };
}

