/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubscriberMailingListMembership
 */
export interface SubscriberMailingListMembership {
    /**
     *
     * @type {string}
     * @memberof SubscriberMailingListMembership
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof SubscriberMailingListMembership
     */
    name: string;
    /**
     *
     * @type {SubscriberMailingListMembershipStatusEnum}
     * @memberof SubscriberMailingListMembership
     */
    status: SubscriberMailingListMembershipStatusEnum;
}


/**
 * @export
 */
export const SubscriberMailingListMembershipStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type SubscriberMailingListMembershipStatusEnum = typeof SubscriberMailingListMembershipStatusEnum[keyof typeof SubscriberMailingListMembershipStatusEnum];


/**
 * Check if a given object implements the SubscriberMailingListMembership interface.
 */
export function instanceOfSubscriberMailingListMembership(value: object): value is SubscriberMailingListMembership {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SubscriberMailingListMembershipFromJSON(json: any): SubscriberMailingListMembership {
    return SubscriberMailingListMembershipFromJSONTyped(json, false);
}

export function SubscriberMailingListMembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriberMailingListMembership {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
        'status': json['status'],
    };
}

export function SubscriberMailingListMembershipToJSON(json: any): SubscriberMailingListMembership {
    return SubscriberMailingListMembershipToJSONTyped(json, false);
}

export function SubscriberMailingListMembershipToJSONTyped(value?: SubscriberMailingListMembership | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
    };
}

