/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriberSummary } from './SubscriberSummary';
import {
    SubscriberSummaryFromJSON,
    SubscriberSummaryFromJSONTyped,
    SubscriberSummaryToJSON,
    SubscriberSummaryToJSONTyped,
} from './SubscriberSummary';

/**
 *
 * @export
 * @interface SubscriberListResponse
 */
export interface SubscriberListResponse {
    /**
     *
     * @type {Array<SubscriberSummary>}
     * @memberof SubscriberListResponse
     */
    items: Array<SubscriberSummary>;
    /**
     *
     * @type {number}
     * @memberof SubscriberListResponse
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof SubscriberListResponse
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the SubscriberListResponse interface.
 */
export function instanceOfSubscriberListResponse(value: object): value is SubscriberListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function SubscriberListResponseFromJSON(json: any): SubscriberListResponse {
    return SubscriberListResponseFromJSONTyped(json, false);
}

export function SubscriberListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriberListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(SubscriberSummaryFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function SubscriberListResponseToJSON(json: any): SubscriberListResponse {
    return SubscriberListResponseToJSONTyped(json, false);
}

export function SubscriberListResponseToJSONTyped(value?: SubscriberListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(SubscriberSummaryToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

