/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupportOverrideAudit } from './SupportOverrideAudit';
import {
    SupportOverrideAuditFromJSON,
    SupportOverrideAuditFromJSONTyped,
    SupportOverrideAuditToJSON,
    SupportOverrideAuditToJSONTyped,
} from './SupportOverrideAudit';

/**
 *
 * @export
 * @interface SupportOverrideAuditPage
 */
export interface SupportOverrideAuditPage {
    /**
     *
     * @type {Array<SupportOverrideAudit>}
     * @memberof SupportOverrideAuditPage
     */
    items: Array<SupportOverrideAudit>;
    /**
     *
     * @type {number}
     * @memberof SupportOverrideAuditPage
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof SupportOverrideAuditPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the SupportOverrideAuditPage interface.
 */
export function instanceOfSupportOverrideAuditPage(value: object): value is SupportOverrideAuditPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function SupportOverrideAuditPageFromJSON(json: any): SupportOverrideAuditPage {
    return SupportOverrideAuditPageFromJSONTyped(json, false);
}

export function SupportOverrideAuditPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportOverrideAuditPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(SupportOverrideAuditFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'],
    };
}

export function SupportOverrideAuditPageToJSON(json: any): SupportOverrideAuditPage {
    return SupportOverrideAuditPageToJSONTyped(json, false);
}

export function SupportOverrideAuditPageToJSONTyped(value?: SupportOverrideAuditPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(SupportOverrideAuditToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

