/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductID } from './ProductID';
import {
    ProductIDFromJSON,
    ProductIDFromJSONTyped,
    ProductIDToJSON,
    ProductIDToJSONTyped,
} from './ProductID';

/**
 *
 * @export
 * @interface SupportOverrideResponse
 */
export interface SupportOverrideResponse {
    /**
     *
     * @type {string}
     * @memberof SupportOverrideResponse
     */
    licenseId: string;
    /**
     *
     * @type {ProductID}
     * @memberof SupportOverrideResponse
     */
    productId: ProductID;
    /**
     *
     * @type {Date}
     * @memberof SupportOverrideResponse
     */
    expiresAt: Date;
    /**
     *
     * @type {string}
     * @memberof SupportOverrideResponse
     */
    reason: string;
}



/**
 * Check if a given object implements the SupportOverrideResponse interface.
 */
export function instanceOfSupportOverrideResponse(value: object): value is SupportOverrideResponse {
    if (!('licenseId' in value) || value['licenseId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function SupportOverrideResponseFromJSON(json: any): SupportOverrideResponse {
    return SupportOverrideResponseFromJSONTyped(json, false);
}

export function SupportOverrideResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportOverrideResponse {
    if (json == null) {
        return json;
    }
    return {

        'licenseId': json['license_id'],
        'productId': ProductIDFromJSON(json['product_id']),
        'expiresAt': (new Date(json['expires_at'])),
        'reason': json['reason'],
    };
}

export function SupportOverrideResponseToJSON(json: any): SupportOverrideResponse {
    return SupportOverrideResponseToJSONTyped(json, false);
}

export function SupportOverrideResponseToJSONTyped(value?: SupportOverrideResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'license_id': value['licenseId'],
        'product_id': ProductIDToJSON(value['productId']),
        'expires_at': value['expiresAt'].toISOString(),
        'reason': value['reason'],
    };
}
