/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuntimeTransfer } from './RuntimeTransfer';
import {
    RuntimeTransferFromJSON,
    RuntimeTransferFromJSONTyped,
    RuntimeTransferToJSON,
    RuntimeTransferToJSONTyped,
} from './RuntimeTransfer';

/**
 *
 * @export
 * @interface TransferListResponse
 */
export interface TransferListResponse {
    /**
     *
     * @type {Array<RuntimeTransfer>}
     * @memberof TransferListResponse
     */
    items: Array<RuntimeTransfer>;
    /**
     *
     * @type {number}
     * @memberof TransferListResponse
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof TransferListResponse
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the TransferListResponse interface.
 */
export function instanceOfTransferListResponse(value: object): value is TransferListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function TransferListResponseFromJSON(json: any): TransferListResponse {
    return TransferListResponseFromJSONTyped(json, false);
}

export function TransferListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferListResponse {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(RuntimeTransferFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function TransferListResponseToJSON(json: any): TransferListResponse {
    return TransferListResponseToJSONTyped(json, false);
}

export function TransferListResponseToJSONTyped(value?: TransferListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(RuntimeTransferToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

