/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsageDailyAgg } from './UsageDailyAgg';
import {
    UsageDailyAggFromJSON,
    UsageDailyAggFromJSONTyped,
    UsageDailyAggToJSON,
    UsageDailyAggToJSONTyped,
} from './UsageDailyAgg';

/**
 * 
 * @export
 * @interface UsageDailyListResponse
 */
export interface UsageDailyListResponse {
    /**
     * 
     * @type {Array<UsageDailyAgg>}
     * @memberof UsageDailyListResponse
     */
    items: Array<UsageDailyAgg>;
}

/**
 * Check if a given object implements the UsageDailyListResponse interface.
 */
export function instanceOfUsageDailyListResponse(value: object): value is UsageDailyListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function UsageDailyListResponseFromJSON(json: any): UsageDailyListResponse {
    return UsageDailyListResponseFromJSONTyped(json, false);
}

export function UsageDailyListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageDailyListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UsageDailyAggFromJSON)),
    };
}

export function UsageDailyListResponseToJSON(json: any): UsageDailyListResponse {
    return UsageDailyListResponseToJSONTyped(json, false);
}

export function UsageDailyListResponseToJSONTyped(value?: UsageDailyListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UsageDailyAggToJSON)),
    };
}

