/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageDailyAgg
 */
export interface UsageDailyAgg {
    /**
     * 
     * @type {string}
     * @memberof UsageDailyAgg
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof UsageDailyAgg
     */
    usageDate: Date;
    /**
     * 
     * @type {string}
     * @memberof UsageDailyAgg
     */
    licenseId: string;
    /**
     * 
     * @type {string}
     * @memberof UsageDailyAgg
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof UsageDailyAgg
     */
    meterType: string;
    /**
     * 
     * @type {number}
     * @memberof UsageDailyAgg
     */
    quantity: number;
}

/**
 * Check if a given object implements the UsageDailyAgg interface.
 */
export function instanceOfUsageDailyAgg(value: object): value is UsageDailyAgg {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('usageDate' in value) || value['usageDate'] === undefined) return false;
    if (!('licenseId' in value) || value['licenseId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('meterType' in value) || value['meterType'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function UsageDailyAggFromJSON(json: any): UsageDailyAgg {
    return UsageDailyAggFromJSONTyped(json, false);
}

export function UsageDailyAggFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageDailyAgg {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'usageDate': (new Date(json['usage_date'])),
        'licenseId': json['license_id'],
        'productId': json['product_id'],
        'meterType': json['meter_type'],
        'quantity': json['quantity'],
    };
}

export function UsageDailyAggToJSON(json: any): UsageDailyAgg {
    return UsageDailyAggToJSONTyped(json, false);
}

export function UsageDailyAggToJSONTyped(value?: UsageDailyAgg | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'usage_date': value['usageDate'].toISOString().substring(0,10),
        'license_id': value['licenseId'],
        'product_id': value['productId'],
        'meter_type': value['meterType'],
        'quantity': value['quantity'],
    };
}

