/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface WebhookDeliveryMetadata
 */
export interface WebhookDeliveryMetadata {
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadata
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadata
     */
    eventId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadata
     */
    endpointId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadata
     */
    destinationId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadata
     */
    productId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadata
     */
    licenseId: string | null;
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadata
     */
    status: string;
    /**
     *
     * @type {number}
     * @memberof WebhookDeliveryMetadata
     */
    attemptCount: number;
    /**
     *
     * @type {Date}
     * @memberof WebhookDeliveryMetadata
     */
    nextAttemptAt: Date | null;
    /**
     *
     * @type {Date}
     * @memberof WebhookDeliveryMetadata
     */
    lastAttemptAt: Date | null;
    /**
     *
     * @type {number}
     * @memberof WebhookDeliveryMetadata
     */
    responseStatus: number | null;
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadata
     */
    lastError: string | null;
    /**
     *
     * @type {Date}
     * @memberof WebhookDeliveryMetadata
     */
    dateAdded: Date | null;
    /**
     *
     * @type {Date}
     * @memberof WebhookDeliveryMetadata
     */
    dateModified: Date | null;
}

/**
 * Check if a given object implements the WebhookDeliveryMetadata interface.
 */
export function instanceOfWebhookDeliveryMetadata(value: object): value is WebhookDeliveryMetadata {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('endpointId' in value) || value['endpointId'] === undefined) return false;
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('licenseId' in value) || value['licenseId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attemptCount' in value) || value['attemptCount'] === undefined) return false;
    if (!('nextAttemptAt' in value) || value['nextAttemptAt'] === undefined) return false;
    if (!('lastAttemptAt' in value) || value['lastAttemptAt'] === undefined) return false;
    if (!('responseStatus' in value) || value['responseStatus'] === undefined) return false;
    if (!('lastError' in value) || value['lastError'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    if (!('dateModified' in value) || value['dateModified'] === undefined) return false;
    return true;
}

export function WebhookDeliveryMetadataFromJSON(json: any): WebhookDeliveryMetadata {
    return WebhookDeliveryMetadataFromJSONTyped(json, false);
}

export function WebhookDeliveryMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryMetadata {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'eventId': json['event_id'],
        'endpointId': json['endpoint_id'],
        'destinationId': json['destination_id'],
        'productId': json['product_id'],
        'licenseId': json['license_id'],
        'status': json['status'],
        'attemptCount': json['attempt_count'],
        'nextAttemptAt': (json['next_attempt_at'] == null ? null : new Date(json['next_attempt_at'])),
        'lastAttemptAt': (json['last_attempt_at'] == null ? null : new Date(json['last_attempt_at'])),
        'responseStatus': json['response_status'],
        'lastError': json['last_error'],
        'dateAdded': (json['date_added'] == null ? null : new Date(json['date_added'])),
        'dateModified': (json['date_modified'] == null ? null : new Date(json['date_modified'])),
    };
}

export function WebhookDeliveryMetadataToJSON(json: any): WebhookDeliveryMetadata {
    return WebhookDeliveryMetadataToJSONTyped(json, false);
}

export function WebhookDeliveryMetadataToJSONTyped(value?: WebhookDeliveryMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'event_id': value['eventId'],
        'endpoint_id': value['endpointId'],
        'destination_id': value['destinationId'],
        'product_id': value['productId'],
        'license_id': value['licenseId'],
        'status': value['status'],
        'attempt_count': value['attemptCount'],
        'next_attempt_at': value['nextAttemptAt'] == null ? value['nextAttemptAt'] : value['nextAttemptAt'].toISOString(),
        'last_attempt_at': value['lastAttemptAt'] == null ? value['lastAttemptAt'] : value['lastAttemptAt'].toISOString(),
        'response_status': value['responseStatus'],
        'last_error': value['lastError'],
        'date_added': value['dateAdded'] == null ? value['dateAdded'] : value['dateAdded'].toISOString(),
        'date_modified': value['dateModified'] == null ? value['dateModified'] : value['dateModified'].toISOString(),
    };
}

