/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookDeliveryMetadata } from './WebhookDeliveryMetadata';
import {
    WebhookDeliveryMetadataFromJSON,
    WebhookDeliveryMetadataFromJSONTyped,
    WebhookDeliveryMetadataToJSON,
    WebhookDeliveryMetadataToJSONTyped,
} from './WebhookDeliveryMetadata';

/**
 *
 * @export
 * @interface WebhookDeliveryMetadataPage
 */
export interface WebhookDeliveryMetadataPage {
    /**
     *
     * @type {Array<WebhookDeliveryMetadata>}
     * @memberof WebhookDeliveryMetadataPage
     */
    items: Array<WebhookDeliveryMetadata>;
    /**
     *
     * @type {number}
     * @memberof WebhookDeliveryMetadataPage
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof WebhookDeliveryMetadataPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the WebhookDeliveryMetadataPage interface.
 */
export function instanceOfWebhookDeliveryMetadataPage(value: object): value is WebhookDeliveryMetadataPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function WebhookDeliveryMetadataPageFromJSON(json: any): WebhookDeliveryMetadataPage {
    return WebhookDeliveryMetadataPageFromJSONTyped(json, false);
}

export function WebhookDeliveryMetadataPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryMetadataPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(WebhookDeliveryMetadataFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'],
    };
}

export function WebhookDeliveryMetadataPageToJSON(json: any): WebhookDeliveryMetadataPage {
    return WebhookDeliveryMetadataPageToJSONTyped(json, false);
}

export function WebhookDeliveryMetadataPageToJSONTyped(value?: WebhookDeliveryMetadataPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(WebhookDeliveryMetadataToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

