/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookDestination } from './WebhookDestination';
import {
    WebhookDestinationFromJSON,
    WebhookDestinationFromJSONTyped,
    WebhookDestinationToJSON,
    WebhookDestinationToJSONTyped,
} from './WebhookDestination';

/**
 *
 * @export
 * @interface WebhookDestinationPage
 */
export interface WebhookDestinationPage {
    /**
     *
     * @type {Array<WebhookDestination>}
     * @memberof WebhookDestinationPage
     */
    items: Array<WebhookDestination>;
    /**
     *
     * @type {number}
     * @memberof WebhookDestinationPage
     */
    total: number;
    /**
     *
     * @type {string}
     * @memberof WebhookDestinationPage
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the WebhookDestinationPage interface.
 */
export function instanceOfWebhookDestinationPage(value: object): value is WebhookDestinationPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function WebhookDestinationPageFromJSON(json: any): WebhookDestinationPage {
    return WebhookDestinationPageFromJSONTyped(json, false);
}

export function WebhookDestinationPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDestinationPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(WebhookDestinationFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'],
    };
}

export function WebhookDestinationPageToJSON(json: any): WebhookDestinationPage {
    return WebhookDestinationPageToJSONTyped(json, false);
}

export function WebhookDestinationPageToJSONTyped(value?: WebhookDestinationPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(WebhookDestinationToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

