/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConsoleCheckoutPage,
  ConsoleConnection,
  ConsoleConnectionPage,
  ConsoleLicense,
  ConsoleOverview,
  ConsoleSearchResponse,
  ConsoleStripeEventPage,
  ConsoleSubscriptionPage,
  ConsoleUsageBillingSummary,
  ErrorResponse,
  NewsletterDeliveryMetadataPage,
  ProductID,
  RuntimeCommandSummary,
  SubscriberUnsubscribePage,
  SupportOverrideAuditPage,
  WebhookDeliveryMetadataPage,
  WebhookDestinationPage,
  WebhookEndpoint,
  WebhookEndpointPage,
  WebhookEventMetadata,
  WebhookEventMetadataPage,
} from '../models/index';
import {
    ConsoleCheckoutPageFromJSON,
    ConsoleCheckoutPageToJSON,
    ConsoleConnectionFromJSON,
    ConsoleConnectionToJSON,
    ConsoleConnectionPageFromJSON,
    ConsoleConnectionPageToJSON,
    ConsoleLicenseFromJSON,
    ConsoleLicenseToJSON,
    ConsoleOverviewFromJSON,
    ConsoleOverviewToJSON,
    ConsoleSearchResponseFromJSON,
    ConsoleSearchResponseToJSON,
    ConsoleStripeEventPageFromJSON,
    ConsoleStripeEventPageToJSON,
    ConsoleSubscriptionPageFromJSON,
    ConsoleSubscriptionPageToJSON,
    ConsoleUsageBillingSummaryFromJSON,
    ConsoleUsageBillingSummaryToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    NewsletterDeliveryMetadataPageFromJSON,
    NewsletterDeliveryMetadataPageToJSON,
    ProductIDFromJSON,
    ProductIDToJSON,
    RuntimeCommandSummaryFromJSON,
    RuntimeCommandSummaryToJSON,
    SubscriberUnsubscribePageFromJSON,
    SubscriberUnsubscribePageToJSON,
    SupportOverrideAuditPageFromJSON,
    SupportOverrideAuditPageToJSON,
    WebhookDeliveryMetadataPageFromJSON,
    WebhookDeliveryMetadataPageToJSON,
    WebhookDestinationPageFromJSON,
    WebhookDestinationPageToJSON,
    WebhookEndpointFromJSON,
    WebhookEndpointToJSON,
    WebhookEndpointPageFromJSON,
    WebhookEndpointPageToJSON,
    WebhookEventMetadataFromJSON,
    WebhookEventMetadataToJSON,
    WebhookEventMetadataPageFromJSON,
    WebhookEventMetadataPageToJSON,
} from '../models/index';

export interface GetConsoleConnectionRequest {
    connectionID: string;
}

export interface GetConsoleOverviewRequest {
    productId?: ProductID;
}

export interface GetLicenseAdminRequest {
    licenseID: string;
}

export interface GetLicenseUsageBillingSummaryRequest {
    licenseID: string;
    productId?: ProductID;
    from?: Date;
    to?: Date;
    month?: string;
}

export interface GetRuntimeCommandRequest {
    commandID: string;
}

export interface GetWebhookEndpointRequest {
    endpointID: string;
}

export interface GetWebhookEventRequest {
    eventID: string;
}

export interface ListBillingCheckoutsRequest {
    q?: string;
    licenseId?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListBillingSubscriptionsRequest {
    q?: string;
    licenseId?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListConsoleConnectionsRequest {
    q?: string;
    productId?: ProductID;
    licenseId?: string;
    installId?: string;
    institutionId?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListNewsletterDeliveriesRequest {
    newsletterID: string;
    q?: string;
    subscriberId?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListNewsletterRecipientOutcomesRequest {
    q?: string;
    subscriberId?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
    newsletterId?: string;
}

export interface ListProcessedStripeEventsRequest {
    q?: string;
    eventType?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListSubscriberUnsubscribesRequest {
    subscriberID: string;
    q?: string;
    mailingListId?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListSupportOverrideHistoryRequest {
    licenseID: string;
    q?: string;
    productId?: ProductID;
    action?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListWebhookDeliveriesRequest {
    q?: string;
    eventId?: string;
    endpointId?: string;
    destinationId?: string;
    productId?: ProductID;
    licenseId?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListWebhookDestinationsRequest {
    endpointID: string;
    q?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListWebhookEndpointsRequest {
    q?: string;
    productId?: ProductID;
    licenseId?: string;
    provider?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListWebhookEventsRequest {
    q?: string;
    endpointId?: string;
    productId?: ProductID;
    licenseId?: string;
    provider?: string;
    eventType?: string;
    status?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface SearchConsoleRequest {
    q?: string;
}

/**
 *
 */
export class ConsoleApi extends runtime.BaseAPI {

    /**
     * Creates request options for getConsoleConnection without sending the request
     */
    async getConsoleConnectionRequestOpts(requestParameters: GetConsoleConnectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionID'] == null) {
            throw new runtime.RequiredError(
                'connectionID',
                'Required parameter "connectionID" was null or undefined when calling getConsoleConnection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/connections/{connectionID}`;
        urlPath = urlPath.replace(`{${"connectionID"}}`, encodeURIComponent(String(requestParameters['connectionID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * getConsoleConnection
     */
    async getConsoleConnectionRaw(requestParameters: GetConsoleConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleConnection>> {
        const requestOptions = await this.getConsoleConnectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleConnectionFromJSON(jsonValue));
    }

    /**
     * getConsoleConnection
     */
    async getConsoleConnection(requestParameters: GetConsoleConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleConnection> {
        const response = await this.getConsoleConnectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConsoleOverview without sending the request
     */
    async getConsoleOverviewRequestOpts(requestParameters: GetConsoleOverviewRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/overview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * getConsoleOverview
     */
    async getConsoleOverviewRaw(requestParameters: GetConsoleOverviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleOverview>> {
        const requestOptions = await this.getConsoleOverviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleOverviewFromJSON(jsonValue));
    }

    /**
     * getConsoleOverview
     */
    async getConsoleOverview(requestParameters: GetConsoleOverviewRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleOverview> {
        const response = await this.getConsoleOverviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLicenseAdmin without sending the request
     */
    async getLicenseAdminRequestOpts(requestParameters: GetLicenseAdminRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['licenseID'] == null) {
            throw new runtime.RequiredError(
                'licenseID',
                'Required parameter "licenseID" was null or undefined when calling getLicenseAdmin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/license/{licenseID}`;
        urlPath = urlPath.replace(`{${"licenseID"}}`, encodeURIComponent(String(requestParameters['licenseID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * getLicenseAdmin
     */
    async getLicenseAdminRaw(requestParameters: GetLicenseAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleLicense>> {
        const requestOptions = await this.getLicenseAdminRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleLicenseFromJSON(jsonValue));
    }

    /**
     * getLicenseAdmin
     */
    async getLicenseAdmin(requestParameters: GetLicenseAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleLicense> {
        const response = await this.getLicenseAdminRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLicenseUsageBillingSummary without sending the request
     */
    async getLicenseUsageBillingSummaryRequestOpts(requestParameters: GetLicenseUsageBillingSummaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['licenseID'] == null) {
            throw new runtime.RequiredError(
                'licenseID',
                'Required parameter "licenseID" was null or undefined when calling getLicenseUsageBillingSummary().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/license/{licenseID}/usage-billing/summary`;
        urlPath = urlPath.replace(`{${"licenseID"}}`, encodeURIComponent(String(requestParameters['licenseID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * getLicenseUsageBillingSummary
     */
    async getLicenseUsageBillingSummaryRaw(requestParameters: GetLicenseUsageBillingSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleUsageBillingSummary>> {
        const requestOptions = await this.getLicenseUsageBillingSummaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleUsageBillingSummaryFromJSON(jsonValue));
    }

    /**
     * getLicenseUsageBillingSummary
     */
    async getLicenseUsageBillingSummary(requestParameters: GetLicenseUsageBillingSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleUsageBillingSummary> {
        const response = await this.getLicenseUsageBillingSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRuntimeCommand without sending the request
     */
    async getRuntimeCommandRequestOpts(requestParameters: GetRuntimeCommandRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commandID'] == null) {
            throw new runtime.RequiredError(
                'commandID',
                'Required parameter "commandID" was null or undefined when calling getRuntimeCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/commands/{commandID}`;
        urlPath = urlPath.replace(`{${"commandID"}}`, encodeURIComponent(String(requestParameters['commandID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * getRuntimeCommand
     */
    async getRuntimeCommandRaw(requestParameters: GetRuntimeCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeCommandSummary>> {
        const requestOptions = await this.getRuntimeCommandRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeCommandSummaryFromJSON(jsonValue));
    }

    /**
     * getRuntimeCommand
     */
    async getRuntimeCommand(requestParameters: GetRuntimeCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeCommandSummary> {
        const response = await this.getRuntimeCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWebhookEndpoint without sending the request
     */
    async getWebhookEndpointRequestOpts(requestParameters: GetWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointID'] == null) {
            throw new runtime.RequiredError(
                'endpointID',
                'Required parameter "endpointID" was null or undefined when calling getWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/endpoints/{endpointID}`;
        urlPath = urlPath.replace(`{${"endpointID"}}`, encodeURIComponent(String(requestParameters['endpointID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * getWebhookEndpoint
     */
    async getWebhookEndpointRaw(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpoint>> {
        const requestOptions = await this.getWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointFromJSON(jsonValue));
    }

    /**
     * getWebhookEndpoint
     */
    async getWebhookEndpoint(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpoint> {
        const response = await this.getWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWebhookEvent without sending the request
     */
    async getWebhookEventRequestOpts(requestParameters: GetWebhookEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventID'] == null) {
            throw new runtime.RequiredError(
                'eventID',
                'Required parameter "eventID" was null or undefined when calling getWebhookEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/events/{eventID}`;
        urlPath = urlPath.replace(`{${"eventID"}}`, encodeURIComponent(String(requestParameters['eventID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * getWebhookEvent
     */
    async getWebhookEventRaw(requestParameters: GetWebhookEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEventMetadata>> {
        const requestOptions = await this.getWebhookEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEventMetadataFromJSON(jsonValue));
    }

    /**
     * getWebhookEvent
     */
    async getWebhookEvent(requestParameters: GetWebhookEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEventMetadata> {
        const response = await this.getWebhookEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBillingCheckouts without sending the request
     */
    async listBillingCheckoutsRequestOpts(requestParameters: ListBillingCheckoutsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/checkouts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listBillingCheckouts
     */
    async listBillingCheckoutsRaw(requestParameters: ListBillingCheckoutsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleCheckoutPage>> {
        const requestOptions = await this.listBillingCheckoutsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleCheckoutPageFromJSON(jsonValue));
    }

    /**
     * listBillingCheckouts
     */
    async listBillingCheckouts(requestParameters: ListBillingCheckoutsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleCheckoutPage> {
        const response = await this.listBillingCheckoutsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBillingSubscriptions without sending the request
     */
    async listBillingSubscriptionsRequestOpts(requestParameters: ListBillingSubscriptionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/subscriptions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listBillingSubscriptions
     */
    async listBillingSubscriptionsRaw(requestParameters: ListBillingSubscriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleSubscriptionPage>> {
        const requestOptions = await this.listBillingSubscriptionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleSubscriptionPageFromJSON(jsonValue));
    }

    /**
     * listBillingSubscriptions
     */
    async listBillingSubscriptions(requestParameters: ListBillingSubscriptionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleSubscriptionPage> {
        const response = await this.listBillingSubscriptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConsoleConnections without sending the request
     */
    async listConsoleConnectionsRequestOpts(requestParameters: ListConsoleConnectionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['installId'] != null) {
            queryParameters['install_id'] = requestParameters['installId'];
        }

        if (requestParameters['institutionId'] != null) {
            queryParameters['institution_id'] = requestParameters['institutionId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/connections`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listConsoleConnections
     */
    async listConsoleConnectionsRaw(requestParameters: ListConsoleConnectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleConnectionPage>> {
        const requestOptions = await this.listConsoleConnectionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleConnectionPageFromJSON(jsonValue));
    }

    /**
     * listConsoleConnections
     */
    async listConsoleConnections(requestParameters: ListConsoleConnectionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleConnectionPage> {
        const response = await this.listConsoleConnectionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listNewsletterDeliveries without sending the request
     */
    async listNewsletterDeliveriesRequestOpts(requestParameters: ListNewsletterDeliveriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['newsletterID'] == null) {
            throw new runtime.RequiredError(
                'newsletterID',
                'Required parameter "newsletterID" was null or undefined when calling listNewsletterDeliveries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['subscriberId'] != null) {
            queryParameters['subscriber_id'] = requestParameters['subscriberId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/{newsletterID}/deliveries`;
        urlPath = urlPath.replace(`{${"newsletterID"}}`, encodeURIComponent(String(requestParameters['newsletterID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listNewsletterDeliveries
     */
    async listNewsletterDeliveriesRaw(requestParameters: ListNewsletterDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NewsletterDeliveryMetadataPage>> {
        const requestOptions = await this.listNewsletterDeliveriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NewsletterDeliveryMetadataPageFromJSON(jsonValue));
    }

    /**
     * listNewsletterDeliveries
     */
    async listNewsletterDeliveries(requestParameters: ListNewsletterDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NewsletterDeliveryMetadataPage> {
        const response = await this.listNewsletterDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listNewsletterRecipientOutcomes without sending the request
     */
    async listNewsletterRecipientOutcomesRequestOpts(requestParameters: ListNewsletterRecipientOutcomesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['subscriberId'] != null) {
            queryParameters['subscriber_id'] = requestParameters['subscriberId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['newsletterId'] != null) {
            queryParameters['newsletter_id'] = requestParameters['newsletterId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/deliveries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List recorded recipient outcomes
     */
    async listNewsletterRecipientOutcomesRaw(requestParameters: ListNewsletterRecipientOutcomesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NewsletterDeliveryMetadataPage>> {
        const requestOptions = await this.listNewsletterRecipientOutcomesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NewsletterDeliveryMetadataPageFromJSON(jsonValue));
    }

    /**
     * List recorded recipient outcomes
     */
    async listNewsletterRecipientOutcomes(requestParameters: ListNewsletterRecipientOutcomesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NewsletterDeliveryMetadataPage> {
        const response = await this.listNewsletterRecipientOutcomesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProcessedStripeEvents without sending the request
     */
    async listProcessedStripeEventsRequestOpts(requestParameters: ListProcessedStripeEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['event_type'] = requestParameters['eventType'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listProcessedStripeEvents
     */
    async listProcessedStripeEventsRaw(requestParameters: ListProcessedStripeEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleStripeEventPage>> {
        const requestOptions = await this.listProcessedStripeEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleStripeEventPageFromJSON(jsonValue));
    }

    /**
     * listProcessedStripeEvents
     */
    async listProcessedStripeEvents(requestParameters: ListProcessedStripeEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleStripeEventPage> {
        const response = await this.listProcessedStripeEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSubscriberUnsubscribes without sending the request
     */
    async listSubscriberUnsubscribesRequestOpts(requestParameters: ListSubscriberUnsubscribesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['subscriberID'] == null) {
            throw new runtime.RequiredError(
                'subscriberID',
                'Required parameter "subscriberID" was null or undefined when calling listSubscriberUnsubscribes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['mailingListId'] != null) {
            queryParameters['mailing_list_id'] = requestParameters['mailingListId'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/subscribers/{subscriberID}/unsubscribes`;
        urlPath = urlPath.replace(`{${"subscriberID"}}`, encodeURIComponent(String(requestParameters['subscriberID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listSubscriberUnsubscribes
     */
    async listSubscriberUnsubscribesRaw(requestParameters: ListSubscriberUnsubscribesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriberUnsubscribePage>> {
        const requestOptions = await this.listSubscriberUnsubscribesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriberUnsubscribePageFromJSON(jsonValue));
    }

    /**
     * listSubscriberUnsubscribes
     */
    async listSubscriberUnsubscribes(requestParameters: ListSubscriberUnsubscribesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriberUnsubscribePage> {
        const response = await this.listSubscriberUnsubscribesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSupportOverrideHistory without sending the request
     */
    async listSupportOverrideHistoryRequestOpts(requestParameters: ListSupportOverrideHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['licenseID'] == null) {
            throw new runtime.RequiredError(
                'licenseID',
                'Required parameter "licenseID" was null or undefined when calling listSupportOverrideHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['action'] != null) {
            queryParameters['action'] = requestParameters['action'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/license/{licenseID}/support-override/history`;
        urlPath = urlPath.replace(`{${"licenseID"}}`, encodeURIComponent(String(requestParameters['licenseID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listSupportOverrideHistory
     */
    async listSupportOverrideHistoryRaw(requestParameters: ListSupportOverrideHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupportOverrideAuditPage>> {
        const requestOptions = await this.listSupportOverrideHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupportOverrideAuditPageFromJSON(jsonValue));
    }

    /**
     * listSupportOverrideHistory
     */
    async listSupportOverrideHistory(requestParameters: ListSupportOverrideHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupportOverrideAuditPage> {
        const response = await this.listSupportOverrideHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookDeliveries without sending the request
     */
    async listWebhookDeliveriesRequestOpts(requestParameters: ListWebhookDeliveriesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['eventId'] != null) {
            queryParameters['event_id'] = requestParameters['eventId'];
        }

        if (requestParameters['endpointId'] != null) {
            queryParameters['endpoint_id'] = requestParameters['endpointId'];
        }

        if (requestParameters['destinationId'] != null) {
            queryParameters['destination_id'] = requestParameters['destinationId'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/deliveries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listWebhookDeliveries
     */
    async listWebhookDeliveriesRaw(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveryMetadataPage>> {
        const requestOptions = await this.listWebhookDeliveriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDeliveryMetadataPageFromJSON(jsonValue));
    }

    /**
     * listWebhookDeliveries
     */
    async listWebhookDeliveries(requestParameters: ListWebhookDeliveriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveryMetadataPage> {
        const response = await this.listWebhookDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookDestinations without sending the request
     */
    async listWebhookDestinationsRequestOpts(requestParameters: ListWebhookDestinationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointID'] == null) {
            throw new runtime.RequiredError(
                'endpointID',
                'Required parameter "endpointID" was null or undefined when calling listWebhookDestinations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/endpoints/{endpointID}/destinations`;
        urlPath = urlPath.replace(`{${"endpointID"}}`, encodeURIComponent(String(requestParameters['endpointID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listWebhookDestinations
     */
    async listWebhookDestinationsRaw(requestParameters: ListWebhookDestinationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDestinationPage>> {
        const requestOptions = await this.listWebhookDestinationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDestinationPageFromJSON(jsonValue));
    }

    /**
     * listWebhookDestinations
     */
    async listWebhookDestinations(requestParameters: ListWebhookDestinationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDestinationPage> {
        const response = await this.listWebhookDestinationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookEndpoints without sending the request
     */
    async listWebhookEndpointsRequestOpts(requestParameters: ListWebhookEndpointsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/endpoints`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listWebhookEndpoints
     */
    async listWebhookEndpointsRaw(requestParameters: ListWebhookEndpointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointPage>> {
        const requestOptions = await this.listWebhookEndpointsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointPageFromJSON(jsonValue));
    }

    /**
     * listWebhookEndpoints
     */
    async listWebhookEndpoints(requestParameters: ListWebhookEndpointsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointPage> {
        const response = await this.listWebhookEndpointsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookEvents without sending the request
     */
    async listWebhookEventsRequestOpts(requestParameters: ListWebhookEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['endpointId'] != null) {
            queryParameters['endpoint_id'] = requestParameters['endpointId'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['event_type'] = requestParameters['eventType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * listWebhookEvents
     */
    async listWebhookEventsRaw(requestParameters: ListWebhookEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEventMetadataPage>> {
        const requestOptions = await this.listWebhookEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEventMetadataPageFromJSON(jsonValue));
    }

    /**
     * listWebhookEvents
     */
    async listWebhookEvents(requestParameters: ListWebhookEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEventMetadataPage> {
        const response = await this.listWebhookEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchConsole without sending the request
     */
    async searchConsoleRequestOpts(requestParameters: SearchConsoleRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * searchConsole
     */
    async searchConsoleRaw(requestParameters: SearchConsoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsoleSearchResponse>> {
        const requestOptions = await this.searchConsoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsoleSearchResponseFromJSON(jsonValue));
    }

    /**
     * searchConsole
     */
    async searchConsole(requestParameters: SearchConsoleRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsoleSearchResponse> {
        const response = await this.searchConsoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
