/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConnectLinkTokenRequest,
  ConnectLinkTokenResponse,
  CreateLinkTokenResponse,
  ErrorResponse,
} from '../models/index';
import {
    ConnectLinkTokenRequestFromJSON,
    ConnectLinkTokenRequestToJSON,
    ConnectLinkTokenResponseFromJSON,
    ConnectLinkTokenResponseToJSON,
    CreateLinkTokenResponseFromJSON,
    CreateLinkTokenResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface ConnectLinkTokenOperationRequest {
    connectLinkTokenRequest: ConnectLinkTokenRequest;
}

/**
 * 
 */
export class LinkApi extends runtime.BaseAPI {

    /**
     * Creates request options for connectLinkToken without sending the request
     */
    async connectLinkTokenRequestOpts(requestParameters: ConnectLinkTokenOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectLinkTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'connectLinkTokenRequest',
                'Required parameter "connectLinkTokenRequest" was null or undefined when calling connectLinkToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/link/connect`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConnectLinkTokenRequestToJSON(requestParameters['connectLinkTokenRequest']),
        };
    }

    /**
     * Exchange public token and connect item
     */
    async connectLinkTokenRaw(requestParameters: ConnectLinkTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectLinkTokenResponse>> {
        const requestOptions = await this.connectLinkTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectLinkTokenResponseFromJSON(jsonValue));
    }

    /**
     * Exchange public token and connect item
     */
    async connectLinkToken(requestParameters: ConnectLinkTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectLinkTokenResponse> {
        const response = await this.connectLinkTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createLinkToken without sending the request
     */
    async createLinkTokenRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/link/token`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create Plaid link token
     */
    async createLinkTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateLinkTokenResponse>> {
        const requestOptions = await this.createLinkTokenRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateLinkTokenResponseFromJSON(jsonValue));
    }

    /**
     * Create Plaid link token
     */
    async createLinkToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateLinkTokenResponse> {
        const response = await this.createLinkTokenRaw(initOverrides);
        return await response.value();
    }

}
