/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ManagedAccountListResponse,
  ManagedBalanceSyncResponse,
  ManagedTransactionListResponse,
  ManagedTransactionSyncResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ManagedAccountListResponseFromJSON,
    ManagedAccountListResponseToJSON,
    ManagedBalanceSyncResponseFromJSON,
    ManagedBalanceSyncResponseToJSON,
    ManagedTransactionListResponseFromJSON,
    ManagedTransactionListResponseToJSON,
    ManagedTransactionSyncResponseFromJSON,
    ManagedTransactionSyncResponseToJSON,
} from '../models/index';

export interface ListManagedAccountsRequest {
    itemID: string;
}

export interface ListManagedTransactionsRequest {
    itemID: string;
    limit?: number;
    cursor?: string;
}

export interface SyncManagedBalancesRequest {
    itemID: string;
}

export interface SyncManagedTransactionsRequest {
    itemID: string;
}

/**
 *
 */
export class ManagedDataApi extends runtime.BaseAPI {

    /**
     * Creates request options for listManagedAccounts without sending the request
     */
    async listManagedAccountsRequestOpts(requestParameters: ListManagedAccountsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemID'] == null) {
            throw new runtime.RequiredError(
                'itemID',
                'Required parameter "itemID" was null or undefined when calling listManagedAccounts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/link/{itemID}/accounts`;
        urlPath = urlPath.replace(`{${"itemID"}}`, encodeURIComponent(String(requestParameters['itemID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List cached managed accounts and balances
     */
    async listManagedAccountsRaw(requestParameters: ListManagedAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedAccountListResponse>> {
        const requestOptions = await this.listManagedAccountsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedAccountListResponseFromJSON(jsonValue));
    }

    /**
     * List cached managed accounts and balances
     */
    async listManagedAccounts(requestParameters: ListManagedAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedAccountListResponse> {
        const response = await this.listManagedAccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listManagedTransactions without sending the request
     */
    async listManagedTransactionsRequestOpts(requestParameters: ListManagedTransactionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemID'] == null) {
            throw new runtime.RequiredError(
                'itemID',
                'Required parameter "itemID" was null or undefined when calling listManagedTransactions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/link/{itemID}/transactions`;
        urlPath = urlPath.replace(`{${"itemID"}}`, encodeURIComponent(String(requestParameters['itemID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List cached managed transactions
     */
    async listManagedTransactionsRaw(requestParameters: ListManagedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedTransactionListResponse>> {
        const requestOptions = await this.listManagedTransactionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedTransactionListResponseFromJSON(jsonValue));
    }

    /**
     * List cached managed transactions
     */
    async listManagedTransactions(requestParameters: ListManagedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedTransactionListResponse> {
        const response = await this.listManagedTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for syncManagedBalances without sending the request
     */
    async syncManagedBalancesRequestOpts(requestParameters: SyncManagedBalancesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemID'] == null) {
            throw new runtime.RequiredError(
                'itemID',
                'Required parameter "itemID" was null or undefined when calling syncManagedBalances().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/link/{itemID}/accounts/balances/sync`;
        urlPath = urlPath.replace(`{${"itemID"}}`, encodeURIComponent(String(requestParameters['itemID'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Refresh and cache managed accounts and balances
     */
    async syncManagedBalancesRaw(requestParameters: SyncManagedBalancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedBalanceSyncResponse>> {
        const requestOptions = await this.syncManagedBalancesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedBalanceSyncResponseFromJSON(jsonValue));
    }

    /**
     * Refresh and cache managed accounts and balances
     */
    async syncManagedBalances(requestParameters: SyncManagedBalancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedBalanceSyncResponse> {
        const response = await this.syncManagedBalancesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for syncManagedTransactions without sending the request
     */
    async syncManagedTransactionsRequestOpts(requestParameters: SyncManagedTransactionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemID'] == null) {
            throw new runtime.RequiredError(
                'itemID',
                'Required parameter "itemID" was null or undefined when calling syncManagedTransactions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/link/{itemID}/transactions/sync`;
        urlPath = urlPath.replace(`{${"itemID"}}`, encodeURIComponent(String(requestParameters['itemID'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Refresh and cache managed transactions
     */
    async syncManagedTransactionsRaw(requestParameters: SyncManagedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedTransactionSyncResponse>> {
        const requestOptions = await this.syncManagedTransactionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedTransactionSyncResponseFromJSON(jsonValue));
    }

    /**
     * Refresh and cache managed transactions
     */
    async syncManagedTransactions(requestParameters: SyncManagedTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedTransactionSyncResponse> {
        const response = await this.syncManagedTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
