/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  NewsletterSubscribeRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    NewsletterSubscribeRequestFromJSON,
    NewsletterSubscribeRequestToJSON,
} from '../models/index';

export interface SubscribeNewsletterRequest {
    newsletterSubscribeRequest: NewsletterSubscribeRequest;
}

/**
 * 
 */
export class NewsletterApi extends runtime.BaseAPI {

    /**
     * Creates request options for subscribeNewsletter without sending the request
     */
    async subscribeNewsletterRequestOpts(requestParameters: SubscribeNewsletterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['newsletterSubscribeRequest'] == null) {
            throw new runtime.RequiredError(
                'newsletterSubscribeRequest',
                'Required parameter "newsletterSubscribeRequest" was null or undefined when calling subscribeNewsletter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/subscribe`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewsletterSubscribeRequestToJSON(requestParameters['newsletterSubscribeRequest']),
        };
    }

    /**
     * Subscribe email to a mailing list (admin)
     */
    async subscribeNewsletterRaw(requestParameters: SubscribeNewsletterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.subscribeNewsletterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Subscribe email to a mailing list (admin)
     */
    async subscribeNewsletter(requestParameters: SubscribeNewsletterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.subscribeNewsletterRaw(requestParameters, initOverrides);
    }

}
