/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type MailingListListResponse,
    MailingListListResponseFromJSON,
    MailingListListResponseToJSON,
} from '../models/MailingListListResponse';
import {
    type NewsletterListResponse,
    NewsletterListResponseFromJSON,
    NewsletterListResponseToJSON,
} from '../models/NewsletterListResponse';
import {
    type NewsletterSendRequest,
    NewsletterSendRequestFromJSON,
    NewsletterSendRequestToJSON,
} from '../models/NewsletterSendRequest';
import {
    type NewsletterSendResponse,
    NewsletterSendResponseFromJSON,
    NewsletterSendResponseToJSON,
} from '../models/NewsletterSendResponse';
import {
    type NewsletterStatus,
    NewsletterStatusFromJSON,
    NewsletterStatusToJSON,
} from '../models/NewsletterStatus';
import {
    type NewsletterSubscribeRequest,
    NewsletterSubscribeRequestFromJSON,
    NewsletterSubscribeRequestToJSON,
} from '../models/NewsletterSubscribeRequest';
import {
    type SubscriberListResponse,
    SubscriberListResponseFromJSON,
    SubscriberListResponseToJSON,
} from '../models/SubscriberListResponse';

export interface ListMailingListsRequest {
    q?: string;
    limit?: number;
    cursor?: string;
}

export interface ListNewslettersRequest {
    mailingListId?: string;
    status?: NewsletterStatus;
    limit?: number;
    cursor?: string;
}

export interface ListSubscribersRequest {
    q?: string;
    mailingListId?: string;
    limit?: number;
    cursor?: string;
}

export interface SendNewsletterRequest {
    newsletterSendRequest: NewsletterSendRequest;
}

export interface SubscribeNewsletterRequest {
    newsletterSubscribeRequest: NewsletterSubscribeRequest;
}

/**
 *
 */
export class NewsletterApi extends runtime.BaseAPI {

    /**
     * Creates request options for listMailingLists without sending the request
     */
    async listMailingListsRequestOpts(requestParameters: ListMailingListsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/mailing-lists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List mailing lists (admin)
     */
    async listMailingListsRaw(requestParameters: ListMailingListsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MailingListListResponse>> {
        const requestOptions = await this.listMailingListsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MailingListListResponseFromJSON(jsonValue));
    }

    /**
     * List mailing lists (admin)
     */
    async listMailingLists(requestParameters: ListMailingListsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MailingListListResponse> {
        const response = await this.listMailingListsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listNewsletters without sending the request
     */
    async listNewslettersRequestOpts(requestParameters: ListNewslettersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['mailingListId'] != null) {
            queryParameters['mailing_list_id'] = requestParameters['mailingListId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List newsletters (admin)
     */
    async listNewslettersRaw(requestParameters: ListNewslettersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NewsletterListResponse>> {
        const requestOptions = await this.listNewslettersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NewsletterListResponseFromJSON(jsonValue));
    }

    /**
     * List newsletters (admin)
     */
    async listNewsletters(requestParameters: ListNewslettersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NewsletterListResponse> {
        const response = await this.listNewslettersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSubscribers without sending the request
     */
    async listSubscribersRequestOpts(requestParameters: ListSubscribersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['mailingListId'] != null) {
            queryParameters['mailing_list_id'] = requestParameters['mailingListId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/subscribers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List subscribers (admin)
     */
    async listSubscribersRaw(requestParameters: ListSubscribersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriberListResponse>> {
        const requestOptions = await this.listSubscribersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriberListResponseFromJSON(jsonValue));
    }

    /**
     * List subscribers (admin)
     */
    async listSubscribers(requestParameters: ListSubscribersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriberListResponse> {
        const response = await this.listSubscribersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendNewsletter without sending the request
     */
    async sendNewsletterRequestOpts(requestParameters: SendNewsletterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['newsletterSendRequest'] == null) {
            throw new runtime.RequiredError(
                'newsletterSendRequest',
                'Required parameter "newsletterSendRequest" was null or undefined when calling sendNewsletter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewsletterSendRequestToJSON(requestParameters['newsletterSendRequest']),
        };
    }

    /**
     * Publish newsletter to subscribed recipients (admin)
     */
    async sendNewsletterRaw(requestParameters: SendNewsletterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NewsletterSendResponse>> {
        const requestOptions = await this.sendNewsletterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NewsletterSendResponseFromJSON(jsonValue));
    }

    /**
     * Publish newsletter to subscribed recipients (admin)
     */
    async sendNewsletter(requestParameters: SendNewsletterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NewsletterSendResponse> {
        const response = await this.sendNewsletterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for subscribeNewsletter without sending the request
     */
    async subscribeNewsletterRequestOpts(requestParameters: SubscribeNewsletterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['newsletterSubscribeRequest'] == null) {
            throw new runtime.RequiredError(
                'newsletterSubscribeRequest',
                'Required parameter "newsletterSubscribeRequest" was null or undefined when calling subscribeNewsletter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/newsletter/subscribe`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewsletterSubscribeRequestToJSON(requestParameters['newsletterSubscribeRequest']),
        };
    }

    /**
     * Subscribe email to a mailing list (admin)
     */
    async subscribeNewsletterRaw(requestParameters: SubscribeNewsletterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.subscribeNewsletterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Subscribe email to a mailing list (admin)
     */
    async subscribeNewsletter(requestParameters: SubscribeNewsletterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.subscribeNewsletterRaw(requestParameters, initOverrides);
    }

}
