/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PlaidWebhookRequest,
    PlaidWebhookRequestToJSON,
} from '../models/PlaidWebhookRequest';
import {
    type PlaidWebhookResponse,
    PlaidWebhookResponseFromJSON,
} from '../models/PlaidWebhookResponse';

export interface ReceivePlaidWebhookRequest {
    plaidVerification: string;
    plaidWebhookRequest: PlaidWebhookRequest;
}

export class PlaidApi extends runtime.BaseAPI {
    /**
     * Creates request options for receivePlaidWebhook without sending the request
     */
    async receivePlaidWebhookRequestOpts(requestParameters: ReceivePlaidWebhookRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['plaidVerification'] == null) {
            throw new runtime.RequiredError(
                'plaidVerification',
                'Required parameter "plaidVerification" was null or undefined when calling receivePlaidWebhook().'
            );
        }
        if (requestParameters['plaidWebhookRequest'] == null) {
            throw new runtime.RequiredError(
                'plaidWebhookRequest',
                'Required parameter "plaidWebhookRequest" was null or undefined when calling receivePlaidWebhook().'
            );
        }

        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';
        headerParameters['Plaid-Verification'] = String(requestParameters['plaidVerification']);

        return {
            path: `/v1/plaid/webhook`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaidWebhookRequestToJSON(requestParameters['plaidWebhookRequest']),
        };
    }

    /**
     * Receive a verified Plaid webhook
     */
    async receivePlaidWebhookRaw(requestParameters: ReceivePlaidWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaidWebhookResponse>> {
        const requestOptions = await this.receivePlaidWebhookRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => PlaidWebhookResponseFromJSON(jsonValue));
    }

    /**
     * Receive a verified Plaid webhook
     */
    async receivePlaidWebhook(requestParameters: ReceivePlaidWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaidWebhookResponse> {
        const response = await this.receivePlaidWebhookRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
