/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type JwksResponse,
    JwksResponseFromJSON,
    JwksResponseToJSON,
} from '../models/JwksResponse';
import {
    type ProductID,
    ProductIDFromJSON,
    ProductIDToJSON,
} from '../models/ProductID';
import {
    type RuntimeActivateRequest,
    RuntimeActivateRequestFromJSON,
    RuntimeActivateRequestToJSON,
} from '../models/RuntimeActivateRequest';
import {
    type RuntimeActivateResponse,
    RuntimeActivateResponseFromJSON,
    RuntimeActivateResponseToJSON,
} from '../models/RuntimeActivateResponse';
import {
    type RuntimeActivationHistoryListResponse,
    RuntimeActivationHistoryListResponseFromJSON,
    RuntimeActivationHistoryListResponseToJSON,
} from '../models/RuntimeActivationHistoryListResponse';
import {
    type RuntimeActivationOverviewResponse,
    RuntimeActivationOverviewResponseFromJSON,
    RuntimeActivationOverviewResponseToJSON,
} from '../models/RuntimeActivationOverviewResponse';
import {
    type RuntimeCommandCreateRequest,
    RuntimeCommandCreateRequestFromJSON,
    RuntimeCommandCreateRequestToJSON,
} from '../models/RuntimeCommandCreateRequest';
import {
    type RuntimeCommandCreateResponse,
    RuntimeCommandCreateResponseFromJSON,
    RuntimeCommandCreateResponseToJSON,
} from '../models/RuntimeCommandCreateResponse';
import {
    type RuntimeCommandDeliveryListResponse,
    RuntimeCommandDeliveryListResponseFromJSON,
    RuntimeCommandDeliveryListResponseToJSON,
} from '../models/RuntimeCommandDeliveryListResponse';
import {
    type RuntimeCommandListResponse,
    RuntimeCommandListResponseFromJSON,
    RuntimeCommandListResponseToJSON,
} from '../models/RuntimeCommandListResponse';
import {
    type RuntimeCommandStatus,
    RuntimeCommandStatusFromJSON,
    RuntimeCommandStatusToJSON,
} from '../models/RuntimeCommandStatus';
import {
    type RuntimeCommandType,
    RuntimeCommandTypeFromJSON,
    RuntimeCommandTypeToJSON,
} from '../models/RuntimeCommandType';
import {
    type RuntimeEntitlementSnapshotResponse,
    RuntimeEntitlementSnapshotResponseFromJSON,
    RuntimeEntitlementSnapshotResponseToJSON,
} from '../models/RuntimeEntitlementSnapshotResponse';
import {
    type RuntimeInstanceListResponse,
    RuntimeInstanceListResponseFromJSON,
    RuntimeInstanceListResponseToJSON,
} from '../models/RuntimeInstanceListResponse';
import {
    type RuntimeRenewResponse,
    RuntimeRenewResponseFromJSON,
    RuntimeRenewResponseToJSON,
} from '../models/RuntimeRenewResponse';
import {
    type RuntimeUsageBatchRequest,
    RuntimeUsageBatchRequestFromJSON,
    RuntimeUsageBatchRequestToJSON,
} from '../models/RuntimeUsageBatchRequest';
import {
    type RuntimeUsageBatchResponse,
    RuntimeUsageBatchResponseFromJSON,
    RuntimeUsageBatchResponseToJSON,
} from '../models/RuntimeUsageBatchResponse';
import {
    type TransferConfirmationRequiredResponse,
    TransferConfirmationRequiredResponseFromJSON,
    TransferConfirmationRequiredResponseToJSON,
} from '../models/TransferConfirmationRequiredResponse';

export interface ActivateRuntimeInstallRequest {
    runtimeActivateRequest: RuntimeActivateRequest;
}

export interface CreateRuntimeCommandRequest {
    runtimeCommandCreateRequest: RuntimeCommandCreateRequest;
}

export interface GetRuntimeActivationOverviewRequest {
    productId?: ProductID;
    licenseId?: string;
    from?: Date;
    to?: Date;
}

export interface IngestRuntimeUsageBatchRequest {
    runtimeUsageBatchRequest: RuntimeUsageBatchRequest;
}

export interface ListRuntimeActivationHistoryRequest {
    productId?: ProductID;
    licenseId?: string;
    from?: Date;
    to?: Date;
    limit?: number;
    cursor?: string;
}

export interface ListRuntimeCommandDeliveriesRequest {
    commandID: string;
    limit?: number;
    cursor?: string;
}

export interface ListRuntimeCommandsRequest {
    productId?: ProductID;
    licenseId?: string;
    installId?: string;
    status?: RuntimeCommandStatus;
    commandType?: RuntimeCommandType;
    limit?: number;
    cursor?: string;
}

export interface ListRuntimeInstancesRequest {
    productId?: ProductID;
    licenseId?: string;
    installId?: string;
    connected?: boolean;
    limit?: number;
    cursor?: string;
}

/**
 *
 */
export class RuntimeApi extends runtime.BaseAPI {

    /**
     * Creates request options for activateRuntimeInstall without sending the request
     */
    async activateRuntimeInstallRequestOpts(requestParameters: ActivateRuntimeInstallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runtimeActivateRequest'] == null) {
            throw new runtime.RequiredError(
                'runtimeActivateRequest',
                'Required parameter "runtimeActivateRequest" was null or undefined when calling activateRuntimeInstall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/runtime/activate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RuntimeActivateRequestToJSON(requestParameters['runtimeActivateRequest']),
        };
    }

    /**
     * Activate runtime install and issue lease JWT
     */
    async activateRuntimeInstallRaw(requestParameters: ActivateRuntimeInstallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeActivateResponse>> {
        const requestOptions = await this.activateRuntimeInstallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeActivateResponseFromJSON(jsonValue));
    }

    /**
     * Activate runtime install and issue lease JWT
     */
    async activateRuntimeInstall(requestParameters: ActivateRuntimeInstallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeActivateResponse> {
        const response = await this.activateRuntimeInstallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createRuntimeCommand without sending the request
     */
    async createRuntimeCommandRequestOpts(requestParameters: CreateRuntimeCommandRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runtimeCommandCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'runtimeCommandCreateRequest',
                'Required parameter "runtimeCommandCreateRequest" was null or undefined when calling createRuntimeCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/commands`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RuntimeCommandCreateRequestToJSON(requestParameters['runtimeCommandCreateRequest']),
        };
    }

    /**
     * Dispatch runtime command to install/license/product target (admin)
     */
    async createRuntimeCommandRaw(requestParameters: CreateRuntimeCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeCommandCreateResponse>> {
        const requestOptions = await this.createRuntimeCommandRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeCommandCreateResponseFromJSON(jsonValue));
    }

    /**
     * Dispatch runtime command to install/license/product target (admin)
     */
    async createRuntimeCommand(requestParameters: CreateRuntimeCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeCommandCreateResponse> {
        const response = await this.createRuntimeCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCurrentRuntimeEntitlement without sending the request
     */
    async getCurrentRuntimeEntitlementRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/entitlement`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get current runtime license and entitlement snapshot
     */
    async getCurrentRuntimeEntitlementRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeEntitlementSnapshotResponse>> {
        const requestOptions = await this.getCurrentRuntimeEntitlementRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeEntitlementSnapshotResponseFromJSON(jsonValue));
    }

    /**
     * Get current runtime license and entitlement snapshot
     */
    async getCurrentRuntimeEntitlement(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeEntitlementSnapshotResponse> {
        const response = await this.getCurrentRuntimeEntitlementRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRuntimeActivationOverview without sending the request
     */
    async getRuntimeActivationOverviewRequestOpts(requestParameters: GetRuntimeActivationOverviewRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/activations/overview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get runtime activation KPI overview (admin)
     */
    async getRuntimeActivationOverviewRaw(requestParameters: GetRuntimeActivationOverviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeActivationOverviewResponse>> {
        const requestOptions = await this.getRuntimeActivationOverviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeActivationOverviewResponseFromJSON(jsonValue));
    }

    /**
     * Get runtime activation KPI overview (admin)
     */
    async getRuntimeActivationOverview(requestParameters: GetRuntimeActivationOverviewRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeActivationOverviewResponse> {
        const response = await this.getRuntimeActivationOverviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRuntimeJwks without sending the request
     */
    async getRuntimeJwksRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/runtime/jwks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get active JWKS for lease JWT verification
     */
    async getRuntimeJwksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JwksResponse>> {
        const requestOptions = await this.getRuntimeJwksRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JwksResponseFromJSON(jsonValue));
    }

    /**
     * Get active JWKS for lease JWT verification
     */
    async getRuntimeJwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JwksResponse> {
        const response = await this.getRuntimeJwksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestRuntimeUsageBatch without sending the request
     */
    async ingestRuntimeUsageBatchRequestOpts(requestParameters: IngestRuntimeUsageBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runtimeUsageBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'runtimeUsageBatchRequest',
                'Required parameter "runtimeUsageBatchRequest" was null or undefined when calling ingestRuntimeUsageBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/usage/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RuntimeUsageBatchRequestToJSON(requestParameters['runtimeUsageBatchRequest']),
        };
    }

    /**
     * Ingest usage events for billing meters
     */
    async ingestRuntimeUsageBatchRaw(requestParameters: IngestRuntimeUsageBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeUsageBatchResponse>> {
        const requestOptions = await this.ingestRuntimeUsageBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeUsageBatchResponseFromJSON(jsonValue));
    }

    /**
     * Ingest usage events for billing meters
     */
    async ingestRuntimeUsageBatch(requestParameters: IngestRuntimeUsageBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeUsageBatchResponse> {
        const response = await this.ingestRuntimeUsageBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRuntimeActivationHistory without sending the request
     */
    async listRuntimeActivationHistoryRequestOpts(requestParameters: ListRuntimeActivationHistoryRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/activations/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List runtime activation history by day (admin)
     */
    async listRuntimeActivationHistoryRaw(requestParameters: ListRuntimeActivationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeActivationHistoryListResponse>> {
        const requestOptions = await this.listRuntimeActivationHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeActivationHistoryListResponseFromJSON(jsonValue));
    }

    /**
     * List runtime activation history by day (admin)
     */
    async listRuntimeActivationHistory(requestParameters: ListRuntimeActivationHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeActivationHistoryListResponse> {
        const response = await this.listRuntimeActivationHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRuntimeCommandDeliveries without sending the request
     */
    async listRuntimeCommandDeliveriesRequestOpts(requestParameters: ListRuntimeCommandDeliveriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commandID'] == null) {
            throw new runtime.RequiredError(
                'commandID',
                'Required parameter "commandID" was null or undefined when calling listRuntimeCommandDeliveries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/commands/{commandID}/deliveries`;
        urlPath = urlPath.replace('{commandID}', encodeURIComponent(String(requestParameters['commandID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List runtime command delivery states and acknowledgements (admin)
     */
    async listRuntimeCommandDeliveriesRaw(requestParameters: ListRuntimeCommandDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeCommandDeliveryListResponse>> {
        const requestOptions = await this.listRuntimeCommandDeliveriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeCommandDeliveryListResponseFromJSON(jsonValue));
    }

    /**
     * List runtime command delivery states and acknowledgements (admin)
     */
    async listRuntimeCommandDeliveries(requestParameters: ListRuntimeCommandDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeCommandDeliveryListResponse> {
        const response = await this.listRuntimeCommandDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRuntimeCommands without sending the request
     */
    async listRuntimeCommandsRequestOpts(requestParameters: ListRuntimeCommandsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['installId'] != null) {
            queryParameters['install_id'] = requestParameters['installId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['commandType'] != null) {
            queryParameters['command_type'] = requestParameters['commandType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/commands`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List runtime commands with delivery status counters (admin)
     */
    async listRuntimeCommandsRaw(requestParameters: ListRuntimeCommandsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeCommandListResponse>> {
        const requestOptions = await this.listRuntimeCommandsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeCommandListResponseFromJSON(jsonValue));
    }

    /**
     * List runtime commands with delivery status counters (admin)
     */
    async listRuntimeCommands(requestParameters: ListRuntimeCommandsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeCommandListResponse> {
        const response = await this.listRuntimeCommandsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRuntimeInstances without sending the request
     */
    async listRuntimeInstancesRequestOpts(requestParameters: ListRuntimeInstancesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['licenseId'] != null) {
            queryParameters['license_id'] = requestParameters['licenseId'];
        }

        if (requestParameters['installId'] != null) {
            queryParameters['install_id'] = requestParameters['installId'];
        }

        if (requestParameters['connected'] != null) {
            queryParameters['connected'] = requestParameters['connected'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("AdminBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/instances`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List runtime instances and websocket connection state (admin)
     */
    async listRuntimeInstancesRaw(requestParameters: ListRuntimeInstancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeInstanceListResponse>> {
        const requestOptions = await this.listRuntimeInstancesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeInstanceListResponseFromJSON(jsonValue));
    }

    /**
     * List runtime instances and websocket connection state (admin)
     */
    async listRuntimeInstances(requestParameters: ListRuntimeInstancesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeInstanceListResponse> {
        const response = await this.listRuntimeInstancesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for renewRuntimeLease without sending the request
     */
    async renewRuntimeLeaseRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/lease/renew`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Renew runtime lease JWT
     */
    async renewRuntimeLeaseRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeRenewResponse>> {
        const requestOptions = await this.renewRuntimeLeaseRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeRenewResponseFromJSON(jsonValue));
    }

    /**
     * Renew runtime lease JWT
     */
    async renewRuntimeLease(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeRenewResponse> {
        const response = await this.renewRuntimeLeaseRaw(initOverrides);
        return await response.value();
    }

}
