/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS Management API
 * REST API for management operations across Penny stack services. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  JwksResponse,
  RuntimeActivateRequest,
  RuntimeActivateResponse,
  RuntimeRenewResponse,
  RuntimeUsageBatchRequest,
  RuntimeUsageBatchResponse,
  TransferConfirmationRequiredResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    JwksResponseFromJSON,
    JwksResponseToJSON,
    RuntimeActivateRequestFromJSON,
    RuntimeActivateRequestToJSON,
    RuntimeActivateResponseFromJSON,
    RuntimeActivateResponseToJSON,
    RuntimeRenewResponseFromJSON,
    RuntimeRenewResponseToJSON,
    RuntimeUsageBatchRequestFromJSON,
    RuntimeUsageBatchRequestToJSON,
    RuntimeUsageBatchResponseFromJSON,
    RuntimeUsageBatchResponseToJSON,
    TransferConfirmationRequiredResponseFromJSON,
    TransferConfirmationRequiredResponseToJSON,
} from '../models/index';

export interface ActivateRuntimeInstallRequest {
    runtimeActivateRequest: RuntimeActivateRequest;
}

export interface IngestRuntimeUsageBatchRequest {
    runtimeUsageBatchRequest: RuntimeUsageBatchRequest;
}

/**
 * 
 */
export class RuntimeApi extends runtime.BaseAPI {

    /**
     * Creates request options for activateRuntimeInstall without sending the request
     */
    async activateRuntimeInstallRequestOpts(requestParameters: ActivateRuntimeInstallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runtimeActivateRequest'] == null) {
            throw new runtime.RequiredError(
                'runtimeActivateRequest',
                'Required parameter "runtimeActivateRequest" was null or undefined when calling activateRuntimeInstall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/runtime/activate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RuntimeActivateRequestToJSON(requestParameters['runtimeActivateRequest']),
        };
    }

    /**
     * Activate runtime install and issue lease JWT
     */
    async activateRuntimeInstallRaw(requestParameters: ActivateRuntimeInstallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeActivateResponse>> {
        const requestOptions = await this.activateRuntimeInstallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeActivateResponseFromJSON(jsonValue));
    }

    /**
     * Activate runtime install and issue lease JWT
     */
    async activateRuntimeInstall(requestParameters: ActivateRuntimeInstallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeActivateResponse> {
        const response = await this.activateRuntimeInstallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRuntimeJwks without sending the request
     */
    async getRuntimeJwksRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/runtime/jwks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get active JWKS for lease JWT verification
     */
    async getRuntimeJwksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JwksResponse>> {
        const requestOptions = await this.getRuntimeJwksRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JwksResponseFromJSON(jsonValue));
    }

    /**
     * Get active JWKS for lease JWT verification
     */
    async getRuntimeJwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JwksResponse> {
        const response = await this.getRuntimeJwksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestRuntimeUsageBatch without sending the request
     */
    async ingestRuntimeUsageBatchRequestOpts(requestParameters: IngestRuntimeUsageBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runtimeUsageBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'runtimeUsageBatchRequest',
                'Required parameter "runtimeUsageBatchRequest" was null or undefined when calling ingestRuntimeUsageBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/usage/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RuntimeUsageBatchRequestToJSON(requestParameters['runtimeUsageBatchRequest']),
        };
    }

    /**
     * Ingest usage events for billing meters
     */
    async ingestRuntimeUsageBatchRaw(requestParameters: IngestRuntimeUsageBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeUsageBatchResponse>> {
        const requestOptions = await this.ingestRuntimeUsageBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeUsageBatchResponseFromJSON(jsonValue));
    }

    /**
     * Ingest usage events for billing meters
     */
    async ingestRuntimeUsageBatch(requestParameters: IngestRuntimeUsageBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeUsageBatchResponse> {
        const response = await this.ingestRuntimeUsageBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for renewRuntimeLease without sending the request
     */
    async renewRuntimeLeaseRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RuntimeBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/runtime/lease/renew`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Renew runtime lease JWT
     */
    async renewRuntimeLeaseRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuntimeRenewResponse>> {
        const requestOptions = await this.renewRuntimeLeaseRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuntimeRenewResponseFromJSON(jsonValue));
    }

    /**
     * Renew runtime lease JWT
     */
    async renewRuntimeLease(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuntimeRenewResponse> {
        const response = await this.renewRuntimeLeaseRaw(initOverrides);
        return await response.value();
    }

}
