/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankAccountSubtype } from './BankAccountSubtype';
import {
    BankAccountSubtypeFromJSON,
    BankAccountSubtypeFromJSONTyped,
    BankAccountSubtypeToJSON,
    BankAccountSubtypeToJSONTyped,
} from './BankAccountSubtype';
import type { BankAccountType } from './BankAccountType';
import {
    BankAccountTypeFromJSON,
    BankAccountTypeFromJSONTyped,
    BankAccountTypeToJSON,
    BankAccountTypeToJSONTyped,
} from './BankAccountType';
import type { BankAccountStatus } from './BankAccountStatus';
import {
    BankAccountStatusFromJSON,
    BankAccountStatusFromJSONTyped,
    BankAccountStatusToJSON,
    BankAccountStatusToJSONTyped,
} from './BankAccountStatus';

/**
 * 
 * @export
 * @interface AccountPatchRequest
 */
export interface AccountPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountPatchRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountPatchRequest
     */
    officialName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountPatchRequest
     */
    mask?: string | null;
    /**
     * 
     * @type {BankAccountType}
     * @memberof AccountPatchRequest
     */
    type?: BankAccountType;
    /**
     * 
     * @type {BankAccountSubtype}
     * @memberof AccountPatchRequest
     */
    subtype?: BankAccountSubtype;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof AccountPatchRequest
     */
    status?: BankAccountStatus;
}



/**
 * Check if a given object implements the AccountPatchRequest interface.
 */
export function instanceOfAccountPatchRequest(value: object): value is AccountPatchRequest {
    return true;
}

export function AccountPatchRequestFromJSON(json: any): AccountPatchRequest {
    return AccountPatchRequestFromJSONTyped(json, false);
}

export function AccountPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'officialName': json['official_name'] == null ? undefined : json['official_name'],
        'mask': json['mask'] == null ? undefined : json['mask'],
        'type': json['type'] == null ? undefined : BankAccountTypeFromJSON(json['type']),
        'subtype': json['subtype'] == null ? undefined : BankAccountSubtypeFromJSON(json['subtype']),
        'status': json['status'] == null ? undefined : BankAccountStatusFromJSON(json['status']),
    };
}

export function AccountPatchRequestToJSON(json: any): AccountPatchRequest {
    return AccountPatchRequestToJSONTyped(json, false);
}

export function AccountPatchRequestToJSONTyped(value?: AccountPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'official_name': value['officialName'],
        'mask': value['mask'],
        'type': BankAccountTypeToJSON(value['type']),
        'subtype': BankAccountSubtypeToJSON(value['subtype']),
        'status': BankAccountStatusToJSON(value['status']),
    };
}

