/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BankAccountSubtype = {
    Checking: 'checking',
    Savings: 'savings',
    MoneyMarket: 'money market',
    CertificateOfDeposit: 'certificate of deposit',
    CreditCard: 'credit card',
    Auto: 'auto',
    Business: 'business',
    Commercial: 'commercial',
    Construction: 'construction',
    Consumer: 'consumer',
    HomeEquity: 'home equity',
    LineOfCredit: 'line of credit',
    Mortgage: 'mortgage',
    Student: 'student',
    _401k: '401k',
    _529: '529',
    _401a: '401a',
    _403b: '403b',
    Brokerage: 'brokerage',
    CashManagement: 'cash management',
    Ira: 'ira',
    Roth: 'roth',
    Hsa: 'hsa',
    StockPlan: 'stock plan',
    Trust: 'trust',
    Other: 'other'
} as const;
export type BankAccountSubtype = typeof BankAccountSubtype[keyof typeof BankAccountSubtype];


export function instanceOfBankAccountSubtype(value: any): boolean {
    for (const key in BankAccountSubtype) {
        if (Object.prototype.hasOwnProperty.call(BankAccountSubtype, key)) {
            if (BankAccountSubtype[key as keyof typeof BankAccountSubtype] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BankAccountSubtypeFromJSON(json: any): BankAccountSubtype {
    return BankAccountSubtypeFromJSONTyped(json, false);
}

export function BankAccountSubtypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountSubtype {
    return json as BankAccountSubtype;
}

export function BankAccountSubtypeToJSON(value?: BankAccountSubtype | null): any {
    return value as any;
}

export function BankAccountSubtypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BankAccountSubtype {
    return value as BankAccountSubtype;
}

