/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BudgetPeriodAllocation } from './BudgetPeriodAllocation';
import {
    BudgetPeriodAllocationFromJSON,
    BudgetPeriodAllocationFromJSONTyped,
    BudgetPeriodAllocationToJSON,
    BudgetPeriodAllocationToJSONTyped,
} from './BudgetPeriodAllocation';
import type { BudgetPeriodStatus } from './BudgetPeriodStatus';
import {
    BudgetPeriodStatusFromJSON,
    BudgetPeriodStatusFromJSONTyped,
    BudgetPeriodStatusToJSON,
    BudgetPeriodStatusToJSONTyped,
} from './BudgetPeriodStatus';

/**
 * 
 * @export
 * @interface BudgetPeriod
 */
export interface BudgetPeriod {
    /**
     * 
     * @type {string}
     * @memberof BudgetPeriod
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetPeriod
     */
    budgetId: string;
    /**
     * 
     * @type {Date}
     * @memberof BudgetPeriod
     */
    dateAdded: Date;
    /**
     * 
     * @type {Date}
     * @memberof BudgetPeriod
     */
    dateModified?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BudgetPeriod
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof BudgetPeriod
     */
    endDate: Date;
    /**
     * 
     * @type {number}
     * @memberof BudgetPeriod
     */
    targetAmount: number;
    /**
     * 
     * @type {BudgetPeriodStatus}
     * @memberof BudgetPeriod
     */
    status: BudgetPeriodStatus;
    /**
     * 
     * @type {Array<BudgetPeriodAllocation>}
     * @memberof BudgetPeriod
     */
    allocations: Array<BudgetPeriodAllocation>;
}



/**
 * Check if a given object implements the BudgetPeriod interface.
 */
export function instanceOfBudgetPeriod(value: object): value is BudgetPeriod {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('budgetId' in value) || value['budgetId'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('targetAmount' in value) || value['targetAmount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('allocations' in value) || value['allocations'] === undefined) return false;
    return true;
}

export function BudgetPeriodFromJSON(json: any): BudgetPeriod {
    return BudgetPeriodFromJSONTyped(json, false);
}

export function BudgetPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'budgetId': json['budget_id'],
        'dateAdded': (new Date(json['date_added'])),
        'dateModified': json['date_modified'] == null ? undefined : (new Date(json['date_modified'])),
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'targetAmount': json['target_amount'],
        'status': BudgetPeriodStatusFromJSON(json['status']),
        'allocations': ((json['allocations'] as Array<any>).map(BudgetPeriodAllocationFromJSON)),
    };
}

export function BudgetPeriodToJSON(json: any): BudgetPeriod {
    return BudgetPeriodToJSONTyped(json, false);
}

export function BudgetPeriodToJSONTyped(value?: BudgetPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'budget_id': value['budgetId'],
        'date_added': value['dateAdded'].toISOString(),
        'date_modified': value['dateModified'] == null ? value['dateModified'] : value['dateModified'].toISOString(),
        'start_date': value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'].toISOString().substring(0,10),
        'target_amount': value['targetAmount'],
        'status': BudgetPeriodStatusToJSON(value['status']),
        'allocations': ((value['allocations'] as Array<any>).map(BudgetPeriodAllocationToJSON)),
    };
}

