/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BudgetPeriodAllocation } from './BudgetPeriodAllocation';
import {
    BudgetPeriodAllocationFromJSON,
    BudgetPeriodAllocationFromJSONTyped,
    BudgetPeriodAllocationToJSON,
    BudgetPeriodAllocationToJSONTyped,
} from './BudgetPeriodAllocation';

/**
 * 
 * @export
 * @interface BudgetPeriodAllocationsReplaceRequest
 */
export interface BudgetPeriodAllocationsReplaceRequest {
    /**
     * 
     * @type {Array<BudgetPeriodAllocation>}
     * @memberof BudgetPeriodAllocationsReplaceRequest
     */
    allocations: Array<BudgetPeriodAllocation>;
}

/**
 * Check if a given object implements the BudgetPeriodAllocationsReplaceRequest interface.
 */
export function instanceOfBudgetPeriodAllocationsReplaceRequest(value: object): value is BudgetPeriodAllocationsReplaceRequest {
    if (!('allocations' in value) || value['allocations'] === undefined) return false;
    return true;
}

export function BudgetPeriodAllocationsReplaceRequestFromJSON(json: any): BudgetPeriodAllocationsReplaceRequest {
    return BudgetPeriodAllocationsReplaceRequestFromJSONTyped(json, false);
}

export function BudgetPeriodAllocationsReplaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetPeriodAllocationsReplaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'allocations': ((json['allocations'] as Array<any>).map(BudgetPeriodAllocationFromJSON)),
    };
}

export function BudgetPeriodAllocationsReplaceRequestToJSON(json: any): BudgetPeriodAllocationsReplaceRequest {
    return BudgetPeriodAllocationsReplaceRequestToJSONTyped(json, false);
}

export function BudgetPeriodAllocationsReplaceRequestToJSONTyped(value?: BudgetPeriodAllocationsReplaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allocations': ((value['allocations'] as Array<any>).map(BudgetPeriodAllocationToJSON)),
    };
}

