/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Budget
 */
export interface Budget {
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof Budget
     */
    dateAdded: Date;
    /**
     * 
     * @type {Date}
     * @memberof Budget
     */
    dateModified?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    currencyCode: string;
}

/**
 * Check if a given object implements the Budget interface.
 */
export function instanceOfBudget(value: object): value is Budget {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('dateAdded' in value) || value['dateAdded'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('currencyCode' in value) || value['currencyCode'] === undefined) return false;
    return true;
}

export function BudgetFromJSON(json: any): Budget {
    return BudgetFromJSONTyped(json, false);
}

export function BudgetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Budget {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dateAdded': (new Date(json['date_added'])),
        'dateModified': json['date_modified'] == null ? undefined : (new Date(json['date_modified'])),
        'name': json['name'],
        'currencyCode': json['currency_code'],
    };
}

export function BudgetToJSON(json: any): Budget {
    return BudgetToJSONTyped(json, false);
}

export function BudgetToJSONTyped(value?: Budget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date_added': value['dateAdded'].toISOString(),
        'date_modified': value['dateModified'] == null ? value['dateModified'] : value['dateModified'].toISOString(),
        'name': value['name'],
        'currency_code': value['currencyCode'],
    };
}

