/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BudgetPeriodStatus = {
    Draft: 'draft',
    Active: 'active',
    Closed: 'closed'
} as const;
export type BudgetPeriodStatus = typeof BudgetPeriodStatus[keyof typeof BudgetPeriodStatus];


export function instanceOfBudgetPeriodStatus(value: any): boolean {
    for (const key in BudgetPeriodStatus) {
        if (Object.prototype.hasOwnProperty.call(BudgetPeriodStatus, key)) {
            if (BudgetPeriodStatus[key as keyof typeof BudgetPeriodStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BudgetPeriodStatusFromJSON(json: any): BudgetPeriodStatus {
    return BudgetPeriodStatusFromJSONTyped(json, false);
}

export function BudgetPeriodStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetPeriodStatus {
    return json as BudgetPeriodStatus;
}

export function BudgetPeriodStatusToJSON(value?: BudgetPeriodStatus | null): any {
    return value as any;
}

export function BudgetPeriodStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BudgetPeriodStatus {
    return value as BudgetPeriodStatus;
}

