/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';

/**
 * 
 * @export
 * @interface CategoryListResponse
 */
export interface CategoryListResponse {
    /**
     * 
     * @type {Array<Category>}
     * @memberof CategoryListResponse
     */
    items: Array<Category>;
    /**
     * 
     * @type {number}
     * @memberof CategoryListResponse
     */
    total: number;
}

/**
 * Check if a given object implements the CategoryListResponse interface.
 */
export function instanceOfCategoryListResponse(value: object): value is CategoryListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function CategoryListResponseFromJSON(json: any): CategoryListResponse {
    return CategoryListResponseFromJSONTyped(json, false);
}

export function CategoryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CategoryFromJSON)),
        'total': json['total'],
    };
}

export function CategoryListResponseToJSON(json: any): CategoryListResponse {
    return CategoryListResponseToJSONTyped(json, false);
}

export function CategoryListResponseToJSONTyped(value?: CategoryListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CategoryToJSON)),
        'total': value['total'],
    };
}

