/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryPatchRequest
 */
export interface CategoryPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof CategoryPatchRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the CategoryPatchRequest interface.
 */
export function instanceOfCategoryPatchRequest(value: object): value is CategoryPatchRequest {
    return true;
}

export function CategoryPatchRequestFromJSON(json: any): CategoryPatchRequest {
    return CategoryPatchRequestFromJSONTyped(json, false);
}

export function CategoryPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CategoryPatchRequestToJSON(json: any): CategoryPatchRequest {
    return CategoryPatchRequestToJSONTyped(json, false);
}

export function CategoryPatchRequestToJSONTyped(value?: CategoryPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

