/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryDeleteDependencyCounts } from './CategoryDeleteDependencyCounts';
import {
    CategoryDeleteDependencyCountsFromJSON,
    CategoryDeleteDependencyCountsFromJSONTyped,
    CategoryDeleteDependencyCountsToJSON,
    CategoryDeleteDependencyCountsToJSONTyped,
} from './CategoryDeleteDependencyCounts';

/**
 * 
 * @export
 * @interface CategoryDeleteImpact
 */
export interface CategoryDeleteImpact {
    categoryId: string;
    mode: CategoryDeleteImpactModeEnum;
    canDelete: boolean;
    dependencyCounts: CategoryDeleteDependencyCounts;
    blockingReasons: Array<CategoryDeleteImpactBlockingReasonsEnum>;
}

export const CategoryDeleteImpactModeEnum = {
    Block: 'block'
} as const;
export type CategoryDeleteImpactModeEnum = typeof CategoryDeleteImpactModeEnum[keyof typeof CategoryDeleteImpactModeEnum];
export const CategoryDeleteImpactBlockingReasonsEnum = {
    ChildCategories: 'child_categories',
    Transactions: 'transactions',
    BudgetPeriodAllocations: 'budget_period_allocations',
    TransactionRules: 'transaction_rules'
} as const;
export type CategoryDeleteImpactBlockingReasonsEnum = typeof CategoryDeleteImpactBlockingReasonsEnum[keyof typeof CategoryDeleteImpactBlockingReasonsEnum];

export function instanceOfCategoryDeleteImpact(value: object): value is CategoryDeleteImpact {
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('canDelete' in value) || value['canDelete'] === undefined) return false;
    if (!('dependencyCounts' in value) || value['dependencyCounts'] === undefined) return false;
    if (!('blockingReasons' in value) || value['blockingReasons'] === undefined) return false;
    return true;
}

export function CategoryDeleteImpactFromJSON(json: any): CategoryDeleteImpact {
    return CategoryDeleteImpactFromJSONTyped(json, false);
}

export function CategoryDeleteImpactFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDeleteImpact {
    if (json == null) {
        return json;
    }
    return {
        'categoryId': json['category_id'],
        'mode': json['mode'],
        'canDelete': json['can_delete'],
        'dependencyCounts': CategoryDeleteDependencyCountsFromJSON(json['dependency_counts']),
        'blockingReasons': json['blocking_reasons'],
    };
}

export function CategoryDeleteImpactToJSON(json: any): CategoryDeleteImpact {
    return CategoryDeleteImpactToJSONTyped(json, false);
}

export function CategoryDeleteImpactToJSONTyped(value?: CategoryDeleteImpact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'category_id': value['categoryId'],
        'mode': value['mode'],
        'can_delete': value['canDelete'],
        'dependency_counts': CategoryDeleteDependencyCountsToJSON(value['dependencyCounts']),
        'blocking_reasons': value['blockingReasons'],
    };
}
