/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryDeleteDependencyCounts
 */
export interface CategoryDeleteDependencyCounts {
    /**
     * 
     * @type {number}
     * @memberof CategoryDeleteDependencyCounts
     */
    childCategories: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryDeleteDependencyCounts
     */
    transactions: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryDeleteDependencyCounts
     */
    budgetPeriodAllocations: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryDeleteDependencyCounts
     */
    transactionRules: number;
}

/**
 * Check if a given object implements the CategoryDeleteDependencyCounts interface.
 */
export function instanceOfCategoryDeleteDependencyCounts(value: object): value is CategoryDeleteDependencyCounts {
    if (!('childCategories' in value) || value['childCategories'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('budgetPeriodAllocations' in value) || value['budgetPeriodAllocations'] === undefined) return false;
    if (!('transactionRules' in value) || value['transactionRules'] === undefined) return false;
    return true;
}

export function CategoryDeleteDependencyCountsFromJSON(json: any): CategoryDeleteDependencyCounts {
    return CategoryDeleteDependencyCountsFromJSONTyped(json, false);
}

export function CategoryDeleteDependencyCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDeleteDependencyCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'childCategories': json['child_categories'],
        'transactions': json['transactions'],
        'budgetPeriodAllocations': json['budget_period_allocations'],
        'transactionRules': json['transaction_rules'],
    };
}

export function CategoryDeleteDependencyCountsToJSON(json: any): CategoryDeleteDependencyCounts {
    return CategoryDeleteDependencyCountsToJSONTyped(json, false);
}

export function CategoryDeleteDependencyCountsToJSONTyped(value?: CategoryDeleteDependencyCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'child_categories': value['childCategories'],
        'transactions': value['transactions'],
        'budget_period_allocations': value['budgetPeriodAllocations'],
        'transaction_rules': value['transactionRules'],
    };
}

