/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionExportFormat } from './TransactionExportFormat';
import {
    TransactionExportFormatFromJSON,
    TransactionExportFormatFromJSONTyped,
    TransactionExportFormatToJSON,
    TransactionExportFormatToJSONTyped,
} from './TransactionExportFormat';

/**
 * 
 * @export
 * @interface CreateTransactionExportRequest
 */
export interface CreateTransactionExportRequest {
    /**
     * 
     * @type {TransactionExportFormat}
     * @memberof CreateTransactionExportRequest
     */
    format: TransactionExportFormat;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateTransactionExportRequest
     */
    accountIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionExportRequest
     */
    q?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateTransactionExportRequest
     */
    pending?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CreateTransactionExportRequest
     */
    dateFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateTransactionExportRequest
     */
    dateTo?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionExportRequest
     */
    amountMin?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionExportRequest
     */
    amountMax?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionExportRequest
     */
    categoryId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateTransactionExportRequest
     */
    tagIds?: Array<string>;
    /**
     * 
     * @type {CreateTransactionExportRequestTagModeEnum}
     * @memberof CreateTransactionExportRequest
     */
    tagMode?: CreateTransactionExportRequestTagModeEnum;
    /**
     * 
     * @type {CreateTransactionExportRequestSortEnum}
     * @memberof CreateTransactionExportRequest
     */
    sort?: CreateTransactionExportRequestSortEnum;
}


/**
 * @export
 */
export const CreateTransactionExportRequestTagModeEnum = {
    Any: 'any',
    All: 'all'
} as const;
export type CreateTransactionExportRequestTagModeEnum = typeof CreateTransactionExportRequestTagModeEnum[keyof typeof CreateTransactionExportRequestTagModeEnum];

/**
 * @export
 */
export const CreateTransactionExportRequestSortEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type CreateTransactionExportRequestSortEnum = typeof CreateTransactionExportRequestSortEnum[keyof typeof CreateTransactionExportRequestSortEnum];


/**
 * Check if a given object implements the CreateTransactionExportRequest interface.
 */
export function instanceOfCreateTransactionExportRequest(value: object): value is CreateTransactionExportRequest {
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('accountIds' in value) || value['accountIds'] === undefined) return false;
    return true;
}

export function CreateTransactionExportRequestFromJSON(json: any): CreateTransactionExportRequest {
    return CreateTransactionExportRequestFromJSONTyped(json, false);
}

export function CreateTransactionExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionExportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'format': TransactionExportFormatFromJSON(json['format']),
        'accountIds': json['account_ids'],
        'q': json['q'] == null ? undefined : json['q'],
        'pending': json['pending'] == null ? undefined : json['pending'],
        'dateFrom': json['date_from'] == null ? undefined : (new Date(json['date_from'])),
        'dateTo': json['date_to'] == null ? undefined : (new Date(json['date_to'])),
        'amountMin': json['amount_min'] == null ? undefined : json['amount_min'],
        'amountMax': json['amount_max'] == null ? undefined : json['amount_max'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'tagIds': json['tag_ids'] == null ? undefined : json['tag_ids'],
        'tagMode': json['tag_mode'] == null ? undefined : json['tag_mode'],
        'sort': json['sort'] == null ? undefined : json['sort'],
    };
}

export function CreateTransactionExportRequestToJSON(json: any): CreateTransactionExportRequest {
    return CreateTransactionExportRequestToJSONTyped(json, false);
}

export function CreateTransactionExportRequestToJSONTyped(value?: CreateTransactionExportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format': TransactionExportFormatToJSON(value['format']),
        'account_ids': value['accountIds'],
        'q': value['q'],
        'pending': value['pending'],
        'date_from': value['dateFrom'] == null ? value['dateFrom'] : value['dateFrom'].toISOString(),
        'date_to': value['dateTo'] == null ? value['dateTo'] : value['dateTo'].toISOString(),
        'amount_min': value['amountMin'],
        'amount_max': value['amountMax'],
        'category_id': value['categoryId'],
        'tag_ids': value['tagIds'],
        'tag_mode': value['tagMode'],
        'sort': value['sort'],
    };
}

