/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ManagedLinkTokenResponse
 */
export interface ManagedLinkTokenResponse {
    /**
     *
     * @type {string}
     * @memberof ManagedLinkTokenResponse
     */
    connectionId?: string;
    /**
     *
     * @type {string}
     * @memberof ManagedLinkTokenResponse
     */
    linkToken: string;
    /**
     *
     * @type {Date}
     * @memberof ManagedLinkTokenResponse
     */
    expiration?: Date;
    /**
     *
     * @type {ManagedLinkTokenResponseModeEnum}
     * @memberof ManagedLinkTokenResponse
     */
    mode?: ManagedLinkTokenResponseModeEnum;
}


/**
 * @export
 */
export const ManagedLinkTokenResponseModeEnum = {
    Create: 'create',
    Update: 'update'
} as const;
export type ManagedLinkTokenResponseModeEnum = typeof ManagedLinkTokenResponseModeEnum[keyof typeof ManagedLinkTokenResponseModeEnum];


/**
 * Check if a given object implements the ManagedLinkTokenResponse interface.
 */
export function instanceOfManagedLinkTokenResponse(value: object): value is ManagedLinkTokenResponse {
    if (!('linkToken' in value) || value['linkToken'] === undefined) return false;
    return true;
}

export function ManagedLinkTokenResponseFromJSON(json: any): ManagedLinkTokenResponse {
    return ManagedLinkTokenResponseFromJSONTyped(json, false);
}

export function ManagedLinkTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedLinkTokenResponse {
    if (json == null) {
        return json;
    }
    return {

        'connectionId': json['connection_id'] == null ? undefined : json['connection_id'],
        'linkToken': json['link_token'],
        'expiration': json['expiration'] == null ? undefined : (new Date(json['expiration'])),
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function ManagedLinkTokenResponseToJSON(json: any): ManagedLinkTokenResponse {
    return ManagedLinkTokenResponseToJSONTyped(json, false);
}

export function ManagedLinkTokenResponseToJSONTyped(value?: ManagedLinkTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'connection_id': value['connectionId'],
        'link_token': value['linkToken'],
        'expiration': value['expiration'] == null ? value['expiration'] : value['expiration'].toISOString(),
        'mode': value['mode'],
    };
}
