/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ManagedLinkInstitution
 */
export interface ManagedLinkInstitution {
    /**
     *
     * @type {string}
     * @memberof ManagedLinkInstitution
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ManagedLinkInstitution
     */
    institutionId: string;
}

/**
 * Check if a given object implements the ManagedLinkInstitution interface.
 */
export function instanceOfManagedLinkInstitution(value: object): value is ManagedLinkInstitution {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('institutionId' in value) || value['institutionId'] === undefined) return false;
    return true;
}

export function ManagedLinkInstitutionFromJSON(json: any): ManagedLinkInstitution {
    return ManagedLinkInstitutionFromJSONTyped(json, false);
}

export function ManagedLinkInstitutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedLinkInstitution {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'institutionId': json['institution_id'],
    };
}

export function ManagedLinkInstitutionToJSON(json: any): ManagedLinkInstitution {
    return ManagedLinkInstitutionToJSONTyped(json, false);
}

export function ManagedLinkInstitutionToJSONTyped(value?: ManagedLinkInstitution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
        'institution_id': value['institutionId'],
    };
}
