/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RuntimeEntitlementSnapshotResponse
 */
export interface RuntimeEntitlementSnapshotResponse {
    /**
     * Whether a local runtime entitlement snapshot has been persisted.
     * @type {boolean}
     * @memberof RuntimeEntitlementSnapshotResponse
     */
    configured: boolean;
    /**
     *
     * @type {string}
     * @memberof RuntimeEntitlementSnapshotResponse
     */
    licenseStatus?: string;
    /**
     *
     * @type {string}
     * @memberof RuntimeEntitlementSnapshotResponse
     */
    plan?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof RuntimeEntitlementSnapshotResponse
     */
    features?: Array<string>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof RuntimeEntitlementSnapshotResponse
     */
    entitlements?: { [key: string]: any; };
    /**
     *
     * @type {Date}
     * @memberof RuntimeEntitlementSnapshotResponse
     */
    lastSyncedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof RuntimeEntitlementSnapshotResponse
     */
    dateAdded?: Date;
    /**
     *
     * @type {Date}
     * @memberof RuntimeEntitlementSnapshotResponse
     */
    dateModified?: Date | null;
}

/**
 * Check if a given object implements the RuntimeEntitlementSnapshotResponse interface.
 */
export function instanceOfRuntimeEntitlementSnapshotResponse(value: object): value is RuntimeEntitlementSnapshotResponse {
    if (!('configured' in value) || value['configured'] === undefined) return false;
    return true;
}

export function RuntimeEntitlementSnapshotResponseFromJSON(json: any): RuntimeEntitlementSnapshotResponse {
    return RuntimeEntitlementSnapshotResponseFromJSONTyped(json, false);
}

export function RuntimeEntitlementSnapshotResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeEntitlementSnapshotResponse {
    if (json == null) {
        return json;
    }
    return {
        'configured': json['configured'],
        'licenseStatus': json['license_status'] == null ? undefined : json['license_status'],
        'plan': json['plan'] == null ? undefined : json['plan'],
        'features': json['features'] == null ? undefined : json['features'],
        'entitlements': json['entitlements'] == null ? undefined : json['entitlements'],
        'lastSyncedAt': json['last_synced_at'] == null ? undefined : (new Date(json['last_synced_at'])),
        'dateAdded': json['date_added'] == null ? undefined : (new Date(json['date_added'])),
        'dateModified': json['date_modified'] == null ? undefined : (new Date(json['date_modified'])),
    };
}

export function RuntimeEntitlementSnapshotResponseToJSON(json: any): RuntimeEntitlementSnapshotResponse {
    return RuntimeEntitlementSnapshotResponseToJSONTyped(json, false);
}

export function RuntimeEntitlementSnapshotResponseToJSONTyped(value?: RuntimeEntitlementSnapshotResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'configured': value['configured'],
        'license_status': value['licenseStatus'],
        'plan': value['plan'],
        'features': value['features'],
        'entitlements': value['entitlements'],
        'last_synced_at': value['lastSyncedAt'] == null ? undefined : ((value['lastSyncedAt'] as any).toISOString()),
        'date_added': value['dateAdded'] == null ? undefined : ((value['dateAdded'] as any).toISOString()),
        'date_modified': value['dateModified'] == null ? undefined : ((value['dateModified'] as any).toISOString()),
    };
}
