/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuntimeStatusWebsocket
 */
export interface RuntimeStatusWebsocket {
    /**
     * 
     * @type {boolean}
     * @memberof RuntimeStatusWebsocket
     */
    enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RuntimeStatusWebsocket
     */
    configured: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RuntimeStatusWebsocket
     */
    endpointConfigured: boolean;
    /**
     * 
     * @type {RuntimeStatusWebsocketStatusEnum}
     * @memberof RuntimeStatusWebsocket
     */
    status: RuntimeStatusWebsocketStatusEnum;
}


/**
 * @export
 */
export const RuntimeStatusWebsocketStatusEnum = {
    Disabled: 'disabled',
    Configured: 'configured',
    MissingRequirements: 'missing_requirements'
} as const;
export type RuntimeStatusWebsocketStatusEnum = typeof RuntimeStatusWebsocketStatusEnum[keyof typeof RuntimeStatusWebsocketStatusEnum];


/**
 * Check if a given object implements the RuntimeStatusWebsocket interface.
 */
export function instanceOfRuntimeStatusWebsocket(value: object): value is RuntimeStatusWebsocket {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('configured' in value) || value['configured'] === undefined) return false;
    if (!('endpointConfigured' in value) || value['endpointConfigured'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RuntimeStatusWebsocketFromJSON(json: any): RuntimeStatusWebsocket {
    return RuntimeStatusWebsocketFromJSONTyped(json, false);
}

export function RuntimeStatusWebsocketFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeStatusWebsocket {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'configured': json['configured'],
        'endpointConfigured': json['endpoint_configured'],
        'status': json['status'],
    };
}

export function RuntimeStatusWebsocketToJSON(json: any): RuntimeStatusWebsocket {
    return RuntimeStatusWebsocketToJSONTyped(json, false);
}

export function RuntimeStatusWebsocketToJSONTyped(value?: RuntimeStatusWebsocket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'configured': value['configured'],
        'endpoint_configured': value['endpointConfigured'],
        'status': value['status'],
    };
}

