/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuntimeStatusEntitlement
 */
export interface RuntimeStatusEntitlement {
    /**
     * 
     * @type {boolean}
     * @memberof RuntimeStatusEntitlement
     */
    configured: boolean;
    /**
     * 
     * @type {string}
     * @memberof RuntimeStatusEntitlement
     */
    licenseStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeStatusEntitlement
     */
    entitlementStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeStatusEntitlement
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof RuntimeStatusEntitlement
     */
    plan?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RuntimeStatusEntitlement
     */
    features?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof RuntimeStatusEntitlement
     */
    lastSyncedAt?: Date;
}

/**
 * Check if a given object implements the RuntimeStatusEntitlement interface.
 */
export function instanceOfRuntimeStatusEntitlement(value: object): value is RuntimeStatusEntitlement {
    if (!('configured' in value) || value['configured'] === undefined) return false;
    return true;
}

export function RuntimeStatusEntitlementFromJSON(json: any): RuntimeStatusEntitlement {
    return RuntimeStatusEntitlementFromJSONTyped(json, false);
}

export function RuntimeStatusEntitlementFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeStatusEntitlement {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'],
        'licenseStatus': json['license_status'] == null ? undefined : json['license_status'],
        'entitlementStatus': json['entitlement_status'] == null ? undefined : json['entitlement_status'],
        'productId': json['product_id'] == null ? undefined : json['product_id'],
        'plan': json['plan'] == null ? undefined : json['plan'],
        'features': json['features'] == null ? undefined : json['features'],
        'lastSyncedAt': json['last_synced_at'] == null ? undefined : (new Date(json['last_synced_at'])),
    };
}

export function RuntimeStatusEntitlementToJSON(json: any): RuntimeStatusEntitlement {
    return RuntimeStatusEntitlementToJSONTyped(json, false);
}

export function RuntimeStatusEntitlementToJSONTyped(value?: RuntimeStatusEntitlement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'license_status': value['licenseStatus'],
        'entitlement_status': value['entitlementStatus'],
        'product_id': value['productId'],
        'plan': value['plan'],
        'features': value['features'],
        'last_synced_at': value['lastSyncedAt'] == null ? value['lastSyncedAt'] : value['lastSyncedAt'].toISOString(),
    };
}

