/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignoutResponse
 */
export interface SignoutResponse {
    /**
     * 
     * @type {string}
     * @memberof SignoutResponse
     */
    status: string;
}

/**
 * Check if a given object implements the SignoutResponse interface.
 */
export function instanceOfSignoutResponse(value: object): value is SignoutResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SignoutResponseFromJSON(json: any): SignoutResponse {
    return SignoutResponseFromJSONTyped(json, false);
}

export function SignoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function SignoutResponseToJSON(json: any): SignoutResponse {
    return SignoutResponseToJSONTyped(json, false);
}

export function SignoutResponseToJSONTyped(value?: SignoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

