/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagDeleteDependencyCounts
 */
export interface TagDeleteDependencyCounts {
    /**
     * 
     * @type {number}
     * @memberof TagDeleteDependencyCounts
     */
    transactions: number;
    /**
     * 
     * @type {number}
     * @memberof TagDeleteDependencyCounts
     */
    transactionRules: number;
}

/**
 * Check if a given object implements the TagDeleteDependencyCounts interface.
 */
export function instanceOfTagDeleteDependencyCounts(value: object): value is TagDeleteDependencyCounts {
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('transactionRules' in value) || value['transactionRules'] === undefined) return false;
    return true;
}

export function TagDeleteDependencyCountsFromJSON(json: any): TagDeleteDependencyCounts {
    return TagDeleteDependencyCountsFromJSONTyped(json, false);
}

export function TagDeleteDependencyCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagDeleteDependencyCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': json['transactions'],
        'transactionRules': json['transaction_rules'],
    };
}

export function TagDeleteDependencyCountsToJSON(json: any): TagDeleteDependencyCounts {
    return TagDeleteDependencyCountsToJSONTyped(json, false);
}

export function TagDeleteDependencyCountsToJSONTyped(value?: TagDeleteDependencyCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactions': value['transactions'],
        'transaction_rules': value['transactionRules'],
    };
}

