/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagDeleteDependencyCounts } from './TagDeleteDependencyCounts';
import {
    TagDeleteDependencyCountsFromJSON,
    TagDeleteDependencyCountsFromJSONTyped,
    TagDeleteDependencyCountsToJSON,
    TagDeleteDependencyCountsToJSONTyped,
} from './TagDeleteDependencyCounts';

/**
 * 
 * @export
 * @interface TagDeleteImpact
 */
export interface TagDeleteImpact {
    tagId: string;
    mode: TagDeleteImpactModeEnum;
    canDelete: boolean;
    dependencyCounts: TagDeleteDependencyCounts;
    blockingReasons: Array<TagDeleteImpactBlockingReasonsEnum>;
}

export const TagDeleteImpactModeEnum = {
    Block: 'block'
} as const;
export type TagDeleteImpactModeEnum = typeof TagDeleteImpactModeEnum[keyof typeof TagDeleteImpactModeEnum];
export const TagDeleteImpactBlockingReasonsEnum = {
    Transactions: 'transactions',
    TransactionRules: 'transaction_rules'
} as const;
export type TagDeleteImpactBlockingReasonsEnum = typeof TagDeleteImpactBlockingReasonsEnum[keyof typeof TagDeleteImpactBlockingReasonsEnum];

export function instanceOfTagDeleteImpact(value: object): value is TagDeleteImpact {
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('canDelete' in value) || value['canDelete'] === undefined) return false;
    if (!('dependencyCounts' in value) || value['dependencyCounts'] === undefined) return false;
    if (!('blockingReasons' in value) || value['blockingReasons'] === undefined) return false;
    return true;
}

export function TagDeleteImpactFromJSON(json: any): TagDeleteImpact {
    return TagDeleteImpactFromJSONTyped(json, false);
}

export function TagDeleteImpactFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagDeleteImpact {
    if (json == null) {
        return json;
    }
    return {
        'tagId': json['tag_id'],
        'mode': json['mode'],
        'canDelete': json['can_delete'],
        'dependencyCounts': TagDeleteDependencyCountsFromJSON(json['dependency_counts']),
        'blockingReasons': json['blocking_reasons'],
    };
}

export function TagDeleteImpactToJSON(json: any): TagDeleteImpact {
    return TagDeleteImpactToJSONTyped(json, false);
}

export function TagDeleteImpactToJSONTyped(value?: TagDeleteImpact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'tag_id': value['tagId'],
        'mode': value['mode'],
        'can_delete': value['canDelete'],
        'dependency_counts': TagDeleteDependencyCountsToJSON(value['dependencyCounts']),
        'blocking_reasons': value['blockingReasons'],
    };
}
