/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransactionRuleAddTagsAction } from './TransactionRuleAddTagsAction';
import {
    instanceOfTransactionRuleAddTagsAction,
    TransactionRuleAddTagsActionFromJSON,
    TransactionRuleAddTagsActionFromJSONTyped,
    TransactionRuleAddTagsActionToJSON,
} from './TransactionRuleAddTagsAction';
import type { TransactionRuleClearCategoryAction } from './TransactionRuleClearCategoryAction';
import {
    instanceOfTransactionRuleClearCategoryAction,
    TransactionRuleClearCategoryActionFromJSON,
    TransactionRuleClearCategoryActionFromJSONTyped,
    TransactionRuleClearCategoryActionToJSON,
} from './TransactionRuleClearCategoryAction';
import type { TransactionRuleRemoveTagsAction } from './TransactionRuleRemoveTagsAction';
import {
    instanceOfTransactionRuleRemoveTagsAction,
    TransactionRuleRemoveTagsActionFromJSON,
    TransactionRuleRemoveTagsActionFromJSONTyped,
    TransactionRuleRemoveTagsActionToJSON,
} from './TransactionRuleRemoveTagsAction';
import type { TransactionRuleReplaceTagsAction } from './TransactionRuleReplaceTagsAction';
import {
    instanceOfTransactionRuleReplaceTagsAction,
    TransactionRuleReplaceTagsActionFromJSON,
    TransactionRuleReplaceTagsActionFromJSONTyped,
    TransactionRuleReplaceTagsActionToJSON,
} from './TransactionRuleReplaceTagsAction';
import type { TransactionRuleSetCategoryAction } from './TransactionRuleSetCategoryAction';
import {
    instanceOfTransactionRuleSetCategoryAction,
    TransactionRuleSetCategoryActionFromJSON,
    TransactionRuleSetCategoryActionFromJSONTyped,
    TransactionRuleSetCategoryActionToJSON,
} from './TransactionRuleSetCategoryAction';

/**
 * @type TransactionRuleAction
 * 
 * @export
 */
export type TransactionRuleAction = TransactionRuleAddTagsAction | TransactionRuleClearCategoryAction | TransactionRuleRemoveTagsAction | TransactionRuleReplaceTagsAction | TransactionRuleSetCategoryAction;

export function TransactionRuleActionFromJSON(json: any): TransactionRuleAction {
    return TransactionRuleActionFromJSONTyped(json, false);
}

export function TransactionRuleActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleAction {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfTransactionRuleAddTagsAction(json)) {
        return TransactionRuleAddTagsActionFromJSONTyped(json, true);
    }
    if (instanceOfTransactionRuleClearCategoryAction(json)) {
        return TransactionRuleClearCategoryActionFromJSONTyped(json, true);
    }
    if (instanceOfTransactionRuleRemoveTagsAction(json)) {
        return TransactionRuleRemoveTagsActionFromJSONTyped(json, true);
    }
    if (instanceOfTransactionRuleReplaceTagsAction(json)) {
        return TransactionRuleReplaceTagsActionFromJSONTyped(json, true);
    }
    if (instanceOfTransactionRuleSetCategoryAction(json)) {
        return TransactionRuleSetCategoryActionFromJSONTyped(json, true);
    }
    return {} as any;
}

export function TransactionRuleActionToJSON(json: any): any {
    return TransactionRuleActionToJSONTyped(json, false);
}

export function TransactionRuleActionToJSONTyped(value?: TransactionRuleAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfTransactionRuleAddTagsAction(value)) {
        return TransactionRuleAddTagsActionToJSON(value as TransactionRuleAddTagsAction);
    }
    if (instanceOfTransactionRuleClearCategoryAction(value)) {
        return TransactionRuleClearCategoryActionToJSON(value as TransactionRuleClearCategoryAction);
    }
    if (instanceOfTransactionRuleRemoveTagsAction(value)) {
        return TransactionRuleRemoveTagsActionToJSON(value as TransactionRuleRemoveTagsAction);
    }
    if (instanceOfTransactionRuleReplaceTagsAction(value)) {
        return TransactionRuleReplaceTagsActionToJSON(value as TransactionRuleReplaceTagsAction);
    }
    if (instanceOfTransactionRuleSetCategoryAction(value)) {
        return TransactionRuleSetCategoryActionToJSON(value as TransactionRuleSetCategoryAction);
    }
    return {};
}

