/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransactionRuleAddTagsActionInputOneOf } from './TransactionRuleAddTagsActionInputOneOf';
import {
    instanceOfTransactionRuleAddTagsActionInputOneOf,
    TransactionRuleAddTagsActionInputOneOfFromJSON,
    TransactionRuleAddTagsActionInputOneOfFromJSONTyped,
    TransactionRuleAddTagsActionInputOneOfToJSON,
} from './TransactionRuleAddTagsActionInputOneOf';
import type { TransactionRuleAddTagsActionInputOneOf1 } from './TransactionRuleAddTagsActionInputOneOf1';
import {
    instanceOfTransactionRuleAddTagsActionInputOneOf1,
    TransactionRuleAddTagsActionInputOneOf1FromJSON,
    TransactionRuleAddTagsActionInputOneOf1FromJSONTyped,
    TransactionRuleAddTagsActionInputOneOf1ToJSON,
} from './TransactionRuleAddTagsActionInputOneOf1';

/**
 * @type TransactionRuleReplaceTagsActionInput
 * 
 * @export
 */
export type TransactionRuleReplaceTagsActionInput = TransactionRuleAddTagsActionInputOneOf | TransactionRuleAddTagsActionInputOneOf1;


/**
 * Check if a given object implements the TransactionRuleReplaceTagsActionInput interface.
 */
export function instanceOfTransactionRuleReplaceTagsActionInput(value: object): value is TransactionRuleReplaceTagsActionInput {
    return instanceOfTransactionRuleAddTagsActionInputOneOf(value) || instanceOfTransactionRuleAddTagsActionInputOneOf1(value);
}

export function TransactionRuleReplaceTagsActionInputFromJSON(json: any): TransactionRuleReplaceTagsActionInput {
    return TransactionRuleReplaceTagsActionInputFromJSONTyped(json, false);
}

export function TransactionRuleReplaceTagsActionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleReplaceTagsActionInput {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfTransactionRuleAddTagsActionInputOneOf(json)) {
        return TransactionRuleAddTagsActionInputOneOfFromJSONTyped(json, true);
    }
    if (instanceOfTransactionRuleAddTagsActionInputOneOf1(json)) {
        return TransactionRuleAddTagsActionInputOneOf1FromJSONTyped(json, true);
    }
    return {} as any;
}

export function TransactionRuleReplaceTagsActionInputToJSON(json: any): any {
    return TransactionRuleReplaceTagsActionInputToJSONTyped(json, false);
}

export function TransactionRuleReplaceTagsActionInputToJSONTyped(value?: TransactionRuleReplaceTagsActionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfTransactionRuleAddTagsActionInputOneOf(value)) {
        return TransactionRuleAddTagsActionInputOneOfToJSON(value as TransactionRuleAddTagsActionInputOneOf);
    }
    if (instanceOfTransactionRuleAddTagsActionInputOneOf1(value)) {
        return TransactionRuleAddTagsActionInputOneOf1ToJSON(value as TransactionRuleAddTagsActionInputOneOf1);
    }
    return {};
}

