/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionTagsReplaceRequest
 */
export interface TransactionTagsReplaceRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionTagsReplaceRequest
     */
    tagIds: Array<string>;
}

/**
 * Check if a given object implements the TransactionTagsReplaceRequest interface.
 */
export function instanceOfTransactionTagsReplaceRequest(value: object): value is TransactionTagsReplaceRequest {
    if (!('tagIds' in value) || value['tagIds'] === undefined) return false;
    return true;
}

export function TransactionTagsReplaceRequestFromJSON(json: any): TransactionTagsReplaceRequest {
    return TransactionTagsReplaceRequestFromJSONTyped(json, false);
}

export function TransactionTagsReplaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionTagsReplaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tagIds': json['tag_ids'],
    };
}

export function TransactionTagsReplaceRequestToJSON(json: any): TransactionTagsReplaceRequest {
    return TransactionTagsReplaceRequestToJSONTyped(json, false);
}

export function TransactionTagsReplaceRequestToJSONTyped(value?: TransactionTagsReplaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag_ids': value['tagIds'],
    };
}

