/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransactionExportFormat = {
    Csv: 'csv',
    Json: 'json'
} as const;
export type TransactionExportFormat = typeof TransactionExportFormat[keyof typeof TransactionExportFormat];


export function instanceOfTransactionExportFormat(value: any): boolean {
    for (const key in TransactionExportFormat) {
        if (Object.prototype.hasOwnProperty.call(TransactionExportFormat, key)) {
            if (TransactionExportFormat[key as keyof typeof TransactionExportFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransactionExportFormatFromJSON(json: any): TransactionExportFormat {
    return TransactionExportFormatFromJSONTyped(json, false);
}

export function TransactionExportFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionExportFormat {
    return json as TransactionExportFormat;
}

export function TransactionExportFormatToJSON(value?: TransactionExportFormat | null): any {
    return value as any;
}

export function TransactionExportFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionExportFormat {
    return value as TransactionExportFormat;
}

