/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionRuleBooleanField } from './TransactionRuleBooleanField';
import {
    TransactionRuleBooleanFieldFromJSON,
    TransactionRuleBooleanFieldFromJSONTyped,
    TransactionRuleBooleanFieldToJSON,
    TransactionRuleBooleanFieldToJSONTyped,
} from './TransactionRuleBooleanField';

/**
 * 
 * @export
 * @interface TransactionRuleBooleanScalarPredicate
 */
export interface TransactionRuleBooleanScalarPredicate {
    /**
     * 
     * @type {TransactionRuleBooleanField}
     * @memberof TransactionRuleBooleanScalarPredicate
     */
    field: TransactionRuleBooleanField;
    /**
     * 
     * @type {TransactionRuleBooleanScalarPredicateOperatorEnum}
     * @memberof TransactionRuleBooleanScalarPredicate
     */
    operator: TransactionRuleBooleanScalarPredicateOperatorEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionRuleBooleanScalarPredicate
     */
    value: boolean;
}


/**
 * @export
 */
export const TransactionRuleBooleanScalarPredicateOperatorEnum = {
    Equals: 'equals',
    NotEquals: 'not_equals'
} as const;
export type TransactionRuleBooleanScalarPredicateOperatorEnum = typeof TransactionRuleBooleanScalarPredicateOperatorEnum[keyof typeof TransactionRuleBooleanScalarPredicateOperatorEnum];


/**
 * Check if a given object implements the TransactionRuleBooleanScalarPredicate interface.
 */
export function instanceOfTransactionRuleBooleanScalarPredicate(value: object): value is TransactionRuleBooleanScalarPredicate {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('operator' in value) || value['operator'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TransactionRuleBooleanScalarPredicateFromJSON(json: any): TransactionRuleBooleanScalarPredicate {
    return TransactionRuleBooleanScalarPredicateFromJSONTyped(json, false);
}

export function TransactionRuleBooleanScalarPredicateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleBooleanScalarPredicate {
    if (json == null) {
        return json;
    }
    return {
        
        'field': TransactionRuleBooleanFieldFromJSON(json['field']),
        'operator': json['operator'],
        'value': json['value'],
    };
}

export function TransactionRuleBooleanScalarPredicateToJSON(json: any): TransactionRuleBooleanScalarPredicate {
    return TransactionRuleBooleanScalarPredicateToJSONTyped(json, false);
}

export function TransactionRuleBooleanScalarPredicateToJSONTyped(value?: TransactionRuleBooleanScalarPredicate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': TransactionRuleBooleanFieldToJSON(value['field']),
        'operator': value['operator'],
        'value': value['value'],
    };
}

