/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionSpendingByDayPoint } from './TransactionSpendingByDayPoint';
import {
    TransactionSpendingByDayPointFromJSON,
    TransactionSpendingByDayPointFromJSONTyped,
    TransactionSpendingByDayPointToJSON,
    TransactionSpendingByDayPointToJSONTyped,
} from './TransactionSpendingByDayPoint';
import type { TransactionSpendingByCategoryPoint } from './TransactionSpendingByCategoryPoint';
import {
    TransactionSpendingByCategoryPointFromJSON,
    TransactionSpendingByCategoryPointFromJSONTyped,
    TransactionSpendingByCategoryPointToJSON,
    TransactionSpendingByCategoryPointToJSONTyped,
} from './TransactionSpendingByCategoryPoint';

/**
 * 
 * @export
 * @interface TransactionAggregateResponse
 */
export interface TransactionAggregateResponse {
    /**
     * 
     * @type {number}
     * @memberof TransactionAggregateResponse
     */
    totalSpent: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionAggregateResponse
     */
    income: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionAggregateResponse
     */
    netFlow: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionAggregateResponse
     */
    pendingCount: number;
    /**
     * 
     * @type {Array<TransactionSpendingByCategoryPoint>}
     * @memberof TransactionAggregateResponse
     */
    spendingByCategory: Array<TransactionSpendingByCategoryPoint>;
    /**
     * 
     * @type {Array<TransactionSpendingByDayPoint>}
     * @memberof TransactionAggregateResponse
     */
    spendingByDay: Array<TransactionSpendingByDayPoint>;
}

/**
 * Check if a given object implements the TransactionAggregateResponse interface.
 */
export function instanceOfTransactionAggregateResponse(value: object): value is TransactionAggregateResponse {
    if (!('totalSpent' in value) || value['totalSpent'] === undefined) return false;
    if (!('income' in value) || value['income'] === undefined) return false;
    if (!('netFlow' in value) || value['netFlow'] === undefined) return false;
    if (!('pendingCount' in value) || value['pendingCount'] === undefined) return false;
    if (!('spendingByCategory' in value) || value['spendingByCategory'] === undefined) return false;
    if (!('spendingByDay' in value) || value['spendingByDay'] === undefined) return false;
    return true;
}

export function TransactionAggregateResponseFromJSON(json: any): TransactionAggregateResponse {
    return TransactionAggregateResponseFromJSONTyped(json, false);
}

export function TransactionAggregateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionAggregateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalSpent': json['total_spent'],
        'income': json['income'],
        'netFlow': json['net_flow'],
        'pendingCount': json['pending_count'],
        'spendingByCategory': ((json['spending_by_category'] as Array<any>).map(TransactionSpendingByCategoryPointFromJSON)),
        'spendingByDay': ((json['spending_by_day'] as Array<any>).map(TransactionSpendingByDayPointFromJSON)),
    };
}

export function TransactionAggregateResponseToJSON(json: any): TransactionAggregateResponse {
    return TransactionAggregateResponseToJSONTyped(json, false);
}

export function TransactionAggregateResponseToJSONTyped(value?: TransactionAggregateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_spent': value['totalSpent'],
        'income': value['income'],
        'net_flow': value['netFlow'],
        'pending_count': value['pendingCount'],
        'spending_by_category': ((value['spendingByCategory'] as Array<any>).map(TransactionSpendingByCategoryPointToJSON)),
        'spending_by_day': ((value['spendingByDay'] as Array<any>).map(TransactionSpendingByDayPointToJSON)),
    };
}

