/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 */
export const TransactionRuleActionType = {
    SetCategory: 'set_category',
    ClearCategory: 'clear_category',
    AddTags: 'add_tags',
    RemoveTags: 'remove_tags',
    ReplaceTags: 'replace_tags'
} as const;
export type TransactionRuleActionType = typeof TransactionRuleActionType[keyof typeof TransactionRuleActionType];

export function TransactionRuleActionTypeFromJSON(json: any): TransactionRuleActionType {
    return TransactionRuleActionTypeFromJSONTyped(json, false);
}

export function TransactionRuleActionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleActionType {
    return json as TransactionRuleActionType;
}

export function TransactionRuleActionTypeToJSON(value?: TransactionRuleActionType | null): any {
    return value as any;
}

export function TransactionRuleActionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionRuleActionType {
    return value as TransactionRuleActionType;
}
