/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionRuleTestApplyFilter
 */
export interface TransactionRuleTestApplyFilter {
    /**
     * User-owned account IDs to evaluate. Required to keep previews bounded and scoped.
     * @type {Array<string>}
     * @memberof TransactionRuleTestApplyFilter
     */
    accountIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TransactionRuleTestApplyFilter
     */
    q?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionRuleTestApplyFilter
     */
    pending?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TransactionRuleTestApplyFilter
     */
    dateFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransactionRuleTestApplyFilter
     */
    dateTo?: Date;
    /**
     * 
     * @type {number}
     * @memberof TransactionRuleTestApplyFilter
     */
    amountMin?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionRuleTestApplyFilter
     */
    amountMax?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionRuleTestApplyFilter
     */
    categoryId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionRuleTestApplyFilter
     */
    tagIds?: Array<string>;
    /**
     * 
     * @type {TransactionRuleTestApplyFilterTagModeEnum}
     * @memberof TransactionRuleTestApplyFilter
     */
    tagMode?: TransactionRuleTestApplyFilterTagModeEnum;
}


/**
 * @export
 */
export const TransactionRuleTestApplyFilterTagModeEnum = {
    Any: 'any',
    All: 'all'
} as const;
export type TransactionRuleTestApplyFilterTagModeEnum = typeof TransactionRuleTestApplyFilterTagModeEnum[keyof typeof TransactionRuleTestApplyFilterTagModeEnum];


/**
 * Check if a given object implements the TransactionRuleTestApplyFilter interface.
 */
export function instanceOfTransactionRuleTestApplyFilter(value: object): value is TransactionRuleTestApplyFilter {
    if (!('accountIds' in value) || value['accountIds'] === undefined) return false;
    return true;
}

export function TransactionRuleTestApplyFilterFromJSON(json: any): TransactionRuleTestApplyFilter {
    return TransactionRuleTestApplyFilterFromJSONTyped(json, false);
}

export function TransactionRuleTestApplyFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleTestApplyFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIds': json['account_ids'],
        'q': json['q'] == null ? undefined : json['q'],
        'pending': json['pending'] == null ? undefined : json['pending'],
        'dateFrom': json['date_from'] == null ? undefined : (new Date(json['date_from'])),
        'dateTo': json['date_to'] == null ? undefined : (new Date(json['date_to'])),
        'amountMin': json['amount_min'] == null ? undefined : json['amount_min'],
        'amountMax': json['amount_max'] == null ? undefined : json['amount_max'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'tagIds': json['tag_ids'] == null ? undefined : json['tag_ids'],
        'tagMode': json['tag_mode'] == null ? undefined : json['tag_mode'],
    };
}

export function TransactionRuleTestApplyFilterToJSON(json: any): TransactionRuleTestApplyFilter {
    return TransactionRuleTestApplyFilterToJSONTyped(json, false);
}

export function TransactionRuleTestApplyFilterToJSONTyped(value?: TransactionRuleTestApplyFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_ids': value['accountIds'],
        'q': value['q'],
        'pending': value['pending'],
        'date_from': value['dateFrom'] == null ? value['dateFrom'] : value['dateFrom'].toISOString(),
        'date_to': value['dateTo'] == null ? value['dateTo'] : value['dateTo'].toISOString(),
        'amount_min': value['amountMin'],
        'amount_max': value['amountMax'],
        'category_id': value['categoryId'],
        'tag_ids': value['tagIds'],
        'tag_mode': value['tagMode'],
    };
}

