/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionRuleActionType } from './TransactionRuleActionType';
import {
    TransactionRuleActionTypeFromJSON,
    TransactionRuleActionTypeFromJSONTyped,
    TransactionRuleActionTypeToJSON,
    TransactionRuleActionTypeToJSONTyped,
} from './TransactionRuleActionType';

/**
 * Transaction rule action input. Server validation applies action-specific requirements: set_category requires exactly one of category_id or category_name; clear_category does not accept category or tag references; add_tags and remove_tags require at least one tag reference; replace_tags accepts the provided tag references and may be empty to clear all tags.
 * 
 * @export
 * @interface TransactionRuleActionInput
 */
export interface TransactionRuleActionInput {
    /**
     * 
     * @type {TransactionRuleActionType}
     * @memberof TransactionRuleActionInput
     */
    type: TransactionRuleActionType;
    /**
     * 
     * @type {string}
     * @memberof TransactionRuleActionInput
     */
    categoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionRuleActionInput
     */
    categoryName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionRuleActionInput
     */
    tagIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionRuleActionInput
     */
    tagNames?: Array<string>;
}



/**
 * Check if a given object implements the TransactionRuleActionInput interface.
 */
export function instanceOfTransactionRuleActionInput(value: object): value is TransactionRuleActionInput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TransactionRuleActionInputFromJSON(json: any): TransactionRuleActionInput {
    return TransactionRuleActionInputFromJSONTyped(json, false);
}

export function TransactionRuleActionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleActionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'type': TransactionRuleActionTypeFromJSON(json['type']),
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'categoryName': json['category_name'] == null ? undefined : json['category_name'],
        'tagIds': json['tag_ids'] == null ? undefined : json['tag_ids'],
        'tagNames': json['tag_names'] == null ? undefined : json['tag_names'],
    };
}

export function TransactionRuleActionInputToJSON(json: any): TransactionRuleActionInput {
    return TransactionRuleActionInputToJSONTyped(json, false);
}

export function TransactionRuleActionInputToJSONTyped(value?: TransactionRuleActionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': TransactionRuleActionTypeToJSON(value['type']),
        'category_id': value['categoryId'],
        'category_name': value['categoryName'],
        'tag_ids': value['tagIds'],
        'tag_names': value['tagNames'],
    };
}

