/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionRuleConditionGroup } from './TransactionRuleConditionGroup';
import {
    TransactionRuleConditionGroupFromJSON,
    TransactionRuleConditionGroupFromJSONTyped,
    TransactionRuleConditionGroupToJSON,
    TransactionRuleConditionGroupToJSONTyped,
} from './TransactionRuleConditionGroup';

/**
 * 
 * @export
 * @interface TransactionRuleGroupNode
 */
export interface TransactionRuleGroupNode {
    /**
     * 
     * @type {any}
     * @memberof TransactionRuleGroupNode
     */
    kind: any | null;
    /**
     * 
     * @type {TransactionRuleConditionGroup}
     * @memberof TransactionRuleGroupNode
     */
    group: TransactionRuleConditionGroup;
}

/**
 * Check if a given object implements the TransactionRuleGroupNode interface.
 */
export function instanceOfTransactionRuleGroupNode(value: object): value is TransactionRuleGroupNode {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    return true;
}

export function TransactionRuleGroupNodeFromJSON(json: any): TransactionRuleGroupNode {
    return TransactionRuleGroupNodeFromJSONTyped(json, false);
}

export function TransactionRuleGroupNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleGroupNode {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'group': TransactionRuleConditionGroupFromJSON(json['group']),
    };
}

export function TransactionRuleGroupNodeToJSON(json: any): TransactionRuleGroupNode {
    return TransactionRuleGroupNodeToJSONTyped(json, false);
}

export function TransactionRuleGroupNodeToJSONTyped(value?: TransactionRuleGroupNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'group': TransactionRuleConditionGroupToJSON(value['group']),
    };
}

