/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionPaymentChannel } from './TransactionPaymentChannel';
import {
    TransactionPaymentChannelFromJSON,
    TransactionPaymentChannelFromJSONTyped,
    TransactionPaymentChannelToJSON,
    TransactionPaymentChannelToJSONTyped,
} from './TransactionPaymentChannel';

/**
 * 
 * @export
 * @interface TransactionPatchRequest
 */
export interface TransactionPatchRequest {
    /**
     * 
     * @type {Date}
     * @memberof TransactionPatchRequest
     */
    datePosted?: Date;
    /**
     * 
     * @type {string}
     * @memberof TransactionPatchRequest
     */
    originalDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionPatchRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionPatchRequest
     */
    amount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionPatchRequest
     */
    pending?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransactionPatchRequest
     */
    isoCurrencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionPatchRequest
     */
    unofficialCurrencyCode?: string;
    /**
     * 
     * @type {TransactionPaymentChannel}
     * @memberof TransactionPatchRequest
     */
    paymentChannel?: TransactionPaymentChannel;
    /**
     * 
     * @type {string}
     * @memberof TransactionPatchRequest
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionPatchRequest
     */
    categoryId?: string | null;
}



/**
 * Check if a given object implements the TransactionPatchRequest interface.
 */
export function instanceOfTransactionPatchRequest(value: object): value is TransactionPatchRequest {
    return true;
}

export function TransactionPatchRequestFromJSON(json: any): TransactionPatchRequest {
    return TransactionPatchRequestFromJSONTyped(json, false);
}

export function TransactionPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'datePosted': json['date_posted'] == null ? undefined : (new Date(json['date_posted'])),
        'originalDescription': json['original_description'] == null ? undefined : json['original_description'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'pending': json['pending'] == null ? undefined : json['pending'],
        'isoCurrencyCode': json['iso_currency_code'] == null ? undefined : json['iso_currency_code'],
        'unofficialCurrencyCode': json['unofficial_currency_code'] == null ? undefined : json['unofficial_currency_code'],
        'paymentChannel': json['payment_channel'] == null ? undefined : TransactionPaymentChannelFromJSON(json['payment_channel']),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
    };
}

export function TransactionPatchRequestToJSON(json: any): TransactionPatchRequest {
    return TransactionPatchRequestToJSONTyped(json, false);
}

export function TransactionPatchRequestToJSONTyped(value?: TransactionPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date_posted': value['datePosted'] == null ? value['datePosted'] : value['datePosted'].toISOString(),
        'original_description': value['originalDescription'],
        'description': value['description'],
        'amount': value['amount'],
        'pending': value['pending'],
        'iso_currency_code': value['isoCurrencyCode'],
        'unofficial_currency_code': value['unofficialCurrencyCode'],
        'payment_channel': TransactionPaymentChannelToJSON(value['paymentChannel']),
        'notes': value['notes'],
        'category_id': value['categoryId'],
    };
}

