/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransactionRuleSourceScope = {
    All: 'all',
    Manual: 'manual',
    Import: 'import'
} as const;
export type TransactionRuleSourceScope = typeof TransactionRuleSourceScope[keyof typeof TransactionRuleSourceScope];


export function instanceOfTransactionRuleSourceScope(value: any): boolean {
    for (const key in TransactionRuleSourceScope) {
        if (Object.prototype.hasOwnProperty.call(TransactionRuleSourceScope, key)) {
            if (TransactionRuleSourceScope[key as keyof typeof TransactionRuleSourceScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransactionRuleSourceScopeFromJSON(json: any): TransactionRuleSourceScope {
    return TransactionRuleSourceScopeFromJSONTyped(json, false);
}

export function TransactionRuleSourceScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleSourceScope {
    return json as TransactionRuleSourceScope;
}

export function TransactionRuleSourceScopeToJSON(value?: TransactionRuleSourceScope | null): any {
    return value as any;
}

export function TransactionRuleSourceScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionRuleSourceScope {
    return value as TransactionRuleSourceScope;
}

