/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionRulePredicate } from './TransactionRulePredicate';
import {
    TransactionRulePredicateFromJSON,
    TransactionRulePredicateFromJSONTyped,
    TransactionRulePredicateToJSON,
    TransactionRulePredicateToJSONTyped,
} from './TransactionRulePredicate';

/**
 * 
 * @export
 * @interface TransactionRulePredicateNode
 */
export interface TransactionRulePredicateNode {
    /**
     * 
     * @type {any}
     * @memberof TransactionRulePredicateNode
     */
    kind: any | null;
    /**
     * 
     * @type {TransactionRulePredicate}
     * @memberof TransactionRulePredicateNode
     */
    predicate: TransactionRulePredicate;
}

/**
 * Check if a given object implements the TransactionRulePredicateNode interface.
 */
export function instanceOfTransactionRulePredicateNode(value: object): value is TransactionRulePredicateNode {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('predicate' in value) || value['predicate'] === undefined) return false;
    return true;
}

export function TransactionRulePredicateNodeFromJSON(json: any): TransactionRulePredicateNode {
    return TransactionRulePredicateNodeFromJSONTyped(json, false);
}

export function TransactionRulePredicateNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRulePredicateNode {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'predicate': TransactionRulePredicateFromJSON(json['predicate']),
    };
}

export function TransactionRulePredicateNodeToJSON(json: any): TransactionRulePredicateNode {
    return TransactionRulePredicateNodeToJSONTyped(json, false);
}

export function TransactionRulePredicateNodeToJSONTyped(value?: TransactionRulePredicateNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'predicate': TransactionRulePredicateToJSON(value['predicate']),
    };
}

