/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionExportStatus } from './TransactionExportStatus';
import {
    TransactionExportStatusFromJSON,
    TransactionExportStatusFromJSONTyped,
    TransactionExportStatusToJSON,
    TransactionExportStatusToJSONTyped,
} from './TransactionExportStatus';
import type { TransactionExportFormat } from './TransactionExportFormat';
import {
    TransactionExportFormatFromJSON,
    TransactionExportFormatFromJSONTyped,
    TransactionExportFormatToJSON,
    TransactionExportFormatToJSONTyped,
} from './TransactionExportFormat';

/**
 * 
 * @export
 * @interface TransactionExportJob
 */
export interface TransactionExportJob {
    /**
     * 
     * @type {string}
     * @memberof TransactionExportJob
     */
    id: string;
    /**
     * 
     * @type {TransactionExportJobTypeEnum}
     * @memberof TransactionExportJob
     */
    type: TransactionExportJobTypeEnum;
    /**
     * 
     * @type {TransactionExportFormat}
     * @memberof TransactionExportJob
     */
    format: TransactionExportFormat;
    /**
     * 
     * @type {TransactionExportStatus}
     * @memberof TransactionExportJob
     */
    status: TransactionExportStatus;
    /**
     * 
     * @type {Date}
     * @memberof TransactionExportJob
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransactionExportJob
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TransactionExportJob
     */
    expiresAt: Date;
    /**
     * 
     * @type {number}
     * @memberof TransactionExportJob
     */
    rowCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionExportJob
     */
    error?: string | null;
}


/**
 * @export
 */
export const TransactionExportJobTypeEnum = {
    Transactions: 'transactions'
} as const;
export type TransactionExportJobTypeEnum = typeof TransactionExportJobTypeEnum[keyof typeof TransactionExportJobTypeEnum];


/**
 * Check if a given object implements the TransactionExportJob interface.
 */
export function instanceOfTransactionExportJob(value: object): value is TransactionExportJob {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function TransactionExportJobFromJSON(json: any): TransactionExportJob {
    return TransactionExportJobFromJSONTyped(json, false);
}

export function TransactionExportJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionExportJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'format': TransactionExportFormatFromJSON(json['format']),
        'status': TransactionExportStatusFromJSON(json['status']),
        'createdAt': (new Date(json['created_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'expiresAt': (new Date(json['expires_at'])),
        'rowCount': json['row_count'] == null ? undefined : json['row_count'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function TransactionExportJobToJSON(json: any): TransactionExportJob {
    return TransactionExportJobToJSONTyped(json, false);
}

export function TransactionExportJobToJSONTyped(value?: TransactionExportJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'format': TransactionExportFormatToJSON(value['format']),
        'status': TransactionExportStatusToJSON(value['status']),
        'created_at': value['createdAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'expires_at': value['expiresAt'].toISOString(),
        'row_count': value['rowCount'],
        'error': value['error'],
    };
}

