/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionRuleAddTagsActionInputOneOf
 */
export interface TransactionRuleAddTagsActionInputOneOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionRuleAddTagsActionInputOneOf
     */
    tagIds: Array<string>;
}

/**
 * Check if a given object implements the TransactionRuleAddTagsActionInputOneOf interface.
 */
export function instanceOfTransactionRuleAddTagsActionInputOneOf(value: object): value is TransactionRuleAddTagsActionInputOneOf {
    if (!('tagIds' in value) || value['tagIds'] === undefined) return false;
    return true;
}

export function TransactionRuleAddTagsActionInputOneOfFromJSON(json: any): TransactionRuleAddTagsActionInputOneOf {
    return TransactionRuleAddTagsActionInputOneOfFromJSONTyped(json, false);
}

export function TransactionRuleAddTagsActionInputOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleAddTagsActionInputOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'tagIds': json['tag_ids'],
    };
}

export function TransactionRuleAddTagsActionInputOneOfToJSON(json: any): TransactionRuleAddTagsActionInputOneOf {
    return TransactionRuleAddTagsActionInputOneOfToJSONTyped(json, false);
}

export function TransactionRuleAddTagsActionInputOneOfToJSONTyped(value?: TransactionRuleAddTagsActionInputOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag_ids': value['tagIds'],
    };
}

