/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionRuleSetCategoryAction
 */
export interface TransactionRuleSetCategoryAction {
    /**
     * 
     * @type {any}
     * @memberof TransactionRuleSetCategoryAction
     */
    type: any | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionRuleSetCategoryAction
     */
    categoryId: string;
}

/**
 * Check if a given object implements the TransactionRuleSetCategoryAction interface.
 */
export function instanceOfTransactionRuleSetCategoryAction(value: object): value is TransactionRuleSetCategoryAction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    return true;
}

export function TransactionRuleSetCategoryActionFromJSON(json: any): TransactionRuleSetCategoryAction {
    return TransactionRuleSetCategoryActionFromJSONTyped(json, false);
}

export function TransactionRuleSetCategoryActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRuleSetCategoryAction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'categoryId': json['category_id'],
    };
}

export function TransactionRuleSetCategoryActionToJSON(json: any): TransactionRuleSetCategoryAction {
    return TransactionRuleSetCategoryActionToJSONTyped(json, false);
}

export function TransactionRuleSetCategoryActionToJSONTyped(value?: TransactionRuleSetCategoryAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'category_id': value['categoryId'],
    };
}

