/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
    TransactionToJSONTyped,
} from './Transaction';

/**
 * 
 * @export
 * @interface TransactionListResponse
 */
export interface TransactionListResponse {
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof TransactionListResponse
     */
    items: Array<Transaction>;
    /**
     * 
     * @type {number}
     * @memberof TransactionListResponse
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionListResponse
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the TransactionListResponse interface.
 */
export function instanceOfTransactionListResponse(value: object): value is TransactionListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function TransactionListResponseFromJSON(json: any): TransactionListResponse {
    return TransactionListResponseFromJSONTyped(json, false);
}

export function TransactionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TransactionFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function TransactionListResponseToJSON(json: any): TransactionListResponse {
    return TransactionListResponseToJSONTyped(json, false);
}

export function TransactionListResponseToJSONTyped(value?: TransactionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TransactionToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

