/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionInsightsSummary
 */
export interface TransactionInsightsSummary {
    /**
     * 
     * @type {number}
     * @memberof TransactionInsightsSummary
     */
    planned: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionInsightsSummary
     */
    spent: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionInsightsSummary
     */
    remaining: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionInsightsSummary
     */
    income: number;
}

/**
 * Check if a given object implements the TransactionInsightsSummary interface.
 */
export function instanceOfTransactionInsightsSummary(value: object): value is TransactionInsightsSummary {
    if (!('planned' in value) || value['planned'] === undefined) return false;
    if (!('spent' in value) || value['spent'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    if (!('income' in value) || value['income'] === undefined) return false;
    return true;
}

export function TransactionInsightsSummaryFromJSON(json: any): TransactionInsightsSummary {
    return TransactionInsightsSummaryFromJSONTyped(json, false);
}

export function TransactionInsightsSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionInsightsSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'planned': json['planned'],
        'spent': json['spent'],
        'remaining': json['remaining'],
        'income': json['income'],
    };
}

export function TransactionInsightsSummaryToJSON(json: any): TransactionInsightsSummary {
    return TransactionInsightsSummaryToJSONTyped(json, false);
}

export function TransactionInsightsSummaryToJSONTyped(value?: TransactionInsightsSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'planned': value['planned'],
        'spent': value['spent'],
        'remaining': value['remaining'],
        'income': value['income'],
    };
}

