/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionSpendingByDayPoint
 */
export interface TransactionSpendingByDayPoint {
    /**
     * UTC calendar day in YYYY-MM-DD format.
     * @type {string}
     * @memberof TransactionSpendingByDayPoint
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionSpendingByDayPoint
     */
    amount: number;
}

/**
 * Check if a given object implements the TransactionSpendingByDayPoint interface.
 */
export function instanceOfTransactionSpendingByDayPoint(value: object): value is TransactionSpendingByDayPoint {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function TransactionSpendingByDayPointFromJSON(json: any): TransactionSpendingByDayPoint {
    return TransactionSpendingByDayPointFromJSONTyped(json, false);
}

export function TransactionSpendingByDayPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionSpendingByDayPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'amount': json['amount'],
    };
}

export function TransactionSpendingByDayPointToJSON(json: any): TransactionSpendingByDayPoint {
    return TransactionSpendingByDayPointToJSONTyped(json, false);
}

export function TransactionSpendingByDayPointToJSONTyped(value?: TransactionSpendingByDayPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'amount': value['amount'],
    };
}

