/* tslint:disable */
/* eslint-disable */
/**
 * PennyOS API
 * REST API for PennyOS core functionality. This spec includes currently implemented REST routes only. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface UserListResponse
 */
export interface UserListResponse {
    /**
     * 
     * @type {Array<User>}
     * @memberof UserListResponse
     */
    items: Array<User>;
    /**
     * 
     * @type {number}
     * @memberof UserListResponse
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof UserListResponse
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the UserListResponse interface.
 */
export function instanceOfUserListResponse(value: object): value is UserListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function UserListResponseFromJSON(json: any): UserListResponse {
    return UserListResponseFromJSONTyped(json, false);
}

export function UserListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UserFromJSON)),
        'total': json['total'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function UserListResponseToJSON(json: any): UserListResponse {
    return UserListResponseToJSONTyped(json, false);
}

export function UserListResponseToJSONTyped(value?: UserListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UserToJSON)),
        'total': value['total'],
        'next_cursor': value['nextCursor'],
    };
}

